### ISSUE TITLE
Bug: semi-transparent line rendering issues

### ISSUE THREAD

**Issue by dpocius** [Esri/feedback-js-api-next#10]
**Describe the bug**
Some parts of semi-transparent lines are rendered incorrectly

**To Reproduce**
1. Go to https://jsbin.com/sadewufibi/edit?html,output
2. Observe line rendering issues:
a) Some non-overlapping parts are rendered as overlapped in higher zoom levels
b) Line caps are rendered as non overlapping when that line part overlaps itself (case of u-turn)

**Expected behavior**
Consistent rendering of overlapping and non-overlapping parts of line

**Screenshots**
https://i.imgur.com/Ki7Umij.png (parts of line where it is rendered incorrectly marked in green rectangles)

**Browser (check https://whatismybrowser.com/)** 
 - Browser: Chrome 77 on Windows 10
 
**What's your OS? (check https://whatsmyos.com):**
 - OS: Windows 10* 64-bit
 - Device: Windows desktop PC

**API version (check your console)**
 - Version: n/a (nothing in console)

**Additional context**

**Comment by mmgeorge** [comment]
@dpocius what is the desired behavior in this case? That the feature does not appear to overlap with itself (esame transparency throughout the feature, including the overlapped parts)? Or is the concern with the caps not appearing to overlap in some cases:

![cap](https://user-images.githubusercontent.com/16738762/65985238-43e5a080-e436-11e9-8317-cbcc93a5ef58.PNG)

**Comment by dpocius** [comment]
@mmgeorge Desired behavior here is consistent rendering. If part of line is darker because it overlaps itself, then, I think, line cap (which you have marked in screenshot) should also be darker. Current rendering, when line cap is rendered as not overlapped while all other part of line is overlapping, does not look nice and I can't think of a reasoning from end-user's perspective when this would look valid and not confusing.
On the other hand, if same transparency level would be kept throughout entire polyline, including overlapping parts, there wouldn't be any problems with line caps too. So, I think, keeping same transparency troughout entire feature is also a valid possible behavior.

**Comment by mmgeorge** [comment]
@dpocius well, even if the cap was darker it would still not look great. Maintaining the same transparency throughout the polyline would look better, but this would require quite a bit of work and would like not be for quite some time. Unfortunately rendering semi-opaque lines is an issue a lot of map engines on the web. 

> Current rendering, when line cap is rendered as not overlapped while all other part of line is overlapping, does not look nice and I can't think of a reasoning from end-user's perspective when this would look valid and not confusing.

I don't think the use-case is so much about the visual quality so much about performance. We don't want the rendering of overlapping semi-opaque lines to slow down much more common workflows. We'll take a look at what we can do for the caps, but I'm not sure we'll be able to prioritize this.

**Comment by bsvensson** [comment]
Hi @dpocius 

Thank you for your interest in the `next` version.  About the issue tracking in this github repo:

* Note that this repo is meant for bugs that are new for the `next` version. If your issue also happens in a released version (like 4.12 in this case), you've already done the right thing - reporting it to Esri Support.  See the [README](https://github.com/Esri/feedback-js-api-next/blob/master/README.md#issues) and the [notes when you create a new bug](https://github.com/Esri/feedback-js-api-next/issues/new): _Bug reports should be specific to js.arcgis.com/next and not present in the current release._
