### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by jessebluemr** [Esri/feedback-js-api-next#102]
**Describe the bug**
If a feature of a feature layer with labeling is edited, then the label value is not updated after editing the corresponding field.

**To Reproduce**

1. Go to 'https://codepen.io/jessebluemr/pen/gOLRLpd'
2. Notice the labels "Active", "Pending", "Closed" these labels are created from the field "Status" of a feature.
3. Click "Edit feature"
4. Click on a feature to edit
5. Change in the attribute dialog the value of the Status field.
3. Save the changes.

**Expected behavior**
The label in the map is refreshed according to the new label value.

**Actual behavior**
The label in the map is still the same as before.

**Browser (check https://whatismybrowser.com/)** 
 - Browser: Any but tested with Chrome.
 
**What's your OS? (check https://whatsmyos.com):**
 - OS:  "Windows 10* 64-bit"
 - Device: "Windows desktop PC"

**API version (check your console)**
 - Version: ArcGIS API for JavaScript 4.19-next [Date: 20210217, Revision: 755997bf]

**Additional context**
Reason of the Bug is `esri/views/2d/layers/features/Store2D.js`. The setComputedAttribute method checks a "_canCacheExpressionValue" flag and a bitset to check if calculated attributes need to be recalculated. But in the `updateSchema` method, which is triggered during editing the "bitset" is not cleared if the schema didn't change. Which causes that calculated attributes are never recalculated.

This behavior can be reproduced in 4.18 as well.

**Comment by NoashX** [comment]
Hi @jessebluemr, thanks for posting this issue, and my apologize for the delay in responding here. We fixed this issue already, so it should fine for you today with 4.22 (and later today with 4.23): https://codepen.io/noash/pen/bGaBMxd?editors=1000
