### ISSUE TITLE
Bug: PrintTask not working

### ISSUE THREAD

**Issue by bbarnell** [Esri/feedback-js-api-next#104]
**Describe the bug**
I'm getting this javascript error message in the console window using the PrintTask and it is failing.

TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at g.m._getGpPrintParams (PrintTask.js:41)

**To Reproduce**
Run the attached sample code.

**Browser (check https://whatismybrowser.com/)** 
All browsers
 
**What's your OS? (check https://whatsmyos.com):**
Windows 10 desktop
 
**API version (check your console)**
ArcGIS API for JavaScript 4.19-next

[Test_Print_419_html.txt](https://github.com/Esri/feedback-js-api-next/files/6076305/Test_Print_419_html.txt)

**Comment by NoashX** [comment]
Hi @bbarnell, thanks for reporting this issue. I can reproduce the behavior. We will get this addressed at a future release.

In the meantime, if you define a PrintTemplate property value, the PrintTask will work as expected (see test-app below).

PrintParameters + template
https://codepen.io/noash/pen/eYBoaqK?editors=1000

**Comment by bbarnell** [comment]
I like easy fixes.  Thanks.

**Comment by NoashX** [comment]
As a bonus, this is now fixed on `next`: https://codepen.io/noash/pen/LYbKyVz?editors=1000
