### ISSUE TITLE
Enhancement: Using the daylight widget on Mars and Moon

### ISSUE THREAD

**Issue by tkamiya0625** [Esri/feedback-js-api-next#106]
**Enhancement category**
Widgets

**Enhancement short summary**
I want to support and display the daylight widget on Mars and Moon.

**Enhancement description**
I want the daylight widget to work correctly on Mars and Moon.

https://developers.arcgis.com/javascript/latest/sample-code/mars/
https://developers.arcgis.com/javascript/latest/sample-code/widgets-daylight/

**Severity**
High or Medium

**Screenshots**
<img width="500" alt="" src="https://user-images.githubusercontent.com/59276069/110099425-a50c6300-7de4-11eb-850a-5611e5390365.png">
You can use the daylight widget, but it's not accurate.

**API version (check your console)**
 - Version: Using ArcGIS API for JavaScript 4.13-next [Date: 20210301, Revision: 393c503a]

**Additional context**
I would like to use it for one of my projects.

**Comment by RalucaNicola** [comment]
I'm sorry @tkamiya0625, but we don't plan to implement this in the near future. However, do let us know about your use case and I'll add to our list of user requirements.

**Comment by tkamiya0625** [comment]
@RalucaNicola 
Thank you for contacting me.
We have a customer who is interested in visualizing monthly data, and we are going to use ArcGIS to do it.

I would like to send you more information about the project individually.

**Comment by tkamiya0625** [comment]
@RalucaNicola 
Sorry, It's hard to tell you the details here, but we are considering switching from open source to ArcGIS API for JavaScript, which is a public system with an English version of the website.

**Comment by SaschaBrunnerCH** [comment]
Tracked now internal as a future enhancement.
