### ISSUE TITLE
SceneView in Angular 

### ISSUE THREAD

**Issue by catalinconstant** [Esri/feedback-js-api-next#107]
I'm geting errors messages when I tried jsapi-angular-cli but using SceneView with the following changes in the code 
`... 
import SceneView from '@arcgis/core/views/SceneView';
....
initializeMap(): Promise<any> {
    const container = this.mapViewEl.nativeElement;
    const map = new Map({
      basemap: "satellite", // Basemap layer service,
      ground: "world-elevation"
    });
    this.view = new SceneView({
      map: map,
      center: [-118.805, 34.027], // Longitude, latitude
      zoom: 13, // Zoom level
      container: container, // Div element
    });
 return this.view.when();
  }
...
`
Error message 
`Unhandled Promise rejection: Aborted ; Zone: <root> ; Task: null ; Value: DOMException: Aborted undefined
  | api.onUnhandledError | @ | zone-evergreen.js:659
-- | -- | -- | --
  | handleUnhandledRejection | @ | zone-evergreen.js:679
  | api.microtaskDrainDone | @ | zone-evergreen.js:673
  | drainMicroTaskQueue | @ | zone-evergreen.js:576
  | Promise.then (async) |   |  
  | scheduleMicroTask | @ | zone-evergreen.js:552
  | resolvePromise | @ | zone-evergreen.js:810
  | (anonymous) | @ | zone-evergreen.js:705
  | (anonymous) | @ | requestUtils.js:5
  | ZoneAwarePromise | @ | zone-evergreen.js:960
  | t | @ | requestUtils.js:5
  | Y | @ | request.js:5
  | G | @ | request.js:5
  | Q | @ | request.js:5
  | async function (async) |   |  
  | Q | @ | request.js:5
  | U | @ | request.js:5
  | async function (async) |   |  
  | U | @ | request.js:5
  | startLoading | @ | StreamDataLoader.js:5
  | (anonymous) | @ | StreamDataLoader.js:5
  | push | @ | AsyncWorkerQueue.js:5
  | createTask | @ | StreamDataLoader.js:5
  | createOrUpdateTask | @ | StreamDataLoader.js:5
  | request | @ | StreamDataLoader.js:5
  | request | @ | ResourceController.js:5
  | _requestMapTileData | @ | TerrainSurface.js:5
  | _requestTileData | @ | TerrainSurface.js:5
  | (anonymous) | @ | TerrainSurface.js:5
  | process | @ | PromiseQueue.js:5
  | processQueue | @ | Scheduler.js:5
  | _update | @ | TerrainSurface.js:5
  | (anonymous) | @ | TerrainSurface.js:5
  | _run | @ | Scheduler.js:5
  | _runInteracting | @ | Scheduler.js:5
  | frame | @ | Scheduler.js:5
  | frame | @ | ResourceController.js:5
  | update | @ | ResourceController.js:5
  | (anonymous) | @ | scheduling.js:5
  | forAll | @ | PooledArray.js:5
  | x | @ | scheduling.js:5
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552
  | requestAnimationFrame (async) |   |  
  | scheduleTask | @ | zone-evergreen.js:2573
  | scheduleTask | @ | zone-evergreen.js:385
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMacroTask | @ | zone-evergreen.js:233
  | scheduleMacroTaskWithCurrentZone | @ | zone-evergreen.js:1134
  | (anonymous) | @ | zone-evergreen.js:2586
  | proto.<computed> | @ | zone-evergreen.js:1449
  | j | @ | scheduling.js:5
  | invokeTask | @ | zone-evergreen.js:399
  | runTask | @ | zone-evergreen.js:167
  | invokeTask | @ | zone-evergreen.js:480
  | ZoneTask.invoke | @ | zone-evergreen.js:469
  | timer | @ | zone-evergreen.js:2552

`
It seems that workers are in the Ng Zone

**Comment by catalinconstant** [comment]
@andygup  the version is @arcgis/core@4.19.0-next.20210315
I tried again with the same errors.

**Comment by andygup** [comment]
Gotcha, thanks. We have an active issue to look into this.

**Comment by andygup** [comment]
@catalinconstant there are a couple of things you can try. Let us know if these steps fix the errors?
* Upgrade your Angular to 11.2.x: `ng update @angular/cli @angular/core`
* Change your ts.config > compilerOptions > target to `es2017`.
* Update Zone.js to `0.11.4` - you'll need this update anyways when Angular 12 comes out in a few months.

**Comment by catalinconstant** [comment]
@andygup With your "steps", now are no errors.
Thanks

**Comment by andygup** [comment]
Sweet, I'll go ahead and close. 

For reference, this "fix" is related to the discussions in the following thread on Angular and zone.js support for async/await : https://github.com/angular/angular/issues/31730
