### ISSUE TITLE
General enhancement - support for JavaScript Proxy in Esri JS API classes / objects

### ISSUE THREAD

**Issue by crackernutter** [Esri/feedback-js-api-next#108]
**Enhancement category**
Other

**Enhancement short summary**
Enable the API classes / objects to be wrapped in a JavaScript Proxy so as better integrate with 3rd party libraries (most notably Vue 3.x) for intercepting and reacting to changes.  Currently this does not seem to work. 

**Enhancement description**
Unclear what it would entail but I imagine it has to do with modifying the Accessor class. 

**Severity**
Low - this is really just for better integration with Vue 3.x.

**API version (check your console)**
 -  4.19-next [Date: 20210311, Revision: 683c2714].  (Seems like the latest next revisions in this repo will not load using esri-loader)

See https://community.esri.com/t5/arcgis-api-for-javascript/arcgis-js-api-4-x-not-supported-with-vuejs-3-0/m-p/120231
original issue.

**Comment by andygup** [comment]
Thanks @crackernutter, sorry I missed your December question over on the "community" post. As @CalebM1987 pointed out in his response - the current pattern is to use Accessor and watchUtils to manage change detection and keep that separate. You can create unwanted overhead by adding that additional layer of abstraction. We'll discuss internally about the long term plan for working with framework state management.

**Comment by steveoh** [comment]
Would there be a complexity reduction in the api by changing accessor to use native proxy objects now that the api support matrix makes using them viable? Is there feature parity between proxy objects and accessor as in would it be a viable replacement?
