### ISSUE TITLE
Enhancement: Provide better Tree Shaking Support

### ISSUE THREAD

**Issue by CalebM1987** [Esri/feedback-js-api-next#109]
**Enhancement category**
How would you categorize the enhancement?  `@arcgis/core`

**Enhancement short summary**
The new `@arcgis/core` package does not appear to use any Tree Shaking, resulting in extremely large builds.  The same application built with `esri-loader` is almost 100x smaller.

**Enhancement description**

It would be great to see the structure of this package get refactored to better support [Tree Shaking](https://developers.google.com/web/fundamentals/performance/optimizing-javascript/tree-shaking).  I have created a test app that uses `@arcgis/core` to load the JS API and the [esri-loader](https://github.com/Esri/esri-loader) in another branch and the differences in build size are astonishing.  I am fully aware that the [arcgis-webpack-plugin](https://github.com/Esri/arcgis-webpack-plugin) can be used to trim this down a bit, but I think there should be some tree shaking that happens out of the box without having to get [webpack](https://webpack.js.org/) involved. I also do not know if there is an equivalent plugin for [Rollup](https://rollupjs.org/guide/en/)?

One of the advantages of using ES modules is that we can use `import` and `export` to allow module bundlers such as webpack or rollup to interpret the dependency tree and only include things that are actually being used in the final build of an application.

My demo app uses only three modules (`esri/config`, `esri/Map`, `esri/views/MapView`) and the build size jumps from `210 KB` using the `esri-loader` to `34.7 MB`

EDIT: I know that by using the esri-loader it does not include anything in the JS API in the bundle. My point is if I’m only using 3 modules from @arcgis/core why is it still bundling megabytes of stuff from the JS API? I understand those 3 modules have dependencies too, but I can’t fathom that those dependencies are ~10 MB in size of minified code.

**Severity**
How important is this enhancement and why? High 

I believe this is a very important enhancement, when a build of the same app goes from `210 KB` to `34.7 MB`, it seems like something is very wrong.

**Screenshots**

`esri-loader` build:

![esri loader build](https://github.com/CalebM1987/arcgis-core-vs-esri-loader/raw/master/docs/esri-loader-fullbuild-explorer.png)

`@arcgis/core` build:

![arcgis core build](https://github.com/CalebM1987/arcgis-core-vs-esri-loader/raw/master/docs/arcgis-core-fullbuild-explorer.png)

**API version (check your console)**
 - Version: 4.18

**Additional context**
The repo showing the code can be found here:

https://github.com/CalebM1987/arcgis-core-vs-esri-loader

Tree shaking article:

https://bluepnume.medium.com/javascript-tree-shaking-like-a-pro-7bf96e139eb7

**Comment by ycabon** [comment]
Hi Caleb,

The bundlers are tree-shaking the API already. The problem you encounter is something else.

`esri-loader` loads API modules modules dynamically from the js.arcgis.com CDN. So they don't account in the since of the built application. 
By [importing the `@arcgis/core` modules directly in your code](https://github.com/CalebM1987/arcgis-core-vs-esri-loader/blob/master/src/views/MapView.vue#L10-L12) your are embedding the code in your build folder.

If you want to lower the initial app download you can load API modules from `@arcgis/core` dynamically as well:

```js
const [{ default: Map }, { default: MapView }] = Promise.all([
  import("@arcgis/core/Map"),
  import("@arcgis/core/MapView")
]);
```

But the bundler will still include all the dependencies from `Map` and `MapView` in your build folder.

**Comment by CalebM1987** [comment]
I am aware that using the `esri-loader` does not bundle any ArcGIS API stuff and that it uses `<script>` tags to lazy load the API via CDN.  But I am only using three modules and just the `js` folder is `10 MB`. It seems like it is bundling the entire JS API and not just the three modules and their dependencies.  

Even with all the CDN loads in my `esri-loader` version, it does not load nearly as much content as when I run the `@arcgis/core` version.  See the Network Tab from an Incognito Chrome window:

`esri-loader`:
 
* 9 JS file requests, `3.2 MB` (which includes stuff from the CDN)

![image](https://user-images.githubusercontent.com/6826046/111704748-a5a5f000-880d-11eb-92c4-c17b87063013.png)


`@arcgis/core`

* 31 JS file requests, `11.8 MB`

![image](https://user-images.githubusercontent.com/6826046/111704516-447e1c80-880d-11eb-9ef4-1fdf1919efdf.png)
 
continued:
![image](https://user-images.githubusercontent.com/6826046/111704600-65467200-880d-11eb-8791-82d0d1341fde.png)

**Comment by andygup** [comment]
> 31 JS file requests, 11.8 MB

@CalebM1987 This seems more like a question about build optimization, and it depends on the module bundler and fine tuning the optimization settings. 

I upgraded your Vue sample to use `@arcgis/core@next` and did a production build. When running `"@arcgis/core": "^4.19.0-next.20210318"` (and at 4.19 which will release in early April) you don't need to copy the assets anymore, they are pulled from CDN. 

I'm seeing 2.3 MBs of .js files at runtime and 13.1MBs on-disk:

![image](https://user-images.githubusercontent.com/510440/111714836-2b2e9d80-8818-11eb-8efa-83dcdc297023.png)


![image](https://user-images.githubusercontent.com/510440/111714548-7d22f380-8817-11eb-99e9-46fb1324d1cd.png)

-----

For comparison, here's what I'm seeing in an Angular 11.2.5 distribution build using webpack 4.44.2 and mostly just default settings. The .js bundles for a Hello World 2D app are weighing in at 2.8MB and on-disk size of 8.2MBs:

![image](https://user-images.githubusercontent.com/510440/111712376-1d2a4e00-8813-11eb-8990-04825ffa5cb6.png)

![image](https://user-images.githubusercontent.com/510440/111713850-00dbe080-8816-11eb-9736-a39ecde4a65d.png)

**Comment by CalebM1987** [comment]
@andygup thanks for sharing that.  I did not know about `@arcgis/core@next` and it is good that the bundle size gets reduced down to `13.1 MB`, which is quite an improvement.  However, that still seems quite large considering that only 3 modules are used to simply display a map:

```ts
import Map from '@arcgis/core/Map'
import MapView from '@arcgis/core/views/MapView'
import esriConfig from '@arcgis/core/config'
```

So are you saying that just those three modules and their dependencies are making up most of that 13 MB?  I know the ArcGIS JS API is huge and supports a lot of really nice features, but it almost seems like it is loading the entire API instead of just a few modules in this simple example of just displaying a map.  And that seems to be reflected in the runtime via the network tab showing only 2.3 MB of JS content being loaded out of the 13 MB bundle. I am also not lazy loading any components that wouldn't be loaded up front. This is essentially a `hello world` version of JS API.  

For an apples to apples comparison of JUST displaying a map, I added [another branch to that repo](https://github.com/CalebM1987/arcgis-core-vs-esri-loader/tree/mapbox-gl) for displaying a map with Mapbox GL. This had a build size of 1.3 MB, and a runtime memory of 989 KB:

![image](https://user-images.githubusercontent.com/6826046/111731170-e3703c00-8840-11eb-96ff-d958bd1f8ca3.png)

We occasionally use Mapbox GL for other less mapping intensive/cartographic centric applications so it's a natural comparison given the fact it's also a mapping api.  Obviously ArcGIS JS API is a more robust api so I'd expect some size difference but ~10mb is quite significant. Mapbox GL is also fairly large and I was able to produce a much smaller bundle with no webpack optimization.  So to me, unless the dependencies used by `Map` and `MapView` really are that large, it seems like the structure of `@arcgis/core` is not as "tree shaking/bundle friendly" as other libraries?  Long story short, I'm just wondering why the bundle is so big (even at 13 MB) when only using 3 modules?

**Comment by odoe** [comment]
Size on disk isn't a good metric to go on. There's a lot of dynamically loaded code in the API `const a = await import('../something')`, for layers, renderers, and more. Being pure ESM, the API will be tree shaken accordingly.

Even modern build tooling isn't as configurable as the dojo build tools for creating bundles. This is why the CDN bundles can be more efficient in some situations, we can have some very fine grained control to build the bundles. And honestly, we've had over ten years of practice to make it work very well. Modern build tools that _chunk_ don't really have that type of fine grained control. I think we're getting there though, and there might be some ways to trim it down further using third-party tools during build time, but I think they can overcomplicate the process.

I would not recommend the use of `@arcgis/webpack-plugin` unless assets are needed locally.

We've reviewed a monorepo approach for the API in the past, and it wouldn't change size on disk or build size. It's not something currently on our road map.

**Comment by CalebM1987** [comment]
> Size on disk isn't a good metric to go on. There's a lot of dynamically loaded code in the API const a = await import('../something'), for layers, renderers, and more. Being pure ESM, the API will be tree shaken accordingly. You may not use all the code on disk, but based on how a service might behave or what it supports, there are chunks you could use.

@odoe ahhh, that is the part I was missing.  It makes more sense now.  So based on @andygup's example using `@arcgis/core@next`, only 2.3 MB is actually being loaded on the client, which is probably the bare bones `MapView` and any dependencies it needs and why it only loaded 11 out of x number of js bundles.  This is much closer to the number I was expecting (I was thinking around double of what mapbox gl would use).

I'm assuming this means that as you start integrating more functionality, i.e. adding layers or working with map graphics, that is when you would see more of those bundles getting loaded asynchronously, so in effect they are just waiting to be used.  Which in the simple map case, they aren't needed, but because `MapView` supports so much functionality, the tree shaken modules of possible functionality that *could* be used are included?

In that case, I'm happy!  I was very excited to see that we can just `import` the js api now but was hesitant to use in any production app because of the bundle size of the build.  But really, that doesn't seem like as big of an issue as additional chunks will be loaded asynchronously on demand.  We often lazy load different views/components anyways, so in most cases we wouldn't even load the mapping portion of the bundle on first paint.

Now that I know how this is working under the hood, I don't think this is an issue anymore.
