### ISSUE TITLE
Bug: Inconsistent rendering of line caps between GraphicsLayer and FeatureLayer

### ISSUE THREAD

**Issue by dpocius** [Esri/feedback-js-api-next#11]
**Describe the bug**
When the line is rendered in GraphicsLayer, line caps are rendered as round. When the same line is rendered using FeatureLayer - same line caps are rendered as butt/square.

**To Reproduce**
1. Go to https://jsbin.com/sadewufibi/edit?html,output
2. Observe that line caps are rendered as round in GraphicsLayer (e.g. most bottom part, u-turn case)
3. Go to https://jsbin.com/qazikoqaja/edit?html,output
4. Observe that the same line caps are rendered as butt/square

**Expected behavior**
Result of rendering same line in GraphicsLayer and FeatureLayer should be equal

**Screenshots**
Line rendered in GraphicsLayer: https://i.imgur.com/s2vrrAS.png
Line rendered in FeatureLayer: https://i.imgur.com/biusrU6.png

**Browser (check https://whatismybrowser.com/)** 
 - Browser: Chrome 77 on Windows 10
 
**What's your OS? (check https://whatsmyos.com):**
 - OS: Windows 10* 64-bit
 - Device: Windows desktop PC

**API version (check your console)**
 - Version: n/a (nothing in console)

**Additional context**

**Comment by mmgeorge** [comment]
@dpocius the differences you see are due to some additional processing we have enabled for graphics. Due to time processing constraints, we currently do not apply this logic in the case of FeatureLayers or VectorTileLayers. This is a known limitation for now and we are looking at ways to improve this area and speed up mesh processing.

**Comment by bsvensson** [comment]
Hi @dpocius 

Thank you for your interest in the `next` version.  About the issue tracking in this github repo:

* Note that this repo is meant for bugs that are new for the `next` version. If your issue also happens in a released version (like 4.12 in this case), please report it to Esri Support (if you haven't already). See the [README](https://github.com/Esri/feedback-js-api-next/blob/master/README.md#issues) and the [notes when you create a new bug](https://github.com/Esri/feedback-js-api-next/issues/new): _Bug reports should be specific to js.arcgis.com/next and not present in the current release._
