### ISSUE TITLE
Enhancement: Problem with FeatureLayer url after using a reverse proxy community.esri.com.

### ISSUE THREAD

**Issue by boualikamel** [Esri/feedback-js-api-next#114]
Hi all, 

I don't know if it's really a problem, i think that there is a problem after declaring the url in the featurelayer class when using the reverse proxy, nginx or apache, or a local devserver proxy.

For example i have this configuration of proxy the path 

      /gis" targetting the "https://localhost:6443" link
 
the declaration of my featurelayer is like this 
 
```
   new FeatureLayer({
    url: "gis/arcgis/rest/services/geo/MapServer/0",
    title:'point',
  }),
```
 

nothing is displayed on the map, so i followed my network on the browser and I noticed that the id of my featurelayer is duplicated on the link
 
http://localhost:3000/gis/arcgis/rest/services/geo/MapServer/0/0/quer.......
 
the 0 in the link is duplicated 
so i would like if to look this is normal
 
cordially

**Comment by pspraveenkr** [comment]
> "gis/arcgis/rest/services/geo/MapServer/0"

You have used a relative url in the declaration. Can you try the full url like this?

`http://localhost:3000/gis/arcgis/rest/services/geo/MapServer/0`

**Comment by boualikamel** [comment]
> `http://localhost:3000/gis/arcgis/rest/services/geo/MapServer/0`

Yes I have tried it before and it works, but I think it's a problem that the api adds one more number in the link, I used before the 3.x api and it worked normally.

i need to use it like this to avoid declaring global variables for thes ip addresses.

**Comment by dasa** [comment]
Can you try `location.origin + "/gis/arcgis/rest/services/geo/MapServer/0"`

**Comment by boualikamel** [comment]
> Can you try `location.origin + "/gis/arcgis/rest/services/geo/MapServer/0"`

Oh yes it's a good idea to , i've triied `window.location.origin` and it worked, thank you @dasa 

so, we conclude that the api doesn't support relative path when using featurelayer ?

**Comment by pspraveenkr** [comment]
> so, we conclude that the api doesn't support relative path when using featurelayer ?

Correct.

**Comment by joel-bennett** [comment]
See also https://community.esri.com/t5/arcgis-api-for-javascript/4-16-featurelayer-bug-when-using-relative-url-for-service/m-p/41118

**Comment by boualikamel** [comment]
Hello, 

DONE, in the 4.20 version.

thank you
