### ISSUE TITLE
[@arcgis/core] Bug: BasemapToggle background images not using `assetPath` from configs 

### ISSUE THREAD

**Issue by pallymore** [Esri/feedback-js-api-next#115]
**Describe the bug**
Hi - I've noticed the `BasemapToggle` doesn't always respect the `assetPath` configuration - see the screenshot below: I've configured `assetPath` to be `/_/assets`, the placeholder image works correctly but the active basemap thumbnails are still using the default path: 

![CleanShot 2021-04-05 at 09 52 12](https://user-images.githubusercontent.com/2566530/113581100-ac49ab00-95f4-11eb-81f8-68598a627ee9.png)

Here's my config 

```ts
import config from '@arcgis/core/config';
import { buildNumber } from './config';

config.assetsPath = `/${buildNumber}/assets`;
```

i'm using the BasemapToggle like this

```ts
import { useEffect } from 'react';
import BasemapToggle from '@arcgis/core/widgets/BasemapToggle';

// .. component code omitted

  useEffect(() => {
    const basemapToggle = new BasemapToggle({
      view,
      nextBasemap: Object.values(EsriBaseMaps).filter(v => v !== basemap.id)[0],
    });

    view.ui.add(basemapToggle, position);

    return () => {
      view.ui.remove(basemapToggle);
    };
  }, [view, basemap, position]);

// ...component code omitted

```

I have a `Map` component which is loaded in the /map page - this config file is loaded in the same Map component file. 

Curiously though, if I import the config in the application root (index.js) - **the images work correctly**. It only doesn't work when we import the file at the same time as importing the map. 
However I'm trying to avoid doing so since this is a relatively big application - we are trying to reduce bundle sizes as much as possible (also some old pages still need to support IE11, we are only making /map as the only feature that require modern browsers). 

**Framework and build tools** 
React        16.14
Webpack  4.x
@arcigs/webpack-plugin

**To Reproduce**
1. config `assetPath` and load it along with the map
2. load the map with BasemapToggle
3. see the placeholder image works correctly but not the other thumbnails in the toggle.

**Expected behavior**
The dynamically added background images for BasemapToggle should use the same `assetPath` as the default placeholder image.

**Browser (check https://whatismybrowser.com/)** 
Chrome 89
 
**What's your OS? (check https://whatsmyos.com):**
macOS 11

**API version (check your console)**
4.18.1

**Additional context**
I've also tried setting `window.esriConfig = { assetPath: '/_/assets' };` - same issue.

I've just tried lazy-loading the `BasemapToggle` component but it didn't help either. 

```tsx
// Map.tsx
import './config-arcgis-core'; // file that contains the configurations shown above

// Map component -> 
return (
  // other components omitted
  <React.Suspense fallback={<></>}>
    // BasemapToggle is a custom component that wraps `BasemapToggle` from @arcgis/core 
    <BasemapToggle view={view} basemap={map.basemap} />
  </React.Suspense>
);
```

**Comment by andygup** [comment]
@pallymore thanks for reporting the issue. We think we have fixed this in the upcoming 4.19 release, which will be available later this month.

Can you run `npm i @arcgis/core@next` and try again?

Also note, in the 4.19 release you won't have to explicitly set the `assetsPath` if you don't need to work with local assets, by default the assets will be loaded via CDN. That should be good news since it will also reduce your on-disk final build size. Once you install `@next` you might also try commenting out the assets configuration and see if that also works.

> also some old pages still need to support IE11

Just a heads up on IE11, ArcGIS JS API versions 4.18+ do not support IE 11. Reference: https://developers.arcgis.com/javascript/latest/release-notes/#end-of-ie11edge-legacy-support

**Comment by pallymore** [comment]
> @pallymore thanks for reporting the issue. We think we have fixed this in the upcoming 4.19 release, which will be available later this month.
> 
> Can you run `npm i @arcgis/core@next` and try again?
> 
> Also note, in the 4.19 release you won't have to explicitly set the `assetsPath` if you don't need to work with local assets, by default the assets will be loaded via CDN. That should be good news since it will also reduce your on-disk final build size. Once you install `@next` you might also try commenting out the assets configuration and see if that also works.
> 
> > also some old pages still need to support IE11
> 
> Just a heads up on IE11, ArcGIS JS API versions 4.18+ do not support IE 11. Reference: https://developers.arcgis.com/javascript/latest/release-notes/#end-of-ie11edge-legacy-support

Hi - thanks for the quick response.

`@next` seems to work both with and without `assetPath` configurations. 
However it also introduced some typing errors for us so we probably can't use it right now. 
Will the fix be released in a patch version for 4.18? Are there any other workarounds we can try?

**Comment by andygup** [comment]
> Will the fix be released in a patch version for 4.18? 

No, sorry, there won't be a patch for 4.18. However, 4.19 release is coming later this month.  You can continue to use local assets if you want at 4.19, that functionality will still be available.

> However it also introduced some typing errors for us

Can you open a new issue for the typing errors? 

> But now we seem to have load @arcgis/core/config in application root which makes the whole app incompatible

Can you provide more information on the incompatibility issue?

**Comment by pallymore** [comment]
> > Will the fix be released in a patch version for 4.18?
> 
> No, sorry, there won't be a patch for 4.18. However, 4.19 release is coming later this month. You can continue to use local assets if you want at 4.19, that functionality will still be available.
> 
> > However it also introduced some typing errors for us
> 
> Can you open a new issue for the typing errors?
> 
> > But now we seem to have load @arcgis/core/config in application root which makes the whole app incompatible
> 
> Can you provide more information on the incompatibility issue?

Hi - will do, if i figure out the source of those errors. the app compiles fine with 4.18.1. It's probably related to `@types/arcgis-js-api` (since there doesn't seem to be a 4.19 typing) - is there a separate typing library for `@arcgis/core`? 

Is there a 4.19 changelog we can see right now? 

re: incompatibility issue - sorry I wasn't being very clear. We understand that IE11 won't be supported (and that's ok with us), so we are just trying to avoid loading `@arcgis/core` in our legacy pages where IE11 support is still needed, and only use it in newer pages.

**Comment by andygup** [comment]
For the typings issue, can you provide  a larger snippet of code that shows how `view` is being created?

It looks like you are auto-casting, and if so then you may need to declare the `type`. Here's a documentation page on auto-casting that might help: https://developers.arcgis.com/javascript/latest/programming-patterns/#autocasting. The doc gives examples in AMD, but the underlying API functionality is exactly the same in the ES modules.

**Comment by pallymore** [comment]
> For the typings issue, can you provide a larger snippet of code that shows how `view` is being created?
> 
> It looks like you are auto-casting, and if so then you may need to declare the `type`. Here's a documentation page on auto-casting that might help: https://developers.arcgis.com/javascript/latest/programming-patterns/#autocasting. The doc gives examples in AMD, but the underlying API functionality is exactly the same in the ES modules.

Hi - I looked into it a bit closer and somehow it has something to do with my `widgetParams.current` - it's a ref that holds the additional parameters for each tool.

The view itself is a simple `MapView` 

```ts
const view = new MapView({ ... });
```

This hook here is a factory that returns different hooks based on the input - we had it mostly for working with esri-loader but I think we can get rid of it now. It works something like this:

```ts
// type - one of pre-defined types, e.g. measure, sketch
// view - __esri.MapView
// params -> __esri.MeasureProperties | __esri.SketchProperties | ... etc.
const useInitWidget = ({ type, view, ...params}) => {
  // ... some code omitted
  useEffect(() => {
     switch (type) {
       case MEASURE:
         return new Measure({ view, ...params });
       case SKETCH:
         return new Sketch({ view, ...params });
       // ... etc
     }
  }, [type, view]);
}
```

the error goes away if i explicitly type `params` instead of using a union type, e.g:

```ts
new Measure({ view, ...(params as __esri.MeasureProperties) });  // no error...
```

I'm a bit curious why it worked in 4.18 though. 

I couldn't find any information about `__esri.AttachmentInfo` in the changelog, it seems in 4.19, that interface is empty - resulting in errors like this: 

![CleanShot 2021-04-05 at 19 11 21](https://user-images.githubusercontent.com/2566530/113637499-bb574a00-9642-11eb-94e8-a4e14576d5ce.png)

I fixed those by replacing all `__esri.AttachmentInfo` with `__esri.supportAttachmentInfo` - it'd be great if this is noted in the changelog though.

**Comment by NoashX** [comment]
> I fixed those by replacing all __esri.AttachmentInfo with __esri.supportAttachmentInfo - it'd be great if this is noted in the changelog though.

Thanks for reporting this @pallymore. This was not intentional, and we will investigate the AttachmentInfo typings (so you might need to change those replacements back in the near future). I'll update this issue when we have an update to share.

**Comment by NoashX** [comment]
@pallymore - Turns out this was intentional. `esri/layers/support/AttachmentInfo` has been moved to `esri/rest/query/support/AttachmentInfo`. While this is not a breaking change for JavaScript users, it is a breaking change for TypeScript users. This has been added to the Release Notes for 4.19. Thanks again for catching this.

**Comment by pallymore** [comment]
> @pallymore - Turns out this was intentional. `esri/layers/support/AttachmentInfo` has been moved to `esri/rest/query/support/AttachmentInfo`. While this is not a breaking change for JavaScript users, it is a breaking change for TypeScript users. This has been added to the Release Notes for 4.19. Thanks again for catching this.

Thanks for the update!

**Comment by andygup** [comment]
Closing as resolved. Thanks again for reporting!
