### ISSUE TITLE
Port SnappingManager from 3.x or provide equivalent 

### ISSUE THREAD

**Issue by dcworldwide** [Esri/feedback-js-api-next#116]
**Enhancement category**
MapView  + SceneView  + Graphics Layer 

**Enhancement short summary**

For years my large gov client has spent millions of dollars developing and operating a state wide permitting system that relies heavily on graphic editing/snapping using the 3.x api. They desperately want to port this product to 4.x and have been waiting in frustration for years for 4.x to support snapping. Please add to version 4.19 and provide guidance for when this is available to begin beta testing. We have contacted ESRI support numerous times over the years and they have be deflected our requirement. 

**Enhancement description**
Our graphic editing workflows require:

- Snapping to other feature layers (which act as a guide). E.g. cadastral parcels, government boundaries. 
- Snapping to other graphics within graphic layers 
- Self snapping not required but useful. 
- Snapping is critical to ensuring accurate permit costing 

**Severity**
High

**Comment by COV-GIS** [comment]
Snapping is in beta and available for testing.

```shell
npm install @arcgis/core@next --save
```

It's been a while coming. But the Esri JS team got it right.

Thanks for doing awesome. :)

**Comment by dcworldwide** [comment]
Does the implementation solve both of our use cases though? 

  Snapping to other feature layers (which act as a guide). E.g. cadastral parcels, government boundaries.
  Snapping to other graphics within graphic layers

**Comment by Biboba** [comment]
In case you missed it @dcworldwide, snapping seems to be now available in 4.19:
https://developers.arcgis.com/javascript/latest/release-notes/#snapping

**Comment by boualikamel** [comment]
Yes snapping is available but only in the sketch widget ! and  editor widget ! 

Unfortunately we can't manage or use it independently without using these widgets ! 

i really hope that this feature will be released in the next version, we are very late on our projects because of this !

**Comment by sebastianfrey** [comment]
@boualikamel You can use the [SketchViewModel](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Sketch-SketchViewModel.html) as low level API to implement Editing and Drawing with snapping support.

I built an enhanced Sketching-API by subclassing SketchViewModel to enable transaction based editing of various layer types in our application.

**Comment by banuelosj** [comment]
@dcworldwide,
Based on the requirements mentioned for snapping functionality you were waiting for in 4x:
- Snapping to other feature layers (which act as a guide). E.g. cadastral parcels, government boundaries.
- Snapping to other graphics within graphic layers
- Self snapping not required but useful.

This is all available already in 4x whether you are working with Sketch, SketchViewModel, or Editor. We have an example with working with SketchViewModel and the SnappingControls widget which allows you to configure snapping properties via a UI.
- https://developers.arcgis.com/javascript/latest/sample-code/sketch-viewmodel-styler/

I will be closing this issue now.
