### ISSUE TITLE
Track widget broken in other spatialReference systems 

### ISSUE THREAD

**Issue by ChristopheSuter** [Esri/feedback-js-api-next#118]
Error in track widget, does not work anymore in other spatialReferences.
See codepen
https://codepen.io/christophesuter/pen/gOgQyvo?editors=1000

**Comment by ChristopheSuter** [comment]
Same for Locate widget...

**Comment by Biboba** [comment]
Hope it will be patched... 4.19 is out with the bug :(

**Comment by ChristopheSuter** [comment]
Patch by Mrs Fitz:
https://codepen.io/annefitz/pen/jOyXOzL?editors=1010

require(["esri/tasks/support/ProjectParameters"], function(ProjectParameters) {        
  Object.defineProperty(ProjectParameters.prototype, "outSR", {
    set(value) {
      this.outSpatialReference = value;
    },
  });
});

**Comment by ubatsukh** [comment]
This was fixed at 4.19.
