### ISSUE TITLE
Enhancement: Snap function for rotating while sketching.

### ISSUE THREAD

**Issue by sebastianfrey** [Esri/feedback-js-api-next#120]
**Enhancement category**
Sketching

**Enhancement short summary**
Snap function for rotating while sketching.

**Enhancement description**
As a user (developer) of the ArcGIS API for JavaScript 4.x, I would like to offer the users of my application the possibility to rotate an already drawn feature by a defined angle step by step while sketching by holding a defined key. Both key and angle should be parameterizable by the developer.

**Severity**
Medium

**Comment by banuelosj** [comment]
There is an internal enhancement created to add this request. In order to track the status of this enhancement, please reach out to technical support to submit a report to track this enhancement.

https://support.esri.com/en
