### ISSUE TITLE
Bug: UI blocking with deep nested GroupLayer's

### ISSUE THREAD

**Issue by sebastianfrey** [Esri/feedback-js-api-next#121]
**Describe the bug**
I encountered an issue when creating simultaneously multilpe hierarchical grouplayers which causes heavy UI blocking. For convenience I have provided an example appliaction which reproduces the encountered issue. The related soruce code can be found here https://github.com/sebastianfrey/multiple-grouplayers-block-ui.

**To Reproduce**
1. Go to 'https://sebastianfrey.github.io/multiple-grouplayers-block-ui/'
2. Wait until map is loaded and click 'GENERATE'
3. Play around with different Layer amount
4. You should notice heavy UI blocking with increasing Layer amount.

**Expected behavior**
Block not the UI.

**Screenshots**

**Browser** 
 - Browser: Does not matter.

**Additional context**
See also BUG-000137996.

**Comment by ycabon** [comment]
Hello @sebastianfrey,

Thanks for the report and the repro app. I see where it's coming from and I'll have a fix for 4.20. 

Thanks!

**Comment by sebastianfrey** [comment]
Hello @ycabon,

Thanks for letting me know.

Since this issue blocks the development schedule of a feature in one of my projects, I would like to ask whetere it's possible to let me know, when your fix hits @arcgis/core#4.20-next? So I could continue on that feature before the 4.20 release.

Thanks!

**Comment by ycabon** [comment]
The fix is in the latest `@arcgis/core@next`

**Comment by sebastianfrey** [comment]
I can confirm, the issue is fixed. Thanks!
