### ISSUE TITLE
Bug: Graphics Added to GraphicLayer do not render until you Zoom when Zone.js is in use

### ISSUE THREAD

**Issue by dougkpowers** [Esri/feedback-js-api-next#122]
**Describe the bug**
When adding graphics to a graphic layer, the graphics do not render immediately.  If you zoom the map, the graphics then appear. 

I'm only able to reproduce this issue when importing Zone.js.

**To Reproduce**

1. See codepen created to reproduce the error here: https://codepen.io/dougrt/pen/NWpqGGq.  This cocepen mixes ES modules and dojo.  Here is another codepen (same example) but purely using ES modules: https://codepen.io/dougrt/pen/PopqLWv
2. There should been a red square in Nevada, but you won't see it
3. Zoom in and the red square will appear
4. Remove the import (in the JS section of the code pen) and the issue goes away

**Expected behavior**
The red square should appear as soon as the graphic is added to the layer.

**Browser (check https://whatismybrowser.com/)** 
Chrome 90 on Mac OS.  (Also reproduceable in Firefox on MacOS and in Chrome on Windows 10).
Worth noting: I cannot reproduce the issue in Safari.
Also worth noting: it works about 10% of the time in Chrome, so there may be a race condition problem that is made worse when Zone.js is imported?!  Refresh the codepen a bunch to see if you can ever get it to work for you.
 
**What's your OS? (check https://whatsmyos.com):**
Mac OS Catalina

**API version (check your console)**
Seen in 4.19 and JavaScript 4.20-next [Date: 20210426, Revision: 49176826]

**Additional context**
1. Similar to: https://github.com/Esri/jsapi-resources/issues/268#issuecomment-831292333
2. I can't reproduce with a Simple-Marker symbol, but was able to reproduce with Vector Path symbols and Picture Marker symbols

**Comment by andygup** [comment]
@dougkpowers I do see the issue in the codepen, however I was not able to reproduce it when using your codepen code in our latest Angular sample using `@arcgis/core@4.19.3`: https://github.com/Esri/jsapi-resources/tree/master/esm-samples/jsapi-angular-cli.  

Can you try the following and let us know if it fixes the issue?
* Upgrade your Angular to 11.2.x: `ng update @angular/cli @angular/core`
* Change your ts.config > compilerOptions > target to `es2017`.  
* Update Zone.js to `0.11.4` - you'll need this update anyways when Angular 12 comes out in a few months.

cc @juliepowell

**Comment by dougkpowers** [comment]
@andygup Your suggestions did not work.

I created a brand new Angular 12 application, which comes with Zone.js 0.11.4 and targets es2017 by default.  I pasted in the contents of this codepen and I encountered the same bug.

Let me know if you'd like a zip of the test project I created.

**Comment by andygup** [comment]
@dougkpowers can you create a test github repo? Otherwise a zip file will work.

**Comment by dougkpowers** [comment]
@andygup  Here is a synopsis of what we've learned (github repo provided where applicable)

| ng version | es target | esri-api-flavor | works | notes | repo
| -----------|----------|---------------|-------|-------|-------------
| 10               |  2015      | dojo                  | no | version of zone.js has no impact  | N/A
| 10               |  2015     | es modules     | no | version of zone.js has no impact    | N/A 
| 10               |  2017     | dojo                 | no  | version of zone.js has no impact | N/A
| 10               |  2017     | es modules     | no   | version of zone.js has no impact | https://github.com/dougkpowers/esri-angular-| 10-test 
| 11               |  2017     | dojo                 | no    | version of zone.js has no impact | https://github.com/dougkpowers/esri-angular-11-dojo-test
| 11               |  2017     | es modules     | yes 🎉 | only working combination we've found | https://github.com/dougkpowers/esri-angular-11-test
| 12               |  2017     | dojo                 | no    | version of zone.js has no impact | N/A
|  12               |  2017     | es modules     | no |arcgis es modules are not  compatible with webpack 5 because of how babel is import  | https://github.com/dougkpowers/esri-angular-12-test

The good news is that we did find a working combination (ng11, targeting es 2017, using es-modules), but if we upgrade we'd like to go straight to 12.

Here is some extra detail on the webpack 5 issue.   You can reproduce it using the ng12 repo above, but it's not specific to ng 12 but to webpack 5.
```
./node_modules/@arcgis/core/widgets/support/chartUtils.js:1:0-177 - Error: Module not found: Error: Can't resolve './scratch/esri-sandbox-twelve/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator' in './scratch/esri-sandbox-twelve/node_modules/@arcgis/core/widgets/support'
Did you mean 'asyncToGenerator.js'?
BREAKING CHANGE: The request '/Users/doug/code/scratch/esri-sandbox-twelve/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

**Comment by andygup** [comment]
Hi @dougkpowers, thanks for the additional info.

> The good news is that we did find a working combination (ng11, targeting es 2017, using es-modules)

Yes, that is what I expected. We currently only test Angular 11 with an ES2017 TS target against JS API 4.19, here's the sample app: https://github.com/Esri/jsapi-resources/tree/master/esm-samples/jsapi-angular-cli

> You can reproduce it using the ng12 repo above, but it's not specific to ng 12 but to webpack 5.

The `asyncToGenerator` error is actually a bug in Angular 12.0.0 Webpack 5 config, it's not an issue with the ArcGIS JS API 4.19. We are tracking it here: https://github.com/Esri/jsapi-resources/issues/298. There is a PR with a fix, but we'll have to wait for an Angular 12 patch release to retest.

**Comment by dougkpowers** [comment]
For others who stumble across this, we found a way to add graphics from ng10 while targeting esri 4.19.  We call the function below just after adding graphics.

I don't recommend this for a production app, but this is at least allowing us to test the rest of the 4.19 API while we schedule out an upgrade to ng11.

```  
/**
   * There is a known issue has existing in the api since 4.18 that sometimes
   * prevents graphics from showing after they have been added to a layer.
   * The issue only manifests itself when using Zone.js and not targeting
   * es2017 (so it impacts NG 10 and older).
   *
   * This hacky fix seems to work.
   *
   * see: https://community.esri.com/t5/arcgis-api-for-javascript/graphics-in-a-graphics-layer-only-appear-on-zoom/td-p/1037515
   *  see: https://github.com/Esri/jsapi-resources/issues/268#issuecomment-781899119
   * @param layer The layer to fix after graphics have been added
   */
  static addGraphicsFixLayerHack(layer: esri.GraphicsLayer): void {
    // the layer may change before our timeout functions execute,
    // so let's make a shallow copy of the graphics first.
    const graphics = [...(layer.graphics as any).items];

    const backup = new Map<esri.Graphic, esri.Symbol>();
    setTimeout(() => {
      graphics.forEach(graphic => {
        backup.set(graphic, graphic.symbol);
        graphic.symbol = graphic.symbol.clone();
      });

      setTimeout(() => {
        graphics.forEach(graphic => {
          graphic.symbol = backup.get(graphic);
        });
      }, 200);

    }, 200);
  }
```
