### ISSUE TITLE
Bug: Text Labels Don't Render within Layer.  Are always on top of all other layers

### ISSUE THREAD

**Issue by dougkpowers** [Esri/feedback-js-api-next#123]
**Describe the bug**
A text label should only be viewable within its layer.  If another layer is on top of it, it should be possible to cover the text label with a graphic in the layer above it.

**To Reproduce**
1.  See a code pen which reproduces the issue here: https://codepen.io/dougrt/pen/eYvYOyR
2. It creates a client side feature layer with 1 feature over Nashville.  The feature is represented by a maroon square and a red label that reads "label"
3. The code pen then creates a graphic layer that is added on top of the feature layer.  An orange circle is placed at the same latitude and longitude as the feature in the feature layer. 

You'll notice that the orange circle is on top of the square (which is correct), but it does not cover the label

**Expected behavior**
The orange circle should cover the text in the layer behind it

**Browser (check https://whatismybrowser.com/)** 
Chrome on MacOS
 
**What's your OS? (check https://whatsmyos.com):**
MacOS Catalina

**API version (check your console)**
ArcGIS API for JavaScript 4.20-next [Date: 20210426, Revision: 49176826]
Also reproducable in 4.19

**Additional context**
The use of a feature Layer (rather than a graphics layer) in the code pen is inconsequential.  If the text is in a Graphics layer, the same issue appears

**Comment by bbarnell** [comment]
This is by design.  You could label using graphic text as a workaround.
