### ISSUE TITLE
General enhancement: Support custom highlight options for LayerViews

### ISSUE THREAD

**Issue by sebastianfrey** [Esri/feedback-js-api-next#125]
**Enhancement category**

How would you categorize the enhancement?  `LayerView`

**Enhancement short summary**

Support custom highlightOptions for `LayerView` subclasses.

**Enhancement description**

As described in the 4.x-API-Reference a developer can customize the highlighting appearance via the `highlightOptions` parameter for a [MapView](https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html#highlightOptions) and a [SceneView](https://developers.arcgis.com/javascript/latest/api-reference/esri-views-SceneView.html#highlightOptions).

Consider a user who wants to distinguish between the highlighted features of different layer views, than the current solution provided in 4.x for highlighting feature

 - does not scale very well.
 - is obviously not suitable for advanced usages.

For 4.x I could imagine the following functionality, when a developer wants to override the default highlighting options coming from `MapView` or `SceneView`:

```jsx
layerView.highlight(featuresToHighlight, >highlightOptions<)
```

Or something globally like this:

```jsx
layerView.highlightOptions = customHighlightOptions
```

I would like to emphasize at this point that this behaviour was **super easy** to implement for FeatureLayers with **3.x**:

```js
featureLayer.setSelectionSymbol(customSelectionSymbol)
```

And boom! Custom highlighting for this layer.

**Severity**

How important is this enhancement and why? High

In our 3.x client the `FeatureLayer#setSelectionSymbol` functionality is used in different scenarios by our users. We now want to move on to 4.x, but missing features like this, will prevent us from doing.

**Comment by ole1986** [comment]
fully agree to @sebastianfrey. Having only a single highlighting option for the SceneView/MapView in v4.x seem to be a downgrade of functionality compared to the setSelectionSymbol in v3.x

Since popup and editing uses the same highlightOptions improve the user experience (IMO)

**Comment by sebastianfrey** [comment]
Thanks for implementing this feature with the 4.26 release. :+1:
