### ISSUE TITLE
@arcgis/core: the local build doesn't work and continue requesting to internet connection.

### ISSUE THREAD

**Issue by boualikamel** [Esri/feedback-js-api-next#126]
I'm working with @arcgis/core, and react framwork i confgured my project to do builds locally.
once i tried it without internet connection so i noticed that in the network there are requests coming from internet. from arcgis cdn.

How to fix this issue ?

i've tried this ! 

```
import esriConfig from "@arcgis/core/config";
esriConfig.assetsPath = "./assets";

```

and  this because of the ts file from the package export (config)
```
import config from "@arcgis/core/config";
config.assetsPath = "./assets";
```

there is no error detected  and the application continue to get the requests from the arcgis cdn.

**note :** 

- i've copied the assets into public assets.
- and i removed cache from my browser.

Cordially

**Comment by odoe** [comment]
Do you have a demo app that shows this behavior? I just tested on a fresh app with copied local assets and I'm not seeing any network traffic from the CDN. Do you maybe have a reference to the CSS from the CDN?

Thanks!

**Comment by boualikamel** [comment]
Hello, i will create a demo and publish it, as soon as possible !

**Comment by andygup** [comment]
@boualikamel just touching base, have you been able to figure this out?

**Comment by boualikamel** [comment]
Hello,
Yes , it works after changing the implacement of esriConfig import, the error was including esriConfig import in primary file which doesn't contain @arcgis/core imports.

thank you for the response, and i close this issuue
