### ISSUE TITLE
Bug: Missing files

### ISSUE THREAD

**Issue by leevers** [Esri/feedback-js-api-next#128]
**Describe the bug**
The next releases ( >= 4.20.0-next.20210517 ) seem to be missing a couple of files when i try and do a dojo build, specifically:
error(303) Missing include module for layer. missing: esri/views/2d/engine/webgl/collisions/LayerViewSorter; layer: esri/views/2d/mapViewDeps
error(303) Missing include module for layer. missing: esri/views/2d/engine/webgl/mesh/factories/matcherUtils; layer: esri/views/2d/mapViewDeps

**Expected behavior**
I beleive these files are missing from the source

 
**What's your OS? (check https://whatsmyos.com):**
 - OS: "Windows 10* 64-bit"
 - Device: "Windows desktop PC"

**API version (check your console)**
4.20.0-next.20210514 -> 4.20.0-next.20210517

**Comment by odoe** [comment]
It looks like can update your build profile to remove those files as they are not in the 4.20 release.
We have not updated the resources sample to reflect the 4.20 updates yet.
https://github.com/Esri/jsapi-resources/blob/master/4.x/amd/dojo/build.profile.js#L105

**Comment by leevers** [comment]
Thanks Rene, that resolved the issue
