### ISSUE TITLE
Enhancement: Include DatePicker and TimePicker as an input in FeatureForm FieldElement

### ISSUE THREAD

**Issue by markoskifle** [Esri/feedback-js-api-next#132]
**Enhancement category**
Widgets 

**Enhancement short summary**
Include DatePicker and TimePicker as an input in FeatureForm FieldElement

**Enhancement description**
AttributeEditor in version 3.x supports date time picker. Many of our users are requesting this feature in 4.x

**Severity**
Medium 

**Screenshots**
none

**API version (check your console)**
 - Version: ArcGIS API for JavaScript 4.21.0-next.20210819

**Additional context**
If there is a work around please post

**Comment by hgonzago** [comment]
There is already an internal issue that we are tracking for this within our API repo. We hope to have this implemented in the near future.
