### ISSUE TITLE
Bug: Cannot read property 'wkid' of undefined in geometryEngine Union

### ISSUE THREAD

**Issue by salahED** [Esri/feedback-js-api-next#134]
Hello guys hope you are doing well.
While using arcgis/core version 4.20.1, I had a problem with the function _Union_ of **geometryEngine**, i tried to merge two segments with the same spatial reference but when i make a call to the function  `geometryEngine.union([seg1, seg2])` it shows the following error: 
![image](https://user-images.githubusercontent.com/23176098/132131575-5efa6706-323c-485e-a258-70b1e6e99e0d.png)

Please do you have any idea to fix it?

**Comment by odoe** [comment]
Can you please provide a reproducible sample of the issue. Also note, geometry engine does not autocast geometries, the need to be Geometry instances.

**Comment by salahED** [comment]
> Can you please provide a reproducible sample of the issue. Also note, geometry engine does not autocast geometries, the need to be Geometry instances.

i tried to create a new segment from a line onclick (**selectedSegments**), to add manually the spatial reference but i still have the same issue, this is a part of my code 
```
const seg1 = new Graphic({
          geometry: {
            type: "polyline", // autocasts as new Polyline()
            paths: selectedSegments[0].geometry.paths,
            spatialReference: 102100
          },
          attributes: selectedSegments[0].attributes
        });
        const seg2 = new Graphic({
          geometry: {
            type: "polyline", // autocasts as new Polyline()
            paths: selectedSegments[1].geometry.paths,
            spatialReference: 102100
          },
          attributes: selectedSegments[1].attributes
        });
        const union = geometryEngine.union([seg1, seg2]);
```

**Comment by odoe** [comment]
I see. You're passing the graphics to the `union` method. geometryEngine only takes geometries.
https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-geometryEngine.html#union

Try this.

```js
const union = geometryEngine.union([seg1.geometry, seg2.geometry]);
```

Here is a sample.
https://codepen.io/odoe/pen/oNwBagL?editors=1000

**Comment by steveoh** [comment]
this seems like a common mistake. can this issue turn into a request for a better error message

**Comment by odoe** [comment]
The doc is pretty clear that it takes geometries. We don't do instance checks anywhere else in the API. We can take it under consideration, but no promises.

**Comment by steveoh** [comment]
I don't think you have to do an instance check. If an expected property doesn't exist on the type you are using then you can assume the wrong type was provided right? Give a link to the docs in the error and suggest that the wrong type was used. Not everyone starts at the docs.

**Comment by salahED** [comment]
> I see. You're passing the graphics to the `union` method. geometryEngine only takes geometries.
> https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-geometryEngine.html#union
> 
> Try this.
> 
> ```js
> const union = geometryEngine.union([seg1.geometry, seg2.geometry]);
> ```
> 
> Here is a sample.
> https://codepen.io/odoe/pen/oNwBagL?editors=1000

Hello thank you for your answer, i fixed the probleme with geometry as you said now i got a new error `Cannot read properties of undefined (reading 'paths')`
