### ISSUE TITLE
Unable to handlet WMTSLayer with a varying TopLeftCorner for Level. 

### ISSUE THREAD

**Issue by xlhomme** [Esri/feedback-js-api-next#138]
Hello 
 I tryed WMTSLayer sample with this url : https://osm.geobretagne.fr/gwc01/service/wmts
 Unfortunetly this WMTS uses the EPSG:3948 spatial refence by default.  this GridSet has different value for the topLeftCorner for each level. 

This sample reproduc the issue : 
 ```
  const layer = new WMTSLayer({
          url: "https://osm.geobretagne.fr/gwc01/service/wmts",
          serviceMode: "KVP",
		  activeLayer: {   id: "osm:bing"  }
        });

        const map = new Map({
          layers: [layer]
        });
		
        const view = new MapView({
          container: "viewDiv",
          map: map,
		  zoom:10
        });

        view.when(() => {
          view.extent = layer.fullExtent;
          const layerList = new LayerList({
            view: view
          });
          view.ui.add(layerList, "bottom-left");
        });
      });
```
This bug report should be coorelated with the following enhancement 
  https://github.com/Esri/feedback-js-api-next/issues/137
   
best regards

**Comment by xlhomme** [comment]
Hello 
another sample with 2154
   var sly=new WMTSSubLayer();
		sly.id= "osm:bing";
		sly.tileMatrixSetId= "EPSG:2154";
        const layer = new WMTSLayer({
          url: "https://osm.geobretagne.fr/gwc01/service/wmts",
          serviceMode: "KVP",
		  activeLayer: sly
        });

        const map = new Map({
          layers: [layer]
        });

best regards

**Comment by ycabon** [comment]
Hi Xavier, thanks for the bug reports. We have fixes in progress for WMTS to honor the top left corner and tile matrix limits.

**Comment by xlhomme** [comment]
great thanks yann! 
We need to have an array or origin in TileInfo.

**Comment by ycabon** [comment]
The best is to go through support in general, thanks!

**Comment by mstefarov** [comment]
@xlhomme Hello!  I am a developer on ArcGIS Runtime team.  Unfortunately this is a known limitation &mdash; Runtime currently expects all TileMatrices within a TileMatrixSet to use the same TopLeftCorner coordinate.  Enhancing this behavior has been in our backlog for some time, but has not been prioritized yet &mdash; such services seemed rare and other GIS products (e.g. by QGIS, ArcGIS Online, or ArcGIS Pro) did not support them either.

I added a note on our internal issue tracker, but the best way to bump up the priority of this enhancement is to open a support issue with Esri.

**Comment by xlhomme** [comment]
Hello 
  OpenLayers implements multiple origins :    https://openlayers.org/en/latest/apidoc/module-ol_tilegrid_WMTS.html
  QGIS handle such use case wery well (tested with QGIS 3.22).
  ArcGIS Pro / ArcGIS Online -> same issue : dont handle this use case.
Best regards.

**Comment by xlhomme** [comment]
Great it works with arcgis js api 4.22 !
