### ISSUE TITLE
Enhancement: CSVLayer with XField and YField (projected coordinate system)

### ISSUE THREAD

**Issue by xizher** [Esri/feedback-js-api-next#139]
**Enhancement category**
How would you categorize the enhancement? Layers

**Enhancement short summary**
How use CSVLayer with the xy fields with projected coordinate system

**Enhancement description**
i found the CSVLayer properties have "longitudeField" and "latitudeField".
if the csv source hasn't longitude and latitude fields, bug has x and y fields which are from projected coordinate system. how can i make the csv on map?

**Severity**
How important is this enhancement and why? Medium

**Comment by ubatsukh** [comment]
This repo is specifically for collecting feedback related to the /next release of the JavaScript SDK. For general enhancements to the SDK, please reach out to [Esri support](https://support.esri.com/en/contact-tech-support) or post on [ArcGIS Ideas](https://community.esri.com/t5/arcgis-javascript-maps-sdk-ideas/idb-p/arcgis-api-for-javascript-ideas). Thank you!

With that said, we created an enhancement request for this in our internal issue tracking system. The enhancement will be announced in What's New when it becomes available.
