### ISSUE TITLE
README says next production release is in October 2019

### ISSUE THREAD

**Issue by tomwayson** [Esri/feedback-js-api-next#14]
>  until the production release in October 2019.

I assume `next` has moved on to 4.14, which is targeted for [some time that is unknown to Tom but very likely after October 2019]

**Comment by bsvensson** [comment]
>  assume next has moved on to 4.1

Not yet...

**Comment by bsvensson** [comment]
We're still working on the next `next` deployment...

**Comment by bsvensson** [comment]
README and CHANGELOG has been updated for 4.14.
