### ISSUE TITLE
How to get featureLayer response on every query

### ISSUE THREAD

**Issue by salahED** [Esri/feedback-js-api-next#142]
Hello everyone, please do you have any idea if there is any way about how to detect arcgis featureLayer query response in the front using arcgis js api 4.x, i want to use it to check at every moment if there is data my token is valid else it's not.
i will be very thankfull if u have any other idea to check if my token is steel valid while navigating the map.
i hope my question is clear.
thank you very much.

**Comment by dasa** [comment]
An `after` request interceptor may be what you need. See: https://developers.arcgis.com/javascript/latest/api-reference/esri-config.html#request
