### ISSUE TITLE
Enhancement: Allow to use lower scale metric units while using measurement widgets

### ISSUE THREAD

**Issue by nikator** [Esri/feedback-js-api-next#143]
**Enhancement category**
Widgets

**Enhancement short summary**
Allow to use millimeters and centimeters in DirectLineMeasurement3D and AreaMeasurement3D widgets.

**Enhancement description**
We have a requirement from a client to allow user to select millimeters and centimeters. When we try to set unit property to these units it throws: "Accessor#set 'millimeters' is not a valid value for this property, only the following values are valid: 'metric', 'imperial', 'inches', 'feet', 'yards', 'miles', 'nautical-miles', 'us-feet', 'meters', 'kilometers'".

I do not see a reason why these units cannot be used as they all are related to multiplier of 10.

**Severity**
Medium

**API version (check your console)**
 - Version: [ArcGIS API for JavaScript 4.22 [Date: 20211215, Revision: ad43611b]]]

**Comment by NoashX** [comment]
Hi @nikator, thanks for posting this here. We are considering an option to allow finer grained output from all the measurement widgets at a future release. Basically, we feel that adding decimal places to existing units (and making the possible available units more clear in the doc) would be more useful than adding small units of measurement. Will keep this issue updated as things progress.
