### ISSUE TITLE
General enhancement: Features should be rendered continuously at +/-180° longitude boundary on a 3D globe

### ISSUE THREAD

**Issue by ryodohemmi** [Esri/feedback-js-api-next#147]
**Enhancement category**
SceneView 

**Enhancement short summary**
Features are shown discontinuously at +/-180° longitude boundary on a 3D globe, which should be corrected.

**Enhancement description**
Feature layers crossing the +/- 180° longitude boundary should be displayed continuously on a 3D scene.  
Polygons and lines across +/- 180° (e.g.,  graticules with a spatial extent of -190 to +190°) are divided into two parts.  
Lines exactly at the boundary are hidden (see the screenshot).

**Severity**
Medium

**Screenshot**
![image](https://user-images.githubusercontent.com/50690084/153178297-1c87f4e3-c057-484b-a47b-150088b18ff4.png)

**API version**
 - ArcGIS API for JavaScript 4.22

**Additional context**
If I'm missing the existing functionality/option to correct this issue, please let me know.

**Comment by SaschaBrunnerCH** [comment]
There is already an internal issue that we are tracking for this within our API repo. We hope to have this implemented in the near future.
