### ISSUE TITLE
Enhancement: assets file are rendered many time 

### ISSUE THREAD

**Issue by boualikamel** [Esri/feedback-js-api-next#148]
**Enhancement category**
Other : Enhance Render Build (ESM Builds)

**Enhancement short summary**
Some assets file are rendered many time, 

**Enhancement description**
I had noticed in my enterprise project that the assets files are rendered multiple times, I checked my react code several times and noticed that commenting out the `map.addMany(featurelayers)` code solved the problem and when i add a feature layer to the map, more duplicate files are rendered in the network, i don't know if this is a problem or not, but when i checked the example in the [[jsapi-resources](https://github.com/Esri/jsapi-resources)/[esm-samples](https://github.com/Esri/jsapi-resources/tree/master/esm-samples)/jsapi-create-react-app/ ](https://github.com/Esri/jsapi-resources/tree/master/esm-samples/jsapi-create-react-app)
i had the same issue, i publish that to have some explanation if it's possible, I thank the team for the excellent work with the arcgis js api.

**Severity**
Medium

**Screenshots**
![image](https://user-images.githubusercontent.com/37594056/154023970-7565712c-68c6-48a6-84eb-61bbc7a35c5a.png)

**API version**
 - ArcGIS API for JavaScript 4.22  **@arcgis/core**

**Comment by andygup** [comment]
Hi @boualikamel did you try disabling the `Disable cache` checkbox? When that's unchecked you should start to see cache notifications show up in the `Size` column. 

![image](https://user-images.githubusercontent.com/510440/154101098-0a4d85c5-69f6-485d-8a99-8e88eed2c56d.png)

**Comment by boualikamel** [comment]
hello @andygup yes yes i know that cache-control should be configured in the frontal server, I was just wondering if it's normal to render files that are the same.

**Comment by odoe** [comment]
@boualikamel those are files being loaded in the workers, so it is expected. The number of workers will vary based on machine and browser.

**Comment by andygup** [comment]
I'm closing this out, the API is working as designed. If something else comes up let us know.
