### ISSUE TITLE
Bug: BasemapGallery widget highlights WMTS basemaps with same URL but different layers

### ISSUE THREAD

**Issue by xlhomme** [Esri/feedback-js-api-next#150]
Hello 

In the following example, I had 2 basemaps coming from the same WMTS url. 
In the basemap layer list widget , when you select a basemap , the widget  highlight all basemap coming from the same url 
![image](https://user-images.githubusercontent.com/3986660/156032386-17abeb42-c495-44d3-9989-b25bbdfdd9e7.png)

moreover it call twice the getcapabilities.... 

best regards

**Comment by ubatsukh** [comment]
@xlhomme, thank you for reporting this issue. We fixed this issue at version 4.23 which will be released on 3/23/22.
