### ISSUE TITLE
BUG-000147618: WMS GetMap requests are sent as POST with invalid encoded body

### ISSUE THREAD

**Issue by sebastianfrey** [Esri/feedback-js-api-next#152]
**Describe the bug**
WMS GetMap requests are sent as POST with invalid encoded body, when a GetMap requests URL exceeds the configured `maxUrlLength` of [@arcgis/core/config](https://developers.arcgis.com/javascript/latest/api-reference/esri-config.html#request).

The WMS spec clearly states here: `"When POST is used, the request message is formulated as
an XML document."`

**To Reproduce**
1. Go to https://sebastianfrey.github.io/wms-getmap-post-issue/
2. GetMap is sent as POST with invalid encoded body, which causes a HTTP 400 error.

**Expected behavior**

Either do format GetMap requests as XML when sent as POST or even better do **always** send GetMap requests as GET, regardless of whether the maxUrlLength is exceeded or not.

**Note:** IMO the priority of this bug should be very high.

**API version (check your console)**
 - ArcGIS API for JavaScript 4.23-next [Date: 20220304, Revision: 559f8392]

**Comment by annelfitz** [comment]
Hi @sebastianfrey - thanks for reporting this. We have a couple questions:
1. Are your WMS url requests exceeding the default url length of 2,000 characters? And why don't you just permanently increase the limit?
2. Does he have a JSAPI 3.x app that you can share that is working?

Thanks!

**Comment by sebastianfrey** [comment]
Hi @annelfitz - thanks for reaching out.

1. Yes. We have a client, which has a WMS service hosted, which exceeds pretty easy the 2,000 characters (it has a lot of layers). Unfortunately the WMS service is not available for public use. Therefore I have restricted in the App the max url length to 400 for demo purpose.

You're right, we may increase in our application the default url length for example to 4,000, but IMO this is just a temporary workaround, which will not scale well. Imagine the next client has a WMS service, which will then exceed the url length of 4,000 characters, so we would have to increase it further. In addition, increasing the default url length, could cause issues when interacting with ArcGIS-Servers, which have a lower max url length for GET requests configured, than we have in our application.

2. Currently I have no JSAPI 3.x app available, but in our legacy application, which is built around 3.x, our clients WMS service works just fine.

**Comment by sebastianfrey** [comment]
What do you mean with server? WMS Server or ArcGIS Server?

The WMS Servers our customers use are either version 1.1.1 or 1.3.0. In that special case, the WMS Server is powered by a QGIS server.

The used ArcGIS server versions are most of the time >=10.7.1, but it depends from customer to customer.

**Comment by annelfitz** [comment]
Hi @sebastianfrey - sorry for the delay in getting back to you.

> **Expected behavior**
> Either do format GetMap requests as XML when sent as POST or even better do always send GetMap requests as GET, regardless of whether the maxUrlLength is exceeded or not.

The WMS spec never standardized XML encoding for the post body, so we cannot support GetMap requests as XML when sent as POST since the XML could be different for each server. Regarding always sending GetMap requests as GET, we decided against that as well, since we do not want to break existing layers where the server responds correctly. 

With that being said, we do have a workaround for you - this request interceptor will always make a GET request: 
```js
    esriConfig.request.interceptors.push({
      urls: "https://host/path", 
      async before(params) {
        if (params.requestOptions.responseType === "image") {
          const url = new URL(params.url);
          url.search = new URLSearchParams([
            ...Array.from(url.searchParams.entries()),
            ...Object.entries(params.requestOptions.query || {})
          ]).toString();
          const img = new Image()
          img.crossOrigin = "anonymous";
          img.src = url.href;
          await img.decode()
          return img;
        }
      }
    });
```
Hope this helps!

**Comment by sebastianfrey** [comment]
Hi @annelfitz,

Thanks for reaching out with that handy solution. I must admit, those interceptors are pretty nice. I am just curious which WMS layer vendors do support GetMap via POST with URL encoded form data. Do you have any samples?

In order to get your workaround to run, I had to remove the following query parameters before setting the search params.

```js
const searchParams = new URLSearchParams([
  ...(Array.from(url.searchParams.entries()) as any),
  ...Object.entries(params.requestOptions.query || {}),
]);
searchParams.delete('time');
searchParams.delete('_ts');
url.search = searchParams.toString();
```

The reason for that was, that some of my test WMS layers are a bit picky about what query parameters are sent.
