### ISSUE TITLE
WMTS with different tileInfo does not work

### ISSUE THREAD

**Issue by TomGeograf** [Esri/feedback-js-api-next#153]
**Describe the bug**
If TileLayer (always with different tileInfo) is used as a basemap layer, then WMTS layer does not work in MapView.
If WMTS layer with same tileInfo is set as a basemap, then additional WMTS in MapView (as a layer) works!

**To Reproduce**
Just try html code in zip
Uncomment lines 25 - 31 and comment lines 32 - 34 to try WMTS as a basemap (WMTS as a layer works.)

[wmts.zip](https://github.com/Esri/feedback-js-api-next/files/8282311/wmts.zip)

**Expected behavior**
MapView or SceneView should show both layers with different tileInfo.

**Browser ** 
 - Browser: ["Edge 99 on Windows 10"]
 
**OS**
 - OS: ["Windows 10* 64-bit"]
 - Device: ["Windows desktop PC"]

**API version**`
 JavaScript 4.23-next [Date: 20220316, Revision: aec2b4ea]

**Comment by ycabon** [comment]
@TomGeograf I guess you spotted already. We fixed the issue :)
