### ISSUE TITLE
Bug: BasemapGallery activeBasemap property

### ISSUE THREAD

**Issue by suzannabentley** [Esri/feedback-js-api-next#155]
**Describe the bug**
If a value is provided for "activeBasemap" when creating a BasemapGallery, an error is throw.
If activeBasemap is set after BasemapGallery is initialized, it works properly. 

Full Error Message:
![image](https://user-images.githubusercontent.com/101646938/159040658-2d110440-3a74-49ca-984c-4764ef65d184.png)

**To Reproduce**
1. Go to https://codepen.io/suzanna-bentley/pen/JjMXYBZ 
2. On load, no basemap or UI trays are rendered. An error is printed to the browser's console log. It is not visible in the codepen console. 

**Expected behavior**
A MapView with specified activeBasemap is rendered, along with other UI components. 

**Browser (check https://whatismybrowser.com/)** 
 - Browser: Firefox 98.0.1 and Chrome 99.0.4844.74 
 
**What's your OS? (check https://whatsmyos.com):**
 - OS: Windows 10 Education* 64-bit"]

 - Device: Windows Desktop
 
**API version (check your console)**
 - ArcGIS API for JavaScript 4.23-next [Date: 20220317, Revision: ff772db3]

**Comment by ubatsukh** [comment]
@suzannabentley thank you so much for reporting this issue. We will get it fixed and will update you once the fix is installed.

**Comment by ubatsukh** [comment]
@suzannabentley, this issue is now fixed. You can check the fix when the `next` version is updated. I am hoping it will be updated sometime later today (3/21/22). 

Thank you for reporting this issue.
