### ISSUE TITLE
@arcgis/core: Unhandled error with the new Editor widget

### ISSUE THREAD

**Issue by omaraisa** [Esri/feedback-js-api-next#159]
**Bug Description**
I keep receiving an error when I try to edit features using the editor widget. precisely when I finish creating a new feature or when I start updating a feature. The error message says:
*****************************************************************************************************
Unhandled Runtime Error
TypeError: Cannot read properties of null (reading 'match')

Call Stack
new y
node_modules\@arcgis\core\core\urlUtils.js (5:757)
j
node_modules\@arcgis\core\core\urlUtils.js (5:1473)
d
node_modules\@arcgis\core\layers\support\arcgisLayerUrl.js (5:759)
Function.createLoadedLayerContingentValuesCache
node_modules\@arcgis\core\layers\support\LayerContingentValuesCache.js (5:1083)
*****************************************************************************************************
I believe it is a bug with the new 4.23 release because when I almost lost hope of fixing it I tried downgrading arcgis/core to 4.22 and the error vanished without changing a single line of code. I upgraded again and I was able to copy the error message. Can you please consider this issue because I'm missing the great features that version 4.23 brings to the editor widget.

**Framework and build tools** 
 - React & NextJs

**To Reproduce**
* Create a simple GeoApp with React/NextJS.
* Add the Editor widget
* Try editing feature layers created from graphics not fetched from a URL.

**Screenshot**
![editor widget_arcgis core error](https://user-images.githubusercontent.com/90543562/169365506-4fa66180-d5e2-493c-9246-d2e7ff7f2602.png)

**Browser** 
 - Google Chrome Version 101.0.4951.54 (Official Build) (64-bit)
 
**OS**
 - Windows 10* 64-bit

**API version**
 - Version: 4.23

**Comment by odoe** [comment]
Looks like this is fixed in the `next` build.
https://codepen.io/odoe/pen/RwQVXjE?editors=1000

**Comment by omaraisa** [comment]
Thanks, @odoe for the quick response. However, I couldn't reproduce the error with CDN. I'm facing this error because my app relies on @arcgis/core ESM.

**Comment by odoe** [comment]
`npm install @arcgis/core@next` to get the latest next build and the fix.

The CDN and NPM package are nearly identical in functionality, it is rare to find a bug in one and not the other.

**Comment by omaraisa** [comment]
It works!
Thanks a lot
