### ISSUE TITLE
Bug: Graphics drawn across the central meridian don't respond to click events on east side.

### ISSUE THREAD

**Issue by denholtz** [Esri/feedback-js-api-next#16]
**Describe the bug**
For both polygon and polyline graphics drawn across the 180th meridian, click events on the portion of the graphic east of the 180th meridian don't register.

**To Reproduce**
Visible in https://codepen.io/ralucanicola/pen/vYYRVPL (special thanks to Raluca for providing the pen and responding to my questions in the forums).

**Browser (check https://whatismybrowser.com/)** 
Chrome 77
 
**What's your OS? (check https://whatsmyos.com):**
Windows 10

**API version (check your console)**
JavaScript 4.14-next [Date: 20191104, Revision: 8cbf0b19]

**Comment by RalucaNicola** [comment]
thanks for reporting this Michael! I opened up an issue in the API. Will let you know when this gets fixed.

**Comment by RalucaNicola** [comment]
@denholtz bug should be fixed now, let me know if it works for you as well. If it does, then please close the issue.

**Comment by bsvensson** [comment]
This seems to work fine in 4.14 now.
