### ISSUE TITLE
Bug: Setting SceneView.container to ' ' with drawn area in AreaMeasurement

### ISSUE THREAD

**Issue by BEJIEC** [Esri/feedback-js-api-next#162]
When set container prop of SceneView to ' ' with drawn and computed area in AreaMeasurement widget, it causes crash of view (maybe trying to update labels). Same actions with MapView don't
![image](https://user-images.githubusercontent.com/35963217/172114227-66b8f3a5-4700-4360-9508-2d4591dd5c58.png)
ArcGIS JS API 4.23 (previos didn't test)

**Comment by BEJIEC** [comment]
@gsoosalu. With next version, Scene/MapView cannot even inits with same props as with 4.23:(
We're not planning to update core yet, so no time to test it.
Props to the view:
![image](https://user-images.githubusercontent.com/35963217/172554060-53c455d5-aa3c-4ca5-a262-ab74727415ce.png)
Map object is the same, as in 4.23 (@arcgis/core/Map). It is not related to this issue, so i close it.
Thanks for reply!

**Comment by BEJIEC** [comment]
https://github.com/Esri/feedback-js-api-next/issues/162#issuecomment-1149548220
It is caused by disabled WebGL for testing. Chrome's --disable-webgl finally worked, sorry)

**Comment by gsoosalu** [comment]
Btw meanwhile we found and fixed another issue: after setting the container to "", when reassigning the SceneView.container, the area measurement didn't show up. But now you can toggle SceneView.container and the measurement is still there: 
![toggle-view-container](https://user-images.githubusercontent.com/85623288/173067712-72b45bd6-0674-4e0b-9df6-2148c7dc92d9.gif)

**Comment by BEJIEC** [comment]
> Btw meanwhile we found and fixed another issue: after setting the container to "", when reassigning the SceneView.container, the area measurement didn't show up. But now you can toggle SceneView.container and the measurement is still there: 
> 
> ![toggle-view-container](https://user-images.githubusercontent.com/85623288/173067712-72b45bd6-0674-4e0b-9df6-2148c7dc92d9.gif)
> 
> 
> 
> 

Great! We're waiting for 24)
