### ISSUE TITLE
Bug: view events typing issues

### ISSUE THREAD

**Issue by stacy-rendall** [Esri/feedback-js-api-next#163]
**Describe the bug**
It appears that types for `view.on()` events are broken in **4.24.0-next.20220614**. In VS Code I'm getting the following error:
```
No overload matches this call.
    Argument of type '"immediate-click"' is not assignable to parameter of type '"blur"'
```

As there is no documentation that I am aware of for **next** I'm not sure if the API has changed or there is a bug

**To Reproduce**
1. `view.on("immediate-click" ...`
2. `view.on("pointer-move" ...`

Note: using `// @ts-ignore` the code runs fine, so I suspect it is some kind of typing bug

**Expected behavior**
Not to get type errors for what appears to be correct code.

**Comment by andygup** [comment]
@stacy-rendall thanks for bringing this to our attention. There does seem to be some differences in the typings for `on()` between 4.23 and 4.24. Can you provide us with a simple github repo so that we can repro, or a fully working code snippet? It would be good to understand your use case with code.

**Comment by stacy-rendall** [comment]
Thanks for your reply Andy

Unfortunately I'm swamped at the moment so haven't been able to make an MWE or anything - in my opinion we are not doing anything especially funky, just ES Modules!

If I get time I'll try to whip something up for you next week

Cheers,
Stacy

Stacy Rendall (he/him) PhD, BE(Hons), MEngNZ
Principal Developer & Research Specialist, Abley
***@***.***  +64 3 371 0033<tel:+64%203%20371%200033> | +64 27 9000918<tel:+64%2027%209000918>
***@***.***  abley.com<http://www.abley.com>

**Comment by andygup** [comment]
Hi @stacy-rendall I'm going to close this out. If you are still experiencing this issue please provide a reproducible code example and we'll take another look at it.
