### ISSUE TITLE
Enhancement: Cache OGC API - Features lookup requests when creating OGCFeatureLayers

### ISSUE THREAD

**Issue by sebastianfrey** [Esri/feedback-js-api-next#166]
**Enhancement category**
*OGCFeatureLayer*

**Enhancement short summary**

When an OGCFeatureLayer is loaded, multiple lookup requests are made:

1. `Landing page`
2. `Conformance declaration`
3. `Feature collections`
4. `OpenAPI definition`
5. `Features` (fetches first 5 features to determine fields automatically)

After that the data of the specified collection is fetched. So far so good.

But when multiple OGCFeatureLayers of the same service instance are loaded, the lookup requests from 1. to 4. are redundant and can be omitted.

**Enhancement description**

Cache lookup requests for `Landing Page`, `Conformance Page`, `Feature collections` and `OpenAPI definition` for OGCFeatureLayers, which do belong to the same service instance.

**Severity**

*Low*

**Additional context**

In our case we have a client which has configured its application to load 20+ OGCFeatureLayers on page startup, those redundant lookup requests cause a massive overhead and harm the applications start up time noticeable.

For now we have a workaround, which leverages a request interceptor, but IMO this is something which should not be handled in user land but rather by the JSAPI.

```ts
// promise helper
export function createDeferrablePromise() {
  let resolve;
  let reject;
  const promise = new Promise((_resolve, _reject) => {
    resolve = _resolve;
    reject = _reject;
  }) ;

  promise.resolve = resolve;
  promise.reject = reject;

  return promise;
}

// ogc cache
const cache = new Map();

// ogc service url
const serviceUrl = 'http://host:port/path/to/ogc/service';

// helper to determine if an api call is cachable
function isCachable(url) {
    const [lastPathSegment] = url.split('/').reverse();
    return (
      url === serviceUrl ||
      !!['conformance', 'collections', 'api'].find((part) => lastPathSegment.includes(part))
    );
}

// interceptor
esriConfig.request.interceptors.push({
  async before(params) {
    if (params.url?.startsWith(serviceUrl)) {
      if (ogcCache.has(params.url)) {
        return await ogcCache.get(params.url);
      }

      if (isCachable(params.url)) {
        ogcCache.set(params.url, createDeferrablePromise());
      }
    }
  },

  async after(params) {
    if (params.url?.startsWith(serviceUrl) {
      if (isCachable(params.url)) {
        const promise = ogcCache.get(params.url);
        if (promise) {
          promise?.resolve(params.data);
        }
      }
    }
  },
```

**Comment by annelfitz** [comment]
Hi @sebastianfrey - thanks for reporting this. We do provide caching for individual layers, but for multiple layers, we believe that your current workaround should suffice so we will not be making any changes to our API at this time.

An alternative solution that might be worth looking into is the cache API (https://developer.mozilla.org/en-US/docs/Web/API/Cache), but your current workaround should be good enough for now. Thanks again!
