### ISSUE TITLE
@arcgis/core: `Accessor` decorators do not work at runtime when transpiled with Babel

### ISSUE THREAD

**Issue by sebastianfrey** [Esri/feedback-js-api-next#169]
**Describe the bug**
`Accessor` decorators on custom classes do not work at runtime, when Babel is used for transpiling. When TypeScript is used for transpiling, everything works as expected.

**Framework and build tools** 
 - Babel v7.18.9
 - Webpack v5.52.1

The following Babel config is used:

```json
{
  "presets": [
    "@babel/preset-env",
    "@babel/typescript"
  ],
  "plugins": [
    "@babel/proposal-object-rest-spread",
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/proposal-class-properties", { "loose": true }],
    ["@babel/plugin-proposal-private-methods", { "loose": true }],
    ["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
  ]
}
```

**To Reproduce**
The follwoing sample class, works at runtime fine when transpiled with TypeScript, but does not work when transpiled with Babel:

```ts
@subclass('app.CustomGroupLayer')
class CustomGroupLayer extends GroupLayer {
  @aliasOf('layers')
  sublayers!: Collection<Layer>;
}
```

The issue occurs, when some caller tries to access the alias `sublayers`.

For example

```ts
groupLayer.sublayers.add(featureLayer);
```

leads to the following error

```
Uncaught TypeError: Cannot read properties of undefined (reading 'add')
```

I have created a small app using `@arcgis/cli`, which reproduces the issue leveraging the above sample class. You can find the source code [here](https://github.com/sebastianfrey/jsapi-decorators-with-babel). The linked repository consists of two branches: `main` and `babel`. The `main` branch contains the ***working*** TypeScript version and the `babel` branch contains the ***not working*** Babel version.

**Expected behavior**
Source code transpiled with babel, which uses `Accessor` decorators on custom classes, should work at runtime as expected.

**Screenshots**

**Additional context**
Recently we started migrating all of our internal JS libraries and applications into a single mono repository. Since some of the migrated JS libraries define custom `Accessor` classes as describe above, this issue prevents us to complete the migration. The reason for that is, that some of the applications use Babel for transpiling (React based applications).

**Comment by andygup** [comment]
Hi @sebastianfrey this seems to be a configuration issue with babel as it relates to TypeScript.

Here are a few suggestions to try:
- In addition to using `babel-loader`, add  `ts-loader` back into your `webpack.config.js`. Order does matter, so have `ts-loader` run first to process the decorators. The JS API decorators won't work in .js so you need at least one pass of the TypeScript compiler.

```
    // Module handling and loaders.
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          use: [
            {
              loader: 'babel-loader',
              options: {
                exclude: /node_modules/,
              }
            },
            {
              loader: 'ts-loader',
              options: {
                transpileOnly: true
              }
            }
```

- Set the `tsconfig.json` `target` to `2022` to limit the amount of TS transpiling
- Try removing the `@babel/plugin-proposal-decorators` plugin from `.babelrc`

Also a gentle reminder: for similar issues in the future that aren't related to "new" issues in `next`, we request that you use either the [Esri community](https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript) site or the [jsapi-resources](https://github.com/Esri/jsapi-resources/issues) repo if it's related to one of the ESM samples.

**Comment by sebastianfrey** [comment]
Hi @andygup, thanks for your support on that. I am aware that with ts-loader in the transpile chain it works as expected.

As I understand your statement 

> The JS API decorators won't work in .js so you need at least one pass of the TypeScript compiler.

correctly, this means that Aaccessor decorators cannot be transpiled with Babel, but only with TypeScript. Is that correct?

**Comment by andygup** [comment]
That's our suggested approach to guarantee the order in which TS/JS transpiling takes place. Since the babel experimentalDecorators option wasn't working working, and the order in which TS/JS transpiling might be taking place seemed backwards, we aren't really sure. You would need to ask the babel team for more information on how the underpinnings work (or don't work). 

There are also other caveats mentioned in babel's documentation: https://babeljs.io/docs/en/babel-plugin-transform-typescript#typescript-compiler-options => `--experimentalDecorators` This option enables support for the "legacy" decorator proposal. You can enable it in Babel using the @babel/plugin-proposal-decorators plugin, **but please be aware, there are some minor differences.**  

Those differences weren't documented - perhaps they are significant enough in this case to break things.

**Comment by sebastianfrey** [comment]
Ok, that makes sense. Thanks again for your efforts on this.

One last thing, before I close this issue:

I would love to see a small note added to the [Implementing Accessor](https://developers.arcgis.com/javascript/latest/implementing-accessor/) guide, that compiling `@arcgis/core` with Babel does not work and is not officially supported. A lot of projects out there use Babel to transpile their TypeScript, so this might save someones time in the future.
