### ISSUE TITLE
Enhancement: IdentifyParameters.layerDefinitions is undocumented

### ISSUE THREAD

**Issue by roemhildtg** [Esri/feedback-js-api-next#17]
**Enhancement category**
How would you categorize the enhancement? Layers 

**Enhancement short summary**

Currently, layerDefinitions is undocumented. In previous versions of the api, layerDefinitions was a simple array that looked like this:

```
idParams.layerDefinitions = [];
idParams.layerDefinitions[100] = 'Status = \'Open\'';
//etc 
```

![image](https://user-images.githubusercontent.com/5471079/69059893-09cb6080-09dc-11ea-8880-49f87d9e850d.png)

This appears to be broken in 4.13.1 and I was wondering what the appropriate fix is. 

In 4.13 - an error is thrown in the Identify operation about an object not having a valid `id`. Is there a new structure for layerDefinitions that was not mentioned in the release notes?

**API version (check your console)**
 - Version: 4.13.2

**Additional context**
Add any other context about the enhancement or suggestion here.

Edit: not breaking change.

**Comment by odoe** [comment]
This is currently undocumented, so not really a breaking change, but if you need it right now, you can do it by defining objects for the layerDefinitions instead of using a sparse array.

```js
layerDefinitions = [ { id: 2, definitionExpression: "POP1999 > 75000" } ];
```

This will change in the future, but no timeframe on that.

**Comment by roemhildtg** [comment]
Okay thanks!

**Comment by roemhildtg** [comment]
I guess it wasn't documented/breaking change. I think I pulled the logic from a previous 3.x script and it worked in 4.x until 4.13.

**Comment by juliepowell** [comment]
Closing; workaround noted above.
