### ISSUE TITLE
Daylight Widget Dark Mode

### ISSUE THREAD

**Issue by leevers** [Esri/feedback-js-api-next#177]
### IMPORTANT

- [x] My question is related to a new issue in the latest next release. For all other issues, open a ticket with [Esri Technical Support](https://support.esri.com/) or post your question in the [community forum](https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript).
- [X] I have [checked for existing issues](https://github.com/Esri/jsapi-resources/issues) to avoid duplicates. If someone has already opened an issue for what you are experiencing, please add a 👍 reaction and comment as necessary to the existing issue instead of creating a new one.

### Actual behavior

When using the daylight widget in dark mode (css) the drop down for the time zone selection is illegible 

### Expected behavior

The shadow widget has a much clearer drop down, some consistency between the two drop downs and more readable color/font combination

### Reproduction sample

https://codepen.io/leevers/pen/LYdZLQb

### Reproduction steps

1. Select the timezone dropdown

### Reproduction browser

Chrome 105 on Windows 10

### API version (check your console)

Using ArcGIS API for JavaScript 4.25-next [Date: 20220906, Revision: 06b756b3]
Using ArcGIS API for JavaScript 4.24 [Date: 20220706, Revision: 7fd01dbc]

### Operating System (check https://whatsmyos.com)

Windows 10 64bit

**Comment by gsoosalu** [comment]
Thanks, @leevers for reporting this. We're looking into fixing it.

**Comment by leevers** [comment]
Thanks, will this appear in a next build shortly?
