### ISSUE TITLE
Bug: Underline Decoration not working for TextSymbol

### ISSUE THREAD

**Issue by rangasatishkumar** [Esri/feedback-js-api-next#18]
**Describe the bug**
Underline Decoration not working for TextSymbol's font

**To Reproduce**
1. Refer to pencode at https://codepen.io/rangasatishkumar/pen/KKKYmGy

**Browser** 
 - Browser: Chrome 78.0
 
**What's your OS?:**
 - OS: Windows 10 64-bit
 - Device: Windows desktop PC

**API version (check your console)**
 - Version: from ArcGIS API for JavaScript 4.11 to ArcGIS API for JavaScript next

**Additional context**
It worked with ArcGIS API for JavaScript 4.9 and 4.10

**Comment by NoashX** [comment]
Thank you for logging this bug @rangasatishkumar. This is a known issue that we are currently investigating. We will update this thread when we get it fixed.

**Comment by mmgeorge** [comment]
@rangasatishkumar likely this won't make it in 4.14, but we will try to get it in for 4.15

**Comment by rangasatishkumar** [comment]
@mmgeorge noted, thank you.

**Comment by bsvensson** [comment]
Thank you for submitting this enhancement. We have added it to our internal tracking system for consideration in an upcoming release.
