### ISSUE TITLE
MediaLayer hitTest to return the source ImageElements pixel dimension if applicable?

### ISSUE THREAD

**Issue by LukeCalladineIHS** [Esri/feedback-js-api-next#185]
### IMPORTANT

- [X] My question is related to a new issue in the latest next release. For all other issues, open a ticket with [Esri Technical Support](https://support.esri.com/) or post your question in the [community forum](https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript).
- [X] I have [checked for existing issues](https://github.com/Esri/jsapi-resources/issues) to avoid duplicates. If someone has already opened an issue for what you are experiencing, please add a 👍 reaction and comment as necessary to the existing issue instead of creating a new one.

### Actual behavior

When you click on a MediaLayer via a hitTest, it returns the MediaLayer element.

### Expected behavior

When you click on a MediaLayer via a hitTest, it returns the MediaLayer element along with X and Y values corresponding to the source ImageElement's pixel dimensions if applicable.

### Reproduction sample

//

### Reproduction steps

1. Click on any MediaLayer via a hitTest.

### Reproduction browser

Brave v1.44.112 ~ Chromium: 106.0.5249.119.

### API version (check your console)

4.25.0-next.20221011.

### Operating System (check https://whatsmyos.com)

OS: Windows 10* 64-bit.
Device: Dell Precision 7540.

**Comment by sagewall** [comment]
@LukeCalladineIHS this seems like a valid enhancement request.  For now, if you are using `ControlPointGeoreference` hopefully the `toSource` method can be used as a workaround. Thanks for submitting the issue.
```js
view.on("click", async (event) => {
  const hitTestResult = await view.hitTest(event);
  const mapPoint = hitTestResult.results[0].mapPoint;
  const sourcePoint = controlPointsGeoreference.toSource(mapPoint);
  console.log("mapPoint:", mapPoint, "sourcePoint", sourcePoint);
});
```

**Comment by sagewall** [comment]
Hi @LukeCalladineIHS, an enhancement has been created internally, so I'm closing this issue. If you would like to track this enhancement, please open a [Support Services](https://support.esri.com/en/contact-tech-support) ticket to create a new enhancement linked to our current internal issue. Thanks again!
