### ISSUE TITLE
Enhancement - Labeling feature in Sketch widget 

### ISSUE THREAD

**Issue by Abexdatl** [Esri/feedback-js-api-next#189]
Will there ever be a labeling feature in sketch widget ?

 In the utilities domain , it is one of the most sought after feature within sketch widget .

**Comment by sebastianfrey** [comment]
+1

**Comment by GilbertNg273** [comment]
> Will there ever be a labeling feature in sketch widget ?
> 
> In the utilities domain , it is one of the most sought after feature within sketch widget .

We are also in the utilties domain, and would like to have labeling added to the Sketch widget.
