### ISSUE TITLE
Bug: event.stopPropagation() on "immediate-click" prevents "double-click"

### ISSUE THREAD

**Issue by daniel6691** [Esri/feedback-js-api-next#19]
**Describe the bug**
Contrary to the 4.13-Version, when calling "stopPropagation" on the "immediate-click"-Event the "double-click" event is not fired.

**To Reproduce**
Go to: 
4.13: 
https://codepen.io/daniel6691/full/BayBNYM
DoubleClick in Map
double-click was executed (see in white box and zoom-in)

next: 
https://codepen.io/daniel6691/full/ExaYjwN
DoubleClick in Map
double-click was not executed (see in white box and no zoom-in)

`
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="initial-scale=1,maximum-scale=1,user-scalable=no"
    />
    <title>Intro to MapView - Create a 2D map - next</title>
    <style>
      html,
      body,
      #viewDiv {
        padding: 0;
        margin: 0;
        height: 100%;
        width: 100%;
      }
      #output{
        background-color: white;
        height: 300px;
        overflow: auto;
        position: absolute;
        right: 5px;
        top: 5px;
        width: 500px;
      }
    </style>

    <link
      rel="stylesheet"
      href="https://js.arcgis.com/next/esri/themes/light/main.css"
    />
    <script src="https://js.arcgis.com/next/"></script>

    <script>
      require(["esri/Map", "esri/views/MapView"], function(Map, MapView) {
        var map = new Map({
          basemap: "streets"
        });

        var view = new MapView({
          container: "viewDiv",
          map: map,
          zoom: 4,
          center: [15, 65] // longitude, latitude
        });

        var events = [
          "double-click",
          "immediate-click",
          "pointer-down",
          "pointer-up"
        ];
        for (var i = 0, iLen = events.length; i < iLen; i++) {
          view.on(events[i], function(argEvent) {
            if( argEvent.type === "immediate-click" ){
              argEvent.stopPropagation();
            }
            document.getElementById("output").innerHTML = new Date().getTime() + ": " + argEvent.type + "<br>" + document.getElementById("output").innerHTML;
          });
        }
      });
    </script>
  </head>

  <body>
    <div id="viewDiv"></div>
    <div id="output"></div>
  </body>
</html>`

**Expected behavior**
"double-click" event should be fired like in Version 4.13 -> zoom-in should work

**Screenshots**
![doubleClick4 13](https://user-images.githubusercontent.com/16337692/69869029-f194f480-12ab-11ea-9f4a-18c7785f154b.PNG)
![doubleClickNext](https://user-images.githubusercontent.com/16337692/69869049-fe194d00-12ab-11ea-9b38-6b7be53d97d6.PNG)

**Browser (check https://whatismybrowser.com/)** 
 - Browser: Google Chrome 79.0.3945.56, Firefox 71.0
 
**What's your OS? (check https://whatsmyos.com):**
 - OS: Windows 10* 64-bit
 - Device: Windows desktop PC

**API version (check your console)**
 - Version:  ArcGIS API for JavaScript 4.14-next [Date: 20191127, Revision: 98683a14]

**Comment by ubatsukh** [comment]
Hi there, 

It is by design at 4.14 and it is a breaking change. 

When the propagation of an event is stopped on the View, then the propagation of any derived events are stopped. For example, when `stopPropagation()` is called on an `immediate-click` event, `click` and `double-click` events are no longer emitted. When `stopPropagation()` is called on an `pointer-up` event, `immediate-click`, `click` and `double-click` are no longer emitted. This makes implementing event handlers easier, since applications usually want to handle only one of those event types at a time.
