### ISSUE TITLE
Transparent background of WMS in PNG is NOT transparent

### ISSUE THREAD

**Issue by TomGeograf** [Esri/feedback-js-api-next#191]
### IMPORTANT

- [X] My question is related to a new issue in the latest next release. For all other issues, open a ticket with [Esri Technical Support](https://support.esri.com/) or post your question in the [community forum](https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript).
- [X] I have [checked for existing issues](https://github.com/Esri/jsapi-resources/issues) to avoid duplicates. If someone has already opened an issue for what you are experiencing, please add a 👍 reaction and comment as necessary to the existing issue instead of creating a new one.

### Actual behavior

Transparent background of WMS from ArcGIS server (includes only points) in PNG is NOT transparent - looks like JPEG. Network comunication seems to be fine, because transparent PNG is returned.

### Expected behavior

Background should be transparent in PNG (image/png), otherwise it´s unusable.
Expected behaviour is in attached example in API version 4.24.

### Reproduction sample

https://github.com/TomGeograf/ArcGIS-JS/blob/main/wms-4-25.html

### Reproduction steps

1. open sample
2. see not transparent WMS background after load

### Reproduction browser

Microsoft Edge 107

### API version (check your console)

Using ArcGIS API for JavaScript 4.25-next [Date: 20221108, Revision: a0716f65]

### Operating System (check https://whatsmyos.com)

Windows 10* 64-bit

**Comment by annelfitz** [comment]
@TomGeograf - thanks for reporting this! We'll take a look.

**Comment by annelfitz** [comment]
Hi @TomGeograf - we installed a fix for this earlier today. Could you try testing again?
It's working as expected for me now with your test app: https://codepen.io/annefitz/pen/eYKgLJM

Thank you again for reporting this!

**Comment by TomGeograf** [comment]
Hi Anne,

thank you for your message and also for the fix, layer behaviour now seems to be fine! 🙂

Still I am a little disappointed because of change for loading indicator for layers. I think previous version was usefull and this new version works 'only sometimes'. 🙁

Tom
________________________________
Od: Anne Fitz ***@***.***>
Odesláno: středa 9. listopadu 2022 23:47
Komu: Esri/feedback-js-api-next ***@***.***>
Kopie: Tomáš Němeček ***@***.***>; Mention ***@***.***>
Předmět: Re: [Esri/feedback-js-api-next] Transparent background of WMS in PNG is NOT transparent (Issue #191)


Hi @TomGeograf<https://github.com/TomGeograf> - we installed a fix for this earlier today. Could you try testing again?
It's working as expected for me now with your test app: https://codepen.io/annefitz/pen/eYKgLJM

Thank you again for reporting this!

**Comment by annelfitz** [comment]
Hi Tom - glad the layer is working as expected for you now! 

Regarding the loading indicator, could you provide more information on what you mean "works only sometimes"? Do you have a repro case where the layer list indicator is not working?

Thanks,
Anne
