### ISSUE TITLE
COG ImageryTileLayer LOD issues

### ISSUE THREAD

**Issue by tguogis** [Esri/feedback-js-api-next#195]
### IMPORTANT

- [X] My question is related to a new issue in the latest next release. For all other issues, open a ticket with [Esri Technical Support](https://support.esri.com/) or post your question in the [community forum](https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript).
- [X] I have [checked for existing issues](https://github.com/Esri/jsapi-resources/issues) to avoid duplicates. If someone has already opened an issue for what you are experiencing, please add a 👍 reaction and comment as necessary to the existing issue instead of creating a new one.

### Actual behavior

When zooming in on the map in SceneView, the raster doesn't load higher LOD, it seems to always stay on the lowest LOD overview of the raster (zooming in works as expected in MapView). Additionally, when zoomed out beyond the lowest LOD overview in MapView or SceneView, the raster just disappears from the map.

MapView:
![tguogis_0-1669974821703](https://user-images.githubusercontent.com/121484926/209643470-b670a026-3945-4956-ad6a-6585385c4ad0.png)

SceneView:
![tguogis_1-1669974848980](https://user-images.githubusercontent.com/121484926/209643482-084fc0f2-89e9-407e-8e0a-83e82d0fc654.png)

### Expected behavior

Zooming in should load in a higher LOD overview of the raster in SceneView. Zooming out beyond the lowest LOD should probably still keep the raster on the map. 

### Reproduction sample

https://codepen.io/tguogis/pen/mdjVeYN

### Reproduction steps

You can see both issues by zooming in and out on this ESRI example raster in Bolivia (I've changed MapView to SceneView) 

### Reproduction browser

Chrome 108 on Windows 10

### SDK version (check your console)

ArcGIS JS API 4.25

### Operating System (check https://whatsmyos.com)

Windows 10

**Comment by ubatsukh** [comment]
As I mentioned in the esri community post we fill fix this issue and update you once the fix is installed. https://community.esri.com/t5/arcgis-javascript-maps-sdk-questions/cog-imagerytilelayer-in-sceneview-doesn-t-load/m-p/1237167#M79527

**Comment by ubatsukh** [comment]
I will update you on esri community once the fix is installed.
