### ISSUE TITLE
Enhancement: method hitTest() should be return many graphics items from all layers by click

### ISSUE THREAD

**Issue by catcherholms007** [Esri/feedback-js-api-next#20]
Better to be many graphics in hitTest response in 2d and in 3d (I using patches for this)

**Comment by mmgeorge** [comment]
@catcherholms007 this is definitely on our todo list, but we don't quite yet have a time table for it.

**Comment by bsvensson** [comment]
Thank you for submitting this enhancement. We have added it to our internal tracking system for consideration in an upcoming release.

**Comment by steveoh** [comment]
are you going to comment here any longer @bsvensson or is this issue going silent since it is closed?
