### ISSUE TITLE
General enhancement: Add debounce support for the FeatureForm widget

### ISSUE THREAD

**Issue by CalebM1987** [Esri/feedback-js-api-next#205]
### Are you in the right place?

- [x] My enhancement is specifically related to a NEW FEATURE in the latest "next" release. If not, please use "General enhancement:" in the issue title. For issues unrelated to the "next" version, open a ticket with [Esri Technical Support](https://support.esri.com/) or post your question in the [community forum](https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript).
- [X] I have [checked existing issues](https://github.com/Esri/jsapi-resources/issues) to avoid duplicate enhancement requests. If someone has already opened an issue that is related, please add a 👍 reaction and comment as necessary to the existing issue instead of creating a new one.

### Enhancement feature

When using the `FeatureForm`, the [.on('value-changed')](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-FeatureForm.html#event-value-change) event is great for getting updates when the user is making changes in the form. However, it would be useful if there was a built in way to debounce the form `input` (text and textarea) fields so that we don't need to capture every keystroke, but rather be able to pass a small delay such as `500` milliseconds to wait for the user to finish typing before capturing the `value-changed` event.

### Enhancement category

Widgets

### Enhancement short summary

Provide an optional `debounce` property (`number` in milliseconds) for text inputs to wait for the user to stop typing before sending the `value-changed` event. If no `debounce` property is set, just fire the `value-changed` event on every keystroke as it currently does.

### Enhancement description

By providing a `debounce` option, this can improve performance for using event handlers on the `value-changed` event, as it would not be called on every keystroke. Here is an [debounced input example](https://quasar.dev/vue-components/input#debouncing-model) of how it is being done in the `Vue` [quasar](https://quasar.dev/) framework:

This can be accomplished fairly easily by wrapping the callback in a `debounce` function like this:

```ts
/**
 * debounce a function 
 * @param cb - the callback function
 * @param delay - the time to delay in milliseconds
 * @returns 
 */
export function debounce(cb: Function, delay = 250) {
  let timeout: NodeJS.Timeout

  return (...args: any[]) => {
    clearTimeout(timeout)
    timeout = setTimeout(() => {
      cb(...args)
    }, delay)
  }
}
```

And then when subscribing to the event, just wrap the callback in `debounce`:

```ts
featureForm.on('value-change', debounce((evt: __esri.FeatureFormValueChangeEvent)=> {
  this.logService.log('featureForm detected change: ', evt)
  if (evt.valid){
    this.graphicCopy!.attributes[evt.fieldName] = evt.value

    // save edits to local storage in case user refreshes the page
    this.saveEditsToLocalStorage(this.graphicCopy)
  }
}, 500))
```

As you can see, very easy to implement our own `debounce`, but would be nice if it were built into the widget itself. In my use case, if I don't debounce this, the application performance could degrade significantly with constantly checking `localStorage` for the existing edit, updating or creating it, and writing it back to `localStorage` on every keystroke.

### Enhancement severity

Medium - can immediately help improve app performance when subscribing to the `value-changed` event

### SDK version (check your console)

not showing up in my console, but am using `"@arcgis/core": "~4.25.0"` in an Angular app.

**Comment by hgonzago** [comment]
Thanks for the feedback. We've done quite a bit of work into this specifically in regards to editing and the FeatureForm. Async support was added for the FeatureForm's field elements in version 4.25. A big part of this update was specifically focused on making sure that performance would not take a hit. For example, there may be scenarios where multiple expressions get added for a form. Updates were made to inspect all referenced Arcade inspections and audit the expression's fields for any dependencies. Logic was added to help predict if one field is dependent upon another. For example, when a field value changes, the form checks if this field value is used within another expression. If so, it will execute those expressions but not those without dependencies. This helps performance by trimming unnecessary queries. We've also internally taken advantage of debounce support for data input.

There is quite a bit of additional work coming for editor and FeatureForm, all of it will most-definitely need to take performance issues into account. If you come across specific issues, please don't hesitate to let our support team know. They are best equipped to handle these types of concerns and will relay all feedback as needed.
