### ISSUE TITLE
General Enhancement: Support Reference Scale based drawing for GraphicsLayer

### ISSUE THREAD

**Issue by sebastianfrey** [Esri/feedback-js-api-next#208]
### Are you in the right place?

- [X] My enhancement is specifically related to a NEW FEATURE in the latest "next" release. If not, please use "General enhancement:" in the issue title. For issues unrelated to the "next" version, open a ticket with [Esri Technical Support](https://support.esri.com/) or post your question in the [community forum](https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript).
- [X] I have [checked existing issues](https://github.com/Esri/jsapi-resources/issues) to avoid duplicate enhancement requests. If someone has already opened an issue that is related, please add a 👍 reaction and comment as necessary to the existing issue instead of creating a new one.

### Enhancement feature

**Reference Scale** based scaling of Graphics in a GraphicsLayer.

### Enhancement category

GraphicsLayer

### Enhancement short summary

Add support for **Reference Scale** based drawing for GraphicsLayer like in [ArcGIS-Pro](https://pro.arcgis.com/en/pro-app/latest/help/mapping/layer-properties/graphics-layers.htm#GUID-C2323A55-5734-4450-AF53-BD9D1C36BF88).

### Enhancement description

Excerpt from the [ArcGIS-Pro documentation](https://pro.arcgis.com/en/pro-app/latest/help/mapping/layer-properties/graphics-layers.htm#GUID-C2323A55-5734-4450-AF53-BD9D1C36BF88), which describes the feature:

> Define the **Reference Scale** value to determine at which scale the graphics layer appears at the intended size. When this property is set, changes in scale result in graphic elements changing size relative to surrounding features. You can also set a custom scale, or choose **<None>** to stop applying a reference scale.

It would be nice to have the option in 4.x to set a reference scale as follows:

```ts
const graphicsLayer = new GraphicsLayer({
  referenceScale: 2500,
});
```

### Enhancement severity

High

### SDK version (check your console)

\-

### Additional context

In our 3.x client, we had written a custom graphics layer, which scaled graphics based on a defined **Reference Scale**. Any hints or guidance on how to implement this in 4.x using a custom GraphicsLayer is appreciated.

Thanks.

**Comment by annelfitz** [comment]
Hi, you can do this already on an individual symbol basis using the [minScale and maxScale properties on CIMSymbol](https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-CIMSymbol.html#CIMSymbolReference).

This repo is specifically for collecting feedback related to the `/next` release of the JavaScript SDK. For general enhancements to the SDK, please reach out to [Esri support](https://support.esri.com/en) or post on [ArcGIS Ideas](https://community.esri.com/t5/arcgis-javascript-maps-sdk-ideas/idb-p/arcgis-api-for-javascript-ideas). Thank you!

**Comment by sebastianfrey** [comment]
@annelfitz Thank you for getting back to me. I am not sure if the minScale and maxScale properties of CIMSymbol are applicable to my use case. If I understand minScale and maxScale correctly, they allow to define a scale range in which the given symbol should be displayed. In my oppinion, this is not the same as using a reference scale based rendering. This is because the minScale and maxScale approach requires the definition of a composite CIM symbol with fixed minScale and maxScale ranges. The scaling of the size units of symbols would then be exclusively discrete and not linear as in a reference scale based approach.

It is a pity to hear that the request was rejected. I will still submit an enhancement request through our company support account because a) this feature would be a great enhancement for the JSAPI in general and b) this feature is a high priority for most of our customers.

**Comment by annelfitz** [comment]
@sebastianfrey thanks for the explanation! The request was not rejected - this repo is specifically for issues related to the next release of the API.

We will still consider your enhancement request, and if you log it through Esri support, it allows us to track and prioritize the enhancement more easily. Thanks for your understanding.

**Comment by sebastianfrey** [comment]
@annelfitz thanks for clarifying.

I have created the enhancement request through Esri support.
