### ISSUE TITLE
Enhancement: optimize graphics visualization only in current map extent

### ISSUE THREAD

**Issue by catcherholms007** [Esri/feedback-js-api-next#21]
Before versions with webGL using map hide graphics out of the current map extent and it were better and fast navigation with many graphics on the map.

**Comment by mmgeorge** [comment]
@catcherholms007 do you have a map you can share with us?

**Comment by catcherholms007** [comment]
I try to do example

**Comment by bsvensson** [comment]
Closing (for now). Let's re-open once we have a test app.
