### ISSUE TITLE
Enhancement: Async GraphicsLayer.addMany() method

### ISSUE THREAD

**Issue by catcherholms007** [Esri/feedback-js-api-next#22]
Try to use async add many graphics via WebWorker + OffscreenCanvas

**Comment by mmgeorge** [comment]
@catcherholms007 this is because you would like it to be easier to know when the graphics have been added or is this because you would like this to improve performance? Currently we use webworkers for FeatureLayers (graphics layers are more designed for low-latency editing workflows).

**Comment by catcherholms007** [comment]
This is because I would like to improve performance. 
I am using GraphicsLayer for my workflow, because in one layer I can control graphics with different geometry types in one layer. 
Feature layer allow to use graphics only one geometry type.

While GraphicsLayer updating I can see UI blocking (drawing to canvas)

**Comment by anonanonttl** [comment]
I confirm GraphicsLayer.addMany() completely blocks the map. I have a service worker that compute 10K objects (points, lines, polygons), when it's resolved, I do addMany method and map blocks completely for more than five seconds.
