### ISSUE TITLE
Bug, regression: layer removes data when definition expression is updated and esri-native-promise=true

### ISSUE THREAD

**Issue by mpayson** [Esri/feedback-js-api-next#23]
**Describe the bug**
I'm updating the `defintionExpression` based on the scale, but when it first updates the API removes existing data from the map and doesn't load new data. This is a regression from 4.13 and only happens with `esri-native-promise: true`.

**To Reproduce**
1. Go to [this pen](https://codepen.io/mpayson/pen/dyPYgYr)
2. Click the Zoom in button twice

**Expected behavior**
The layer patches new data to reflect the updated definitionExpression

**Browser (check https://whatismybrowser.com/)** 
 - Firefox 70 & Chrome 78
 
**What's your OS? (check https://whatsmyos.com):**
 - macOS Mojave

**API version (check your console)**
 - Version: 4.14-next [Date: 20191206, Revision: 624a19b9]

**Comment by mmgeorge** [comment]
Hi @mpayson thanks for the report. Likely this won't make it in 4.14, but we will ensure this is fixed when we flip the default (currently we're thinking around 4.15-4.16).

**Comment by mmgeorge** [comment]
On further investigation it looks like this is limited to cases where you change the definitionExpression in response to a scale change (i.e., a race between loading new tiles & refreshing).

**Comment by mmgeorge** [comment]
@mpayson we have a fix currently in review for matching the non-native-promise behavior. There will still be some issues when zooming in/out quickly + changing the defexp (as can also be seen in the non-native promise version) where some tiles will disappear. This is caused by outstanding tile requests getting aborted during scale changes. We have plans to refactor some of the controller logic in an upcoming at which point we'll try to tackle those outstanding issues.

**Comment by mmgeorge** [comment]
This was installed and should be in the next version of /next

**Comment by mmgeorge** [comment]
@mpayson I think the fix should now be live on /next

**Comment by mpayson** [comment]
thanks @mmgeorge ! looks to be working well on `/next`

**Comment by mpayson** [comment]
@mmgeorge , hope all is well! Looks like this regressed in `/next`. The API isn't fetching new data and `mapview.updating` hangs on `true`

To reproduce:
1. [Open the pen](https://codepen.io/mpayson/pen/dyPYgYr)
2. Click zoom in twice
3. Top right definition expression set to null / updating stays on true but nothing happens?

This works as expected in 4.14 and was reported by a partner

**Comment by mmgeorge** [comment]
Thanks @mpayson, sorry for the delay. We are investigating the issue.

**Comment by mmgeorge** [comment]
We have a PR up for this now that's currently under review.

**Comment by bsvensson** [comment]
@mpayson - this should be fixed in 4.15 now - https://js.arcgis.com/4.15.

**Comment by mpayson** [comment]
confirmed in the codepen, closing, thanks!!
