### ISSUE TITLE
Enhancement: PictureMarkerSymbol sizes can be more than 200px when additional parameter, for example, scaleable equals false

### ISSUE THREAD

**Issue by catcherholms007** [Esri/feedback-js-api-next#24]
Create in PictureMarkerSymbol optional parameter like a `scaleable` (true/false). When it `false` then symbol sizes can be more than 200px (height and width).  When it `true` then image will be scaled down to a height of 200px while preserving the aspect ratio of the image. 
In documentation white warning about lower performance while using `scaleable`:`false`.

**Comment by mmgeorge** [comment]
@catcherholms007 sorry for the late reply. Is your request that we allow for larger symbol sizes?

**Comment by catcherholms007** [comment]
Yes
