### ISSUE TITLE
Bug: Popups do not render relationships/0/fieldname

### ISSUE THREAD

**Issue by roemhildtg** [Esri/feedback-js-api-next#25]
**Describe the bug**
I discovered this bug while troubleshooting an issue with 4.13. In 4.13, relationship fields would not render inside of `<a href="{relationships/0/fieldname}"` so I decided to test with next and it appears that in this version, these values do not render at all, like in a empty paragraph.

See this webmap: 6f654280a82e45ec9b5e132a3c5df2c9

https://codepen.io/roemhildtg/pen/zYxoKxM?&editable=true&editors=100

**To Reproduce**
1. Click on the shape
2. See that the relationship field does not get rendered at all.

**Browser (check https://whatismybrowser.com/)** 
 - Browser: Firefox 71 on windows 10
 
**API version (check your console)**
 - Version: [e.g. ArcGIS API for JavaScript 4.14.0-next.20191210

Image of ArcGIS Online:
![image](https://user-images.githubusercontent.com/5471079/70944828-79536080-2019-11ea-9a9f-3e9da118b991.png)
![image](https://user-images.githubusercontent.com/5471079/70944845-7fe1d800-2019-11ea-9151-f7bcf57d34df.png)

**Comment by roemhildtg** [comment]
I also have a case open with the support for the 4.13 bug. 

https://my.esri.com/#/support/cases/02458817

**Comment by bsvensson** [comment]
I think this was fixed before 4.14 was officially released.
