### ISSUE TITLE
Bug: Calling sketchViewModel.update results in sketch:invalid-parameter

### ISSUE THREAD

**Issue by roemhildtg** [Esri/feedback-js-api-next#27]
**Describe the bug**
When I call `sketchViewModel.update([graphic]);` I get an error in the console:

```
Logger.js?aac4:25 [esri.widgets.Sketch.SketchViewModel] t {name: "sketch:invalid-parameter", message: "Parameter 'graphics' contains one or more graphics missing from the supplied GraphicsLayer.", details: undefined}
```

I am taking a graphic from a graphicsLayer that is NOT the sketch view model graphics layer, and calling update on it. 

This is code works in 4.13, but not in the latest js api next.

**To Reproduce**
1. Use the sketch view model to create a graphic
2. When graphic is created, clone it and add it to another graphics layer
4. Call `sketch.update([graphic])` on that graphic from the graphics layer.
5. The graphic appears to get destroyed and the error is logged.

**Expected behavior**
I would expect sketch to start editing the graphic. 

**Screenshots**

**Browser (check https://whatismybrowser.com/)** 
Chrome 79
 
**What's your OS? (check https://whatsmyos.com):**
Windows 10 x64

**API version (check your console)**
 - arcgis-js-api@4.14.0-next.20191210

**Additional context**
Its not clear what is the recommended path for handling graphics from a sketch. This seems to switch with every api release as well. My understanding is that the sketch view model uses its own internal graphics layer for all the sketch handles, etc, so I am storing the graphics on a separate graphics layer, since I do not want to deal with all the sketch graphics when using the user drawn graphics.

**Comment by bsvensson** [comment]
Hi @roemhildtg 
The SketchViewModel had some breaking changes at 4.10 when we introduced the Sketch widget, Since then, and as mentioned in https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Sketch-SketchViewModel.html#layer :
_The Sketch widget adds new graphics to this layer or can only update graphics stored in this layer._

So the recommended path for handling graphics is to use the `layer` property.

This has been the case since we introduced the Sketch widget at version 4.10.

**Comment by roemhildtg** [comment]
Hi @bsvensson - I understand to use the layer property but its not clear how to do so. Would this be the recommended approach moving forward?

```js
sketchViewModel.layer.add(graphic);
sketchViewModel.update([graphic]);

//....
// when sketch is done
sketch.on('update', (graphic) => {
    sketchViewModel.layer.remove(graphic);
    // do something with the new graphic
})
```

**Comment by devilsgeographer** [comment]
I have the same issue @roemhildtg and the answer from @bsvensson is not descriptive enough to be useful.   Were you able to figure it out?

**Comment by roemhildtg** [comment]
Yes - I was able to get it working. 

You need to create a new GraphicsLayer and pass that to the sketch view model. Then you need to add any graphics that you want to edit first, then call `sketchViewModel.update` with that graphic. 

Does that make sense?

**Comment by devilsgeographer** [comment]
Yea that makes sense.  Thank you for that detail, I believe I will be able to make it work now.   Have a great day!
