### ISSUE TITLE
Bug: IE11 - Popup disappearing and unable to re-open

### ISSUE THREAD

**Issue by sirishbyreddy** [Esri/feedback-js-api-next#28]
**Describe the bug**
Popup disappear and not appearing again

**Sample File**
[popup_413Next.zip](https://github.com/Esri/feedback-js-api-next/files/3983718/popup_413Next.zip)

**To Reproduce**
1. Download the attached "popup_413Next.zip" file.
2. Extract zip file in your local system
1. Open the "popup_413Next.html" file in IE11
2. Click on map, a popup will appear
3. Click & Hold mouse left button and perform Pan (at a stretch) on the map, such that popup goes out of the map extent
4. Release the mouse left button
5. Pan the map again and bring back the earlier popup location to with in the map extent (You can observe that popup already disappeared)
6. Click on the map (you can try multiple times also), popup will never appear again

**Expected behavior**
IE11:
When the popup visible, even map extent changes, it should not close the popup.
Chrome:
Working as expected

**Browser (check https://whatismybrowser.com/)** 
 - Browser: IE11
 
**What's your OS? (check https://whatsmyos.com):**
 - OS: Windows 10* 64-bit
 - Device: Windows desktop PC

**API version (check your console)**
 - Version:  ArcGIS API for JavaScript next

**Additional context**
Add any other context about the problem here. Please note if this issue has been reported elsewhere.

**Comment by bsvensson** [comment]
Thank you for reporting this issue.

I put your sample code into  https://output.jsbin.com/vuriwem 

It works fine in Chrome, Firefox, classic Edge and Chromium-based Edge, but not in IE11. We will investigate more.

**Comment by sirishbyreddy** [comment]
@bsvensson 
Thank you Bjorn Svensson, for the quick reply and confirming that not working in IE11.

Any workaround suggestion would be appreciated and Is this bug will be fixed in future release?

**Comment by bsvensson** [comment]
@sirishbyreddy - This has been fixed in the current `next` version.

**Comment by sirishbyreddy** [comment]
@bsvensson
Thank you very much for the quick response....

Its working fine
