### ISSUE TITLE
Drag&Drop will broke itself by touch control

### ISSUE THREAD

**Issue by TomGeograf** [Esri/feedback-js-api-next#284]
### IMPORTANT

- [X] My question is related to a new issue in the latest next release. For all other issues, open a ticket with [Esri Technical Support](https://support.esri.com/en/contact-tech-support), post your question in the [community forum](https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript), or share your idea with the global community on [ArcGIS Ideas](https://community.esri.com/t5/forums/searchpage/tab/message?advanced=false&allow_punctuation=false&q=javascript).
- [X] I have [checked for existing issues](https://github.com/Esri/feedback-js-api-next/issues) to avoid duplicates. If someone has already opened an issue for what you are experiencing, please add a 👍 reaction and comment as necessary to the existing issue instead of creating a new one.

### Actual behavior

On mobile device or even on emulation of device in web browser does not work drag&drop in LayerList with touch control. After few attemptions it stucks in process of changing order of layers.

### Expected behavior

I expect no freeze or stuck during the process of change layer order.

### Reproduction sample

https://github.com/TomGeograf/ArcGIS-JS/blob/main/layerlist.html

### Reproduction steps

1. Open dev tools
2. Emulate mobile device with touch control
3. Try to change layer order (maybe few times)

### Reproduction browser

MS Edge 120, Windows 11

### SDK version (check your console)

ArcGIS Maps SDK for JavaScript 4.29-next [Date: 20240207, Revision: a0f4d97f]

### Operating System (check https://whatsmyos.com)

Windows 11 64-bit

**Comment by sagewall** [comment]
I've created an internal issue, I'll comment back here when it's been fixed.

**Comment by TomGeograf** [comment]
Thanks!

Will be possible to enable Drag&drop only for layers and not for their sublayers?

________________________________

**Comment by sagewall** [comment]
No current plans to prevent sublayer's from being reordered, but it's an idea worth considering.  I can see how that might be useful in some situations.

**Comment by TomGeograf** [comment]
Native reorder option for layers Is really usefull, but in most/some cases it is undesirable for sublayers. Please consider this and make it as a choice. Or I will be forced to hide button using classess, etc... :(

________________________________

**Comment by sagewall** [comment]
Related issue: https://github.com/Esri/calcite-design-system/issues/8728

**Comment by TomGeograf** [comment]
New API is live, but this bug is still here, why? :(

**Comment by sagewall** [comment]
@TomGeograf
If you upgrade your application to use a newer version of the calcite components, might help. If you are using `@arcgis/core`: `npm install @esri/calcite-components@latest`

I tested this out in this [codepen](https://codepen.io/sagewall/full/qBwWREx), and by including the latest calcite library (currently v2.5.1) by CDN and drag and drop seems to be working correctly on iOS 17.3.1. However, I was still having issues with my Android device.

A little more info can be found here about compatible calcite versions in the [release notes](https://developers.arcgis.com/javascript/latest/release-notes/#additional-packages)

**Comment by TomGeograf** [comment]
Thanks, but I am not using npm and calcite components in this way..

Unfortunately, I have to revert back to reorder layers by action buttons. But I found there another bug with broken action toggle button.

________________________________

**Comment by sagewall** [comment]
Hi @TomGeograf ,
We've been able to fix this in the core API by upgrading to calcite version 2.7.1.  It should be available on the public next branch on next Monday's build.
