### ISSUE TITLE
VectorTileLayer response does not contain all elements

### ISSUE THREAD

**Issue by TomGeograf** [Esri/feedback-js-api-next#285]
### IMPORTANT

- [X] My question is related to a new issue in the latest next release. For all other issues, open a ticket with [Esri Technical Support](https://support.esri.com/en/contact-tech-support), post your question in the [community forum](https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript), or share your idea with the global community on [ArcGIS Ideas](https://community.esri.com/t5/forums/searchpage/tab/message?advanced=false&allow_punctuation=false&q=javascript).
- [X] I have [checked for existing issues](https://github.com/Esri/feedback-js-api-next/issues) to avoid duplicates. If someone has already opened an issue for what you are experiencing, please add a 👍 reaction and comment as necessary to the existing issue instead of creating a new one.

### Actual behavior

VectorTileLayer response does not contain all elements, but it works in 4.28.

### Expected behavior

VectorTileLayer response contains all elements.

### Reproduction sample

https://github.com/TomGeograf/ArcGIS-JS/blob/main/vectortilelayer.html

### Reproduction steps

1. Run sample and check missing features
2. Revert to 4.28 in HTML head and check correct response

### Reproduction browser

Edge 120

### SDK version (check your console)

ArcGIS Maps SDK for JavaScript 4.29-next [Date: 20240212, Revision: f74a5f12]

### Operating System (check https://whatsmyos.com)

Windows 11 64-bit

**Comment by TomGeograf** [comment]
The situation has changed, the missing elements will all appear, but their correct symbols will not appear. The correct symbols will flash for a fraction of a second when zoomed in and out. The bug comparison with 4.28 is still valid.

**Comment by ubatsukh** [comment]
We are still working on a fix. I will update you once we install the fix. Thanks

**Comment by ubatsukh** [comment]
OK we just installed the fix for the issues you reported. Can you please check and let me know? Thank you.

**Comment by TomGeograf** [comment]
Seems to be fine now, thank you!
________________________________
Od: Undral Batsukh ***@***.***>
Odesláno: sobota 17. února 2024 1:10
Komu: Esri/feedback-js-api-next ***@***.***>
Kopie: Tomáš Němeček ***@***.***>; Author ***@***.***>
Předmět: Re: [Esri/feedback-js-api-next] VectorTileLayer response does not contain all elements (Issue #285)


OK we just installed the fix for the issues you reported. Can you please check and let me know? Thank you.

**Comment by TomGeograf** [comment]
I am sorry, but I have to report another bug with missing labels and some features...
Can you please open html in zip and try to change SDk version on 28 and 29? You will see missing labels and some point point features (I think that there can´t be label without feature)

Thank you
________________________________
Od: Undral Batsukh ***@***.***>
Odesláno: středa 28. února 2024 17:48
Komu: Esri/feedback-js-api-next ***@***.***>
Kopie: Tomáš Němeček ***@***.***>; Assign ***@***.***>
Předmět: Re: [Esri/feedback-js-api-next] VectorTileLayer response does not contain all elements (Issue #285)


Closed #285<https://github.com/Esri/feedback-js-api-next/issues/285> as completed.

**Comment by Biboba** [comment]
@TomGeograf same issue here. I have case opened in case...

**Comment by TomGeograf** [comment]
Can you send send me link on case please?
________________________________
Od: Biboba ***@***.***>
Odesláno: čtvrtek 29. února 2024 11:23
Komu: Esri/feedback-js-api-next ***@***.***>
Kopie: Tomáš Němeček ***@***.***>; Mention ***@***.***>
Předmět: Re: [Esri/feedback-js-api-next] VectorTileLayer response does not contain all elements (Issue #285)


@TomGeograf<https://github.com/TomGeograf> same issue here. I have case opened in case...

**Comment by ubatsukh** [comment]
@TomGeograf I cannot access your vector tiles any longer. Can you please put a repro case here with some screenshots?

**Comment by TomGeograf** [comment]
You cannot use previous sample, please:

Update layer URL: https://ags.cuzk.cz/arcgis2/rest/services/Hosted/NavigacniMapa/VectorTileServer

And view.goTo.zoom = 8

Thanks

________________________________

**Comment by ubatsukh** [comment]
Thanks. We are investigating the issue.

**Comment by Biboba** [comment]
On my side, using latest 4.29.4 and CDN, labels are now displayed properly.

**Comment by ubatsukh** [comment]
Thank you for reporting the issue and confirming the fix.
