### ISSUE TITLE
CIMSymbol not displaying

### ISSUE THREAD

**Issue by steveoh** [Esri/feedback-js-api-next#286]
### IMPORTANT

- [X] My question is related to a new issue in the latest next release. For all other issues, open a ticket with [Esri Technical Support](https://support.esri.com/en/contact-tech-support), post your question in the [community forum](https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript), or share your idea with the global community on [ArcGIS Ideas](https://community.esri.com/t5/forums/searchpage/tab/message?advanced=false&allow_punctuation=false&q=javascript).
	- case number 03563620
- [X] I have [checked for existing issues](https://github.com/Esri/feedback-js-api-next/issues) to avoid duplicates. If someone has already opened an issue for what you are experiencing, please add a 👍 reaction and comment as necessary to the existing issue instead of creating a new one.

### Actual behavior

symbol is not drawn but is still a hit target.  They drew until 4.28. Does not draw in 4.29 or next

### Expected behavior

It should display the points properly

### Reproduction sample

https://gist.github.com/steveoh/871c8706c5a75a90be6f35398a919192

### Reproduction steps

1. open with 4.28 and notice points
2. update to 4.29 or next and notice points no longer display

### Reproduction browser

chrome 121 on macos ventura 

### SDK version (check your console)

"Using ArcGIS Maps SDK for JavaScript 4.29 [Date: 20240223, Revision: 417264d9]"

### Operating System (check https://whatsmyos.com)

```
  System:
    OS: macOS 13.6.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 55.64 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
```

**Comment by annelfitz** [comment]
Hi @steveoh - thanks for reporting this! We're looking into it.

**Comment by annelfitz** [comment]
@steveoh we're working on fixing a bug for this one, but there's also an issue with the Arcade expression that you're using. 

```
iif(hasKey($feature, "text") && $feature.text, [31, 41, 55, .25], [31, 41, 55, 1]);
```

`$feature.text` does not return a boolean, so it does not work in this logical expression. Instead, if you want to check if the given key exists **and** has a value, use the Arcade [HasValue](https://developers.arcgis.com/arcade/function-reference/dictionary_functions/#hasvalue) function instead:

```
iif(hasValue($feature, "text"), [31, 41, 55, .25], [31, 41, 55, 1]);
```

**Comment by steveoh** [comment]
> @steveoh we're working on fixing a bug for this one, but there's also a couple of issues with the Arcade expression that you're using that will need fixing.

In my code I am using boolean fields that do not exist in the sample. I used a field that was available in the sample feature service just in case that could cause an issue.

The rgb string/array does work but I can see that it's going to be an issue that needs fixing. Thanks for identifying that.

**Comment by annelfitz** [comment]
Sounds good. This fix is now available on production - here's a codepen of your app (with the updated Arcade and a boolean value used for text): https://codepen.io/annefitz/pen/RwObgOw

**Comment by steveoh** [comment]
I just tried this in 4.29.10 and it doesn't seem to be functioning. Does this look valid to you? I'm pretty sure I made the changes you requested properly. 

```
{
  type: 'CIMPrimitiveOverride',
  primitiveName: 'selected',
  propertyName: 'Color',
  valueExpressionInfo: {
    type: 'CIMExpressionInfo',
    title: 'Color of pin based on selected status',
    expression:
      'iif(hasKey($feature, "selected") && $feature.selected, "rgba(147, 197, 253, 1)", "rgba(251, 251, 251, 1)");',
    returnType: 'Default',
  },
},
```

**Comment by annelfitz** [comment]
Hi @steveoh - I believe it is working as expected in 4.29 and next. Here's an [example](https://codepen.io/annefitz/pen/RwObgOw). I updated the app so that if the letter button is selected at the top, all new symbols are drawn with a `text` attribute value of `null`. The override gets applied to the symbols like so: 
<img width="397" alt="Screenshot 2024-04-17 at 8 55 47 AM" src="https://github.com/Esri/feedback-js-api-next/assets/51344676/faa55587-d0c8-4128-b61a-d3fcdb3d7165">

I'd recommend updating your expression to use the Arcade [HasValue](https://developers.arcgis.com/arcade/function-reference/array_functions/#hasvalue) function. Or if you don't want to do that, wrap your `$feature.selected` in an [IsEmpty](https://developers.arcgis.com/arcade/function-reference/logical_functions/#isempty) function: 
```
hasKey($feature, "selected") && !IsEmpty($feature.selected)
```

The logic in your expression as it is now will likely always return false due to Arcade's implicit casting: https://developers.arcgis.com/arcade/guide/type-casting/#implicit-boolean-casting

**Comment by annelfitz** [comment]
Ah, I see -- didn't realize selected was boolean, your Arcade should work as expected then 👍 
I updated the app to use a boolean value instead of a string, still works for me: https://codepen.io/annefitz/pen/zYXmBzX?editors=1000

**Comment by steveoh** [comment]
One difference between your example and my use case is that I am updating the graphics attributes on click and the symbol isn't changing. You are creating the graphic with a different symbol and that does appear to be working.

**Comment by annelfitz** [comment]
You may need to clone the symbol and reapply it to the graphic after updating the attribute.
If you share a repro case, I can take a closer look.

**Comment by steveoh** [comment]
Would that be a technical change required to migrate from 4.28 and 4.29? Yep, i'll make a repro. I'm pretty sure I already have one from way back. Yep, https://codepen.io/steveoh-the-encoder/pen/yLPPQrr. This does what I expect back to 4.26 when i created it. I updated it to 29 to show that it's misbehaving.

**Comment by annelfitz** [comment]
Thanks for the repro case @steveoh ! We're looking into it.

In the meantime, you can clone the symbol and reapply it as a workaround.

**Comment by steveoh** [comment]
should we reopen this?

**Comment by annelfitz** [comment]
No need - we just installed a fix for this 🙂 

It should be available now in [4.30.0-next.20240425](https://www.npmjs.com/package/@arcgis/core/v/4.30.0-next.20240425). The CDN (https://js.arcgis.com/next) should be updated with this fix on Monday.

**Comment by steveoh** [comment]
What was the issue?

**Comment by annelfitz** [comment]
We weren't properly updating the symbol with the attribute value changed.
