### ISSUE TITLE
ChangeLog performance enhancements error ?

### ISSUE THREAD

**Issue by Biboba** [Esri/feedback-js-api-next#29]
Out of curiosity, are WebGL performance improvements in 4.14 or for 4.15 ? So far it is mentionned in both:
- 4.14 releases notes: **[link](https://developers.arcgis.com/javascript/latest/guide/release-notes/)**
- 4.15 change log [link](https://github.com/Esri/feedback-js-api-next/blob/07fd19b1f46f1cc432086dbe8c7115dfa7a1dcfe/CHANGELOG.md)

Thanks !

**Comment by bsvensson** [comment]
While there are some minor changes already, that bullet in the changelog seems like it was copied across by mistake.  I'll remove it.  Thanks for letting us know.

**Comment by Biboba** [comment]
OK thanks. 
I only mentionned WebGL but it seems like all the performance enhancements have been duplicated from 4.14
