### ISSUE TITLE
CoordinateConversion widget Input coordinate format chooser as wrong spacing/CSS

### ISSUE THREAD

**Issue by Calin-Geoinfo** [Esri/feedback-js-api-next#302]
### IMPORTANT

- [X] My question is related to a new issue in the latest next release. For all other issues, open a ticket with [Esri Technical Support](https://support.esri.com/en/contact-tech-support), post your question in the [community forum](https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript), or share your idea with the global community on [ArcGIS Ideas](https://community.esri.com/t5/forums/searchpage/tab/message?advanced=false&allow_punctuation=false&q=javascript).
- [X] I have [checked for existing issues](https://github.com/Esri/feedback-js-api-next/issues) to avoid duplicates. If someone has already opened an issue for what you are experiencing, please add a 👍 reaction and comment as necessary to the existing issue instead of creating a new one.

### Actual behavior

The coordinate format text is cut off. In an earlier version this was the case as well on the "main window", now only in the input coordinate window.

### Expected behavior

The way it looks like in 4.29

### Reproduction sample

https://developers.arcgis.com/javascript/latest/sample-code/sandbox/?sample=widgets-coordinateconversion add jsnext

### Reproduction steps

Click on the pencil icon.

### Reproduction browser

Chrome

### SDK version (check your console)

20240523

### Operating System (check https://whatsmyos.com)

Windows

**Comment by NoashX** [comment]
Thanks for reporting this @Calin-Geoinfo. I can reproduce the issue. We are investigating.

**Comment by NoashX** [comment]
Update: we have a fix in place, and this will be resolved at the 4.30 release. The fix should be testable via _next_ in the coming days.

**Comment by Calin-Geoinfo** [comment]
I can confirm it is fixed. Thanks.
