### ISSUE TITLE
Bug: multiplying graphics on the map

### ISSUE THREAD

**Issue by besLisbeth** [Esri/feedback-js-api-next#31]
Hi everyone, 
I noticed a strange bug with multiplying graphics on the map after the execution of the particular steps. This bug reproduced from the version 4.13 (I started from it, maybe even earlier) up to the 'next', but I couldn't send the request at the `https://support.esri.com/`, because my account is not confirmed.

**Steps to reproduce the behavior**
1. Add two graphics layers
2. Add graphics to the first layer
3. Set opacity different from 1 to the second layer
4. Add graphics to the second layer
5. Call removeAll() of graphics of the first layer
6. Drag map to see the bug
7. Zoom in/out to clear the bug issue

**Code to reproduce**

It's based on https://github.com/Esri/jsapi-resources
```
import "./config";

import TileLayer from "esri/layers/TileLayer";
import ArcGISMap from "esri/Map";
import MapView from "esri/views/MapView";
import GraphicsLayer from "esri/layers/GraphicsLayer";
import Graphic from "esri/Graphic";

const map = new ArcGISMap();

const view = new MapView({
    map,
    container: "app",
    extent: {
        spatialReference: {
            wkid: 102100
        },
    },
    zoom: 5,
    center: [32.37700182573525, 51.571642079194056]
});

const createGraphicFromPoint = ({longitude, latitude}) => {
    return new Graphic({
        geometry: {type: 'point', longitude, latitude},
        symbol: {
            type: "simple-marker",
            color: [226, 119, 40, 0.8],
            outline: {
                color: [255, 255, 255],
                width: 2
            }
        }
    });
};

const tileLayer = new TileLayer({url: "https://sampleserver6.arcgisonline.com/arcgis/rest/services/World_Street_Map/MapServer"});
map.add(tileLayer);

const grLayer = new GraphicsLayer();
const grLayer1 = new GraphicsLayer();
grLayer.add(createGraphicFromPoint({longitude: 37.524, latitude: 52.56}));

map.add(grLayer);
map.add(grLayer1);

view.on('click', (event) => {
    grLayer1.opacity = grLayer1.opacity - 0.1;
    grLayer1.add(createGraphicFromPoint(event.mapPoint));
    setTimeout(() => grLayer.removeAll(), 2000);
});
```

**Screenshots**

![bug](https://user-images.githubusercontent.com/31760858/72425208-fd6f4400-378f-11ea-9e6c-1515e7bbe6ae.gif)

**Browser** 
 - Browser: Chrome 79 on Windows 10
 
**What's your OS?**
 - OS: Windows 10* 64-bit
 - Device: Laptop Dell P66F

**API version**
 - Version: [ArcGIS API for JavaScript 4.13/4.14/next]

**Additional context**
It's important for our team to have at least steps to avoid the bug because users of our application noticed it, and we cannot find the right way using the current API.

**Comment by mmgeorge** [comment]
@besLisbeth thanks for reporting this, we'll take a look.

**Comment by besLisbeth** [comment]
Hi!
I'd like to know if this fix will be in the 4.15 version?

**Comment by mmgeorge** [comment]
Hi @besLisbeth. We are planning on fixing this for 4.15. We'll let you know when we have it deployed to /next

**Comment by bsvensson** [comment]
This has been fixed and is available on https://js.arcgis.com/next now

@besLisbeth - please test and let us know if there's any issues.

**Comment by besLisbeth** [comment]
@bsvensson, I still bump into this issue. I add a new marker on the screen by clicking on the map and started dragging the map using the code above.

![image](https://user-images.githubusercontent.com/31760858/76949334-0f48a100-6911-11ea-9058-cb3eff90b21b.png)

**Comment by besLisbeth** [comment]
Can I ask you to reopen it?

**Comment by NoashX** [comment]
Hi @besLisbeth, I tested this again and the fix still looks good. I then compared to the previous version and the bug is there. Can you try clearing your browser cache, or perhaps incognito mode, and test again? Perhaps there is some sort of caching issue with the latest version of js-next.

**Comment by besLisbeth** [comment]
Hi @NoashX, I also tested it again - with the updated dependencies and in the incognito mode - still all the same.

**My dependencies:** 
```
"devDependencies": {
    "@theintern/istanbul-loader": "^1.0.0-beta.2",
    "@types/sinon": "^7.5.2",
    "clean-webpack-plugin": "^3.0.0",
    "copy-webpack-plugin": "~5.1.1",
    "css-loader": "^3.4.2",
    "html-loader": "^1.0.0",
    "html-webpack-plugin": "^4.0.1",
    "mini-css-extract-plugin": "^0.9.0",
    "node-sass": "~4.13.1",
    "prettier": "^2.0.2",
    "resolve-url-loader": "^3.1.1",
    "sass-loader": "^8.0.2",
    "style-loader": "~1.1.3",
    "terser-webpack-plugin": "^2.3.5",
    "ts-loader": "^6.2.2",
    "tslib": "^1.11.1",
    "tslint": "^6.1.0",
    "tslint-config-prettier": "^1.18.0",
    "tslint-eslint-rules": "^5.4.0",
    "tslint-plugin-prettier": "^2.2.0",
    "typescript": "^3.8.3",
    "webpack": "^4.42.1",
    "webpack-cli": "~3.3.11",
    "webpack-dev-server": "^3.10.3"
  },
  "dependencies": {
    "@arcgis/webpack-plugin": "~4.14.2"
  }
```

**And the result:**

![image](https://user-images.githubusercontent.com/31760858/77528032-e33f9980-6e95-11ea-885d-a1e21c76fb0a.png)

**Comment by besLisbeth** [comment]
Created the gif file with the new dependencies. If you look closely, you can see that after the click on the map, after the second or so,  the marker change color intensity, like it was duplicated. And while the dragging - it duplicated.

![screencast-localhost_8081 (3)](https://user-images.githubusercontent.com/31760858/77531208-3c5dfc00-6e9b-11ea-9e66-899e2ea9b499.gif)

**Comment by dasa** [comment]
Can you see what's reported using `npm ls arcgis-js-api`?

**Comment by odoe** [comment]
@besLisbeth I wasn't able to repro with the latest next release.

Here is a repo with the code sample above.
https://github.com/odoe/jsapi-next-issue-31

Live demo
https://jsapi-next-issue-31.surge.sh/

I am on a Mac though, so maybe its windows specific? Could you test the above app? Are there any errors in the console?

Thanks.

**Comment by odoe** [comment]
Looking at your package.json, I don't see the jsapi next install. Can you please try `npm install --save arcgis-js-api@next` and try again? Thanks.

**Comment by besLisbeth** [comment]
Yeah, sorry, that's my bad. I changed `config.js` with 
```
const DEFAULT_WORKER_URL = "https://js.arcgis.com/next/";
const DEFAULT_LOADER_URL = `${DEFAULT_WORKER_URL}dojo/dojo-lite.js`;
```
but totally forgot about npm dependency. Thanks, everybody, for the help with this issue!
