### ISSUE TITLE
Enhancement: display IntegratedMeshLayer, SceneLayer,BuildingSceneLayer,PointCloudLayer with custom spatialReference in local SceneView

### ISSUE THREAD

**Issue by dansdocker** [Esri/feedback-js-api-next#32]
**Enhancement category**
SceneView

**Enhancement short summary**
Users would like the API to display IntegratedMeshLayer, SceneLayer,BuildingSceneLayer,PointCloudLayer with custom spatialReference in local SceneView.

**Enhancement description**
Users now can use ArcGIS Pro 2.5 beta3 creating slpk of IntegratedMeshLayer with custom spatialReference, then publishing. This is an enhancement that the ArcGIS Pro Team has worked hard to accomplish. In order to achieve a complete workflow, the user needs to visualize the IntegratedMeshLayer of this custom coordinate system on the web side.
I found that it is not working now. When I add a tileLayer of a custom coordinate system and IntegratedMeshLayer with the same coordinate system in the local scene, an error of spatial reference inconsistency will be reported, but my console.log ()  the coordinate system of two layers and the view The coordinate system was found to be consistent.

**Severity**
High. Because many projects require a custom coordinate system for location security and confidentiality. If i3s does not support custom coordinate systems, Esri will lose customers in these areas, which is quite unfavorable.

**Screenshots**
Sorry i won't upload the picture yet, here.

**API version (check your console)**
 - Version: Using ArcGIS API for JavaScript 4.15-next [Date: 20200106, Revision: 08186fb3]

**Additional context**
Many projects require a custom coordinate system for location security and confidentiality. If i3s does not support custom coordinate systems, Esri will lose customers in these areas, which is quite unfavorable.

**Comment by RalucaNicola** [comment]
Hi Dans, 

We tried it with an internal IntegratedMesh layer with a [projected coordinate system for Australia](https://epsg.io/28355) and we could load it in a local scene. To my knowledge in a local scene you should be able to load any of the layers you mentioned in a projected coordinate system.
Can you give us a bit more information about the issue you're seeing:
 - What coordinate system are you using?
 - Can you take a screenshot of the console error?
 - Does the tile layer load fine? 
 - When you load the IntegratedMesh does it not show up and throw the error you mentioned?

Or if the data is not private, it would be awesome if you could share it with us.

**Comment by dansdocker** [comment]
For clearly , I will answer your question by order.
1. The coordinate system has no wkid. Only WKT. PROJCS["ShangHaiCity",GEOGCS["GCS_Beijing_1954",DATUM["D_Beijing_1954",SPHEROID["Krasovsky_1940",6378245.0,298.3]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Gauss_Kruger"],PARAMETER["False_Easting",8.0],PARAMETER["False_Northing",-3450000.04],PARAMETER["Central_Meridian",121.0],PARAMETER["Scale_Factor",1.0],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0]]

2.(1) loading failed by ArcGIS API for JavaScript.
![loaderror](https://user-images.githubusercontent.com/25220681/72673057-f140fa80-3a9f-11ea-8663-8061162d129b.png)
  (2) loading Successfully in ArcGIS Pro.
![loadsuccessInPro](https://user-images.githubusercontent.com/25220681/72673076-3d8c3a80-3aa0-11ea-94a8-a342f81f7ee1.png)

3.No , the layer cannot be loaded.
4. It dosen't show up.

**Comment by dansdocker** [comment]
If you can provide an FTP server. I can upload this slpk and a point to make maps and scene overlays.

**Comment by RalucaNicola** [comment]
so it seems that we don't support projections that don't have wkid. I'll have to check what the plans are to add support for this and come back to you.

**Comment by dansdocker** [comment]
@RalucaNicola Thanks, I look forward to your reply.
