### ISSUE TITLE
Enhancement: FeatureTable Widget

### ISSUE THREAD

**Issue by rangasatishkumar** [Esri/feedback-js-api-next#34]
**Enhancement category**
Widget

**Enhancement short summary**
When can expect FeatureTable widget in ArcGIS API for JavaScript 4.x?

**Enhancement description**

**Severity**
High

**Screenshots**

**API version (check your console)**
 - Version: ArcGIS API for JavaScript 4.x?

**Additional context**

**Comment by hgonzago** [comment]
Hi, we intend on getting the first iteration of FeatureTable out in our next release of 4.15. This version will have basic viewing functionality of features within the table. We intend to update it as the API grows.

HTH

**Comment by rangasatishkumar** [comment]
Eagerly waiting for FeatureTable :)

**Comment by rangasatishkumar** [comment]
May I know the name of grid component and it's version that will be used for upcoming FeatureTable widget?
