### ISSUE TITLE
Bug: "[trigger-action:unknown-action]: Unable to identify action to perform"

### ISSUE THREAD

**Issue by RyannGalea** [Esri/feedback-js-api-next#35]
I have an issue when i click on a popup action i get the following error, I never had the issue show up using 4.14 only on this next version. This is in an angular 9 project.

Currently using: "arcgis-js-api": "^4.15.0-next.20200121",

```
core.js:6412 ERROR Error: Uncaught (in promise): [trigger-action:unknown-action]: Unable to identify action to perform
    at resolvePromise (zone-evergreen.js:793)
    at Function.reject (zone-evergreen.js:883)
    at Object.C [as reject] (promiseUtils.js:25)
    at Object.push../node_modules/arcgis-js-api/widgets/Popup/actions.js.r.triggerAction (actions.js:25)
    at Object.<anonymous> (PopupViewModel.js:25)
    at Evented.js:25
    at Array.forEach (<anonymous>)
    at t.emit (Evented.js:25)
    at Object.e.emit (Evented.js:25)
    at Object.t.triggerAction (PopupViewModel.js:25)
```

I create the layer like shown here:
```
    this.layer = new FeatureLayer({
      id: 'businessGeometry',
      source,
      fields: [
        { name: '_id', type: 'string' },
        { name: 'address', type: 'string' },
        { name: 'object_id', type: 'oid' }
      ],
      objectIdField: 'object_id',
      popupTemplate: {
        title: '{address}',
        actions: [
          { title: 'Property', id: 'business-property', className: 'fas fa-map-marker-alt' },
          { title: 'Jobs', id: 'business-jobs', className: 'fas fa-briefcase' }
        ] as any,
        outFields: ['*']
      }
    })
```

I create the listen events like this using a behaviourSubject in RXJS
```
private _popup$: BehaviorSubject<PopupTriggerActionEvent> = new BehaviorSubject(null)

this._mapView.popup.on('trigger-action', e => this._popup$.next(e))

popup$(_id) {
   return this._popup$.pipe(filter(Boolean), filter(({action:{id}}) => id === _id))
}

```

and whenever i have to listen for an action to be clicked, I do so as shown here:
```
popup$('business-property').subscribe(e => this.popupPropertyClick(e))
```

It still functions as it should but i receive the error on console.

**Comment by bsvensson** [comment]
Hi @RyannGalea - I think this has been resolved. Could you test again?

**Comment by RyannGalea** [comment]
@bsvensson How can i get on the latest next build? just using @next on npm install?

**Comment by RyannGalea** [comment]
Yep it is working on my end, i think it was actually resolved in '20200303'..

I do get this warning still unrelated to this.

```
./node_modules/arcgis-js-api/core/workers/WorkerFallback.js 25:2859-2869
Critical dependency: the request of a dependency is an expression
warnings @ client:135
```

**Comment by bsvensson** [comment]
@RyannGalea - that seems like a separate issue.  If that's specific to the `next` and not happening with 4.14 and earlier, could you create a separate issue for that?  Thanks :)

**Comment by andygup** [comment]
For others that run across the `Critical dependency` message please refer to this comment: https://github.com/Esri/arcgis-webpack-plugin/issues/84#issuecomment-621283968
