### ISSUE TITLE
Bug: Web Map Printing produces error for MapImageLayers

### ISSUE THREAD

**Issue by pieter990** [Esri/feedback-js-api-next#36]
**Describe the bug**
ArcGIS Javascript API v4.13 works perfectly and I can print my MapImageLayers, but I get the following error when executing the same geoprocessing task using v4.14. 
Seems to be something missing from the Web_Map_as_JSON input parameter, since I get the following error message: TypeError: Cannot set property 'drawingInfo' of undefined.

I use the following python script which was published via ArcGIS Pro:
[PrintWebMapAdvanced.zip](https://github.com/Esri/feedback-js-api-next/files/4126965/PrintWebMapAdvanced.zip)

**To Reproduce**
1. Switch on a MapImageLayer on the map.
2. Execute a exportwebmap geoprocessing task
3. See Error

**Expected behavior**
It should print and produce output

**Browser (check https://whatismybrowser.com/)** 
Chrome
 
**What's your OS? (check https://whatsmyos.com):**
Windows 10* 64-bit"

**API version (check your console)**
 - Version: ArcGIS API for JavaScript 4.15-next.20200109 [Revision: 49dc0031]]

**Additional context**
The printing works fine when I add a Feature Layer to my map, but fails as soon as I add a MapImageLayer

**Comment by NoashX** [comment]
Hi Pieter, I just tried and it works for me with js-next. Perhaps there is a caching issue, as js-next gets updated regularly with more fixes and updates. Here is a codepen that I used to test: https://codepen.io/noash/pen/PowvyvO

**Comment by pieter990** [comment]
Hi Noah,

Thank you, it seems that you are right. I used the local build of v4.14,
but with the next api it seems to work fine.
Sorry about that.

I assume this bug fix will be included in v4.15 which are to be release in
March 2020 ?

Kind regards,
Pieter

**Comment by NoashX** [comment]
Correct, this fix will be a part of the 4.15 release, which is due out in Spring (March/April).
