### ISSUE TITLE
Bug: HTML in popupTemplate not showing

### ISSUE THREAD

**Issue by pieter990** [Esri/feedback-js-api-next#37]
**Describe the bug**
My popup works fine in v4.12, but the HTML which is added after the fields does not display in v4.14.
This is the javascript code:
          feature.popupTemplate = {
            title: layerName,
            content:[{
              type: "fields",
              fieldInfos: [
                  {
                    fieldName: "TA_NAME",
                    label: "Name"
                  },
                  {
                    fieldName: "GAZETTE",
                    label: "Gazette No"
                  },
                  {
                    fieldName: "PROVINCE",
                    label: "Province"
                  },
                  {
                    fieldName: "SOURCE",
                    label: "Source"
                  },
                  {
                    fieldName: "Status",
                    label: "Status"
                  }
                ]
              },
              {
                  type: "text",
                  text: attachment_hyperlink.text
              }
            ]
          };

**To Reproduce**
1. create popuptemplate that combines "fields" content with "text" content (html)
2. Only "fields" content is shown

**Expected behavior**
Both "fields" and "text" should appear in the popup

**Screenshots**
This is what the popup should look like (v4.12)
![image](https://user-images.githubusercontent.com/20990920/73342478-54444580-4287-11ea-8727-508cbba500ee.png)

**Browser (check https://whatismybrowser.com/)** 
Chrome
 
**What's your OS? (check https://whatsmyos.com):**
Windows 10* 64-bit"

**API version (check your console)**
Version: ArcGIS API for JavaScript 4.15-next.20200109 [Revision: 49dc0031]]

**Additional context**
As an interim I followed the workaround as proposed here:
https://community.esri.com/thread/246183-414-html-in-popuptemplate-not-rendering
But I hope that the bug could be resolved, since the output for combining the fields in table format with the html still does not work with this solution. I now have to put everything in HTML, including the fields.

**Comment by hgonzago** [comment]
I'm guessing it's the HTML sanitizer doing its thing. Could you please send us a repro sample showing this? There may be something else going on that we need to know about.

Thanks.

**Comment by pieter990** [comment]
This bug have been resolved with the ArcGIS API for JavaScript 4.15. Thank you very much

**Comment by hgonzago** [comment]
Great, thanks for letting us know.
