### ISSUE TITLE
esri/views/MapView: Property “scale” is not correct updated after change

### ISSUE THREAD

**Issue by jessebluemr** [Esri/feedback-js-api-next#38]
**Describe the bug**

The MapView reports old scales values if non animated scale changes are used. The wrong scale value is reported after the second non animated scale change.

**To Reproduce**

See also BUG-000129310.

1. Open sample at: https://codepen.io/jessebluemr/pen/eYNgEdq
    Or as alternative (but using view.goTo with animate:false
       https://codepen.io/jessebluemr/pen/qBdjLbg

   The code changes the scale and displays the current value on top of the screen.
   The code uses view.scale property or (alternative: view.goTo({scale: xxx},{animate:false}) method.
   The change is correct applied to the map, but the value reported by the view.watch(“scale”) and view.scale property are not correct after the **second** change.

   Note: pan the map and the value will be corrected.

**Expected behavior**

After the last scale change the view.scale property should report the value used by the map.
Expressed in code this should be equal values:
view.scale === view.state.content.viewpoint.scale

**Analysis**

Reason for the problem is the class esri/views/2d/ViewState.js. This class has an “_update” Method which triggers following code:

```
t.prototype._update = function(e, t) {
    ...
    if (this._set("viewpoint", f),l && i && r) {
        ...
        this.scale = r;
        …
    }
}
```

Important is that the statement:

`this._set("viewpoint", f)`

is called before the scale property is changed. The scale property is not an Accessor property and will not fire an own watch event.
This early call of `_set` triggers the calculation of the computed property `MapView.scale` to early, because the compute function will read the old scale value. This fact leads to the observed problem.

By changing the code to:

```
t.prototype._update = function(e, t) {
    ..
    if (l && i && r) {
        ...
        this.scale = r;
    }
    this._set("viewpoint", f);
    return this;
}
```

the computed property `MapView.scale` will be informed after the value update of the scale property of the ViewState.

**Browser (check https://whatismybrowser.com/)** 
 - Browser: Chrome 80 [www.whatsmybrowser.org/b/HGQ0R]
 
**What's your OS? (check https://whatsmyos.com):**
 - OS: Windows 10* 64-bit
 - Device: Windows desktop PC

**API version (check your console)**
 - Version: Using ArcGIS API for JavaScript 4.15-next [Date: 20200308, Revision: 29ff8778]

**Comment by ronavraham** [comment]
Also ran into this issue. When watching over the "scale" property, old value of the scale reported each time the scale changes.
Please fix this issue, as it makes the API useless for us.

**Comment by bsvensson** [comment]
Thank you for reporting this `next` bug.  However, it seems like this isn't a new problem specific to `next`. The same occurs with 4.13 & 4.14.  But worked with 4.11/41.2.

**Comment by ycabon** [comment]
@jessebluemr Hi Marko! I installed a fix 5 days ago.

**Comment by jessebluemr** [comment]
@ycabon  Hi Yann, I updated both of my test apps and the reported values are now always correct. Thank you! Should I close this bug now?
