### ISSUE TITLE
Enhancement:  cluster labels (with counts)

### ISSUE THREAD

**Issue by anonanonttl** [Esri/feedback-js-api-next#39]
Hello,

Is it planned cluster feature like https://github.com/Leaflet/Leaflet.markercluster?

Thanks

![Capture](https://user-images.githubusercontent.com/29690420/77303950-0c282900-6cf4-11ea-92aa-d2172e22133a.PNG)

**Comment by bsvensson** [comment]
Hello @anonanonttl 
The API already supports clustering in general. 
* https://developers.arcgis.com/javascript/latest/sample-code/featurereduction-cluster/index.html
* https://developers.arcgis.com/javascript/latest/sample-code/featurereduction-cluster-visualvariables/index.html

Or are you referring specifically to showing a label with the counts? Or something else?

**Comment by anonanonttl** [comment]
Hello @bsvensson 

Yes, perhaps override the cluster graphic renderer process to have simple circle symbol with the counts, through a custom layer that extend feature layer.

**Comment by mmgeorge** [comment]
Hi @anonanonttl this is something we are currently looking at adding. For labelling clusters, do you strictly want counts or would it also be beneficial to you to label other clustered fields (e.g. avg temperature, etc). Similarly would you be interested in the ability to change that label to be not just center-center but above-center, below-center, etc.

**Comment by steveoh** [comment]
I think it would be great to center the count, but be able to execute arcade scripts over the feature set contained in the cluster to be able to create averages etc. To me the above-center and below-center aren't that important unless the cluster symbol has some sort of meaning other than color.

**Comment by pspraveenkr** [comment]
> To me the above-center and below-center aren't that important unless the cluster symbol has some sort of meaning other than color.

@steveoh - perhaps above-center and below-center are useful if the cluster symbol is a picture marker symbol?

**Comment by steveoh** [comment]
Ya that makes sense! I think that allowing the offset x,y would be more useful than some magic strings.

**Comment by mmgeorge** [comment]
@steveoh basically we're trying to evaluate whether we want to support the full [labelClass](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-support-LabelClass.html)/labelingInfo API for clusters.

**Comment by steveoh** [comment]
a consistent api is a nice thing.

**Comment by anonanonttl** [comment]
Hi, we really needed it but hey, next time . 
we were also confronted on how to have all objects in the cluster, so maybe it would be interesting to have at least the id of the objects in each cluster.

**Comment by anonanonttl** [comment]
> > To me the above-center and below-center aren't that important unless the cluster symbol has some sort of meaning other than color.
> 
> @steveoh - perhaps above-center and below-center are useful if the cluster symbol is a picture marker symbol?

**Comment by anonanonttl** [comment]
> Hi @anonanonttl this is something we are currently looking at adding. For labelling clusters, do you strictly want counts or would it also be beneficial to you to label other clustered fields (e.g. avg temperature, etc). Similarly would you be interested in the ability to change that label to be not just center-center but above-center, below-center, etc.

It is mainly to group a lot of objects in the map with a simple cirle (polygon) with a fill symbol customizable, with the count in the middle, to have also each object information in the cluster to customize the popup.

**Comment by bsvensson** [comment]
@anonanonttl 
This cluster label with counts functionality is now available in the `next` version - https://github.com/Esri/feedback-js-api-next/blob/master/CHANGELOG.md
