### ISSUE TITLE
Bug:  symbolUtils.renderPreviewHTML : TextSymbol hallo color does not work

### ISSUE THREAD

**Issue by anonanonttl** [Esri/feedback-js-api-next#43]
Hello,

TextSymbol hallo color does not appear in render element preview.

`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
    <title>Intro to graphics - 4.15</title>

    <link rel="stylesheet" href="https://js.arcgis.com/4.15/esri/themes/light/main.css" />
    <script src="https://js.arcgis.com/4.15/"></script>

    <style>
      html,
      body,
      #viewDiv {
        padding: 0;
        margin: 0;
        height: 90%;
        width: 100%;
      }
    </style>

    <script>
      require([
        'esri/Map',
        'esri/views/MapView',
        'esri/symbols/TextSymbol',
        'esri/Graphic',
        'esri/layers/GraphicsLayer',
        'esri/symbols/support/symbolUtils',
      ], function(Map, MapView, TextSymbol, Graphic, GraphicsLayer, symbolUtils) {
        var map = new Map({
          basemap: 'topo-vector',
        });

        var view = new MapView({
          center: [-80, 35],
          container: 'viewDiv',
          map: map,
          zoom: 3,
        });

        var layer = new GraphicsLayer();
        map.add(layer);

        var geometry = {
          type: 'point',
          longitude: -49.97,
          latitude: 41.73,
        };

        var symbol = new TextSymbol({
          color: [48, 58, 58, 255],
          haloSize: 20,
          haloColor: [99, 255, 0, 255],
          horizontalAlignment: 'center',
          angle: 0,
          xoffset: 0,
          yoffset: 0,
          text: 'Hello world !',
          rotated: false,
          kerning: true,
          font: {
            size: 9.75,
            style: 'normal',
            decoration: 'none',
            weight: 'bold',
            family: 'Arial Unicode MS',
          },
        });

        var displaySymbolRenderPreviewHTML = async function() {
          var symbolRenderPreview = await symbolUtils.renderPreviewHTML(symbol);
          document.getElementById('symbolRenderPreview')?.appendChild(symbolRenderPreview);
        };
		
        displaySymbolRenderPreviewHTML();

        var pointGraphic = new Graphic({
          geometry,
          symbol,
        });

        layer.add(pointGraphic);
      });
    </script>
  </head>

  <body>
    <div id="viewDiv"></div>
    <div id="symbolRenderPreview" style="text-align: center;"></div>
  </body>
</html>
`

![test-text-symbol-render-preview-html](https://user-images.githubusercontent.com/29690420/79691591-d75eb180-8260-11ea-8032-cb480ad1365c.PNG)

Thanks

**Comment by bsvensson** [comment]
Hi @anonanonttl  - thank you for reporting this bug.  

However, it doesn't seem like the bug is specific to `next` version. It can be reproduced with any released version.  For such bugs, if possible, please report via [Esri Support](http://support.esri.com/).

This repo is meant for issues specific to the https://js.arcgis.com/next version (and that cannot be reproduced in earlier versions).

We've logged the bug in our internal system. Thank you for reporting.
