### ISSUE TITLE
Bug: FeatureTable showing blank records

### ISSUE THREAD

**Issue by sirishbyreddy** [Esri/feedback-js-api-next#44]
**Describe the bug**
Point feature class published as a service in ArcGIS server and set the parameter "Maximum Number of Records Returned by Server" is to 10.

Total features count is 49.

**To Reproduce**
1. Created new featureTable and passed the 'featureLayer'
 const featureTable = new FeatureTable({
    layer: featureLayer,           
    container: document.getElementById("tableDiv")
  });
2. Once FetureTable is loaded, it is showing attribute values for the first 10 records and remaining 39 are blank.

**Expected behavior**
FeatureTable should show attribute values for all the records/features

**Screenshots**
![FeatureTable](https://user-images.githubusercontent.com/18139951/80176501-5e2dd880-862b-11ea-870f-9c01b3d36d6f.png)

**Browser (check https://whatismybrowser.com/)** 
 - Chrome: Version 81.0.4044.122 (Official Build) (64-bit)
 
**What's your OS? (check https://whatsmyos.com):**
 - OS: Windows 10* 64-bit
 - Device: Windows desktop PC 

**API version (check your console)**
 - Version: ArcGIS API for JavaScript next

**Additional context**
Add any other context about the problem here. Please note if this issue has been reported elsewhere.

**Comment by hgonzago** [comment]
Thanks for the feedback. The issue you are seeing is how the FeatureTable works with pagination. Be default it shows 50 records. Generally, we don't see many instances where a `maxRecordCount` is set this low. We will add a check for this in a later version.

**Comment by sirishbyreddy** [comment]
@hgonzago Thanks for the update

**Comment by hgonzago** [comment]
I'm closing this as this was addressed back with version 4.16. If you are still experiencing the issue. Please let us know.

Thanks
