### ISSUE TITLE
Bug: PopupTemplate menu is shown with no items

### ISSUE THREAD

**Issue by markoskifle** [Esri/feedback-js-api-next#47]
**Describe the bug**

**To Reproduce**
1. Go to '...' (e.g. an app on codepen, jsbin etc)

**Expected behavior**

**Screenshots**

**Browser (check https://whatismybrowser.com/)** 
 - Browser: [e.g. "Edge 78 on Windows 10"]
 
**What's your OS? (check https://whatsmyos.com):**
 - OS: [e.g. "Apple iOS 12.4" or "Windows 10* 64-bit"]
 - Device: [e.g. "Windows desktop PC" or "iPhone 11"]

**API version (check your console)**
 - Version: [e.g. ArcGIS API for JavaScript 4.13-next.YYYYMMDD [Revision: d8d62578]]

**Additional context**
Add any other context about the problem here. Please note if this issue has been reported elsewhere.

**Comment by markoskifle** [comment]
If PopupTemplate has more than 3 actions and only two of the actions are visible, the menu is shown with no menu items

- [ ]

**Comment by bsvensson** [comment]
Hi @markoskifle and thank you for submitting an issue in this repo that's about the "next" (aka beta) version of the ArcGIS API for JavaScript..

As mentioned in the issue template, here are some tips for creating a good issue:

- Can you reproduce the issue with a released version? If so, please report via [Esri Support](http://support.esri.com/).

- Is this a bug specifically for https://js.arcgis.com/next (and cannot be reproduced in earlier versions)? 
  Then you're in the right place...

Also, if you have a short test case of the issue, maybe in a codepen or similar online place that is very much appreciated.
