### ISSUE TITLE
Bug: HistogramRangeSlider Safari issues

### ISSUE THREAD

**Issue by mpayson** [Esri/feedback-js-api-next#5]
**Describe the bug**
HistogramRangeSlider does not adhere to a fixed container height in Safari like in Firefox and Chrome

**To Reproduce**
1. Open this pen in Chrome / Firefox then in Safari, in Safari the slider overflows
> https://codepen.io/mpayson/pen/yLBZzpg

**Expected behavior**
In Safari, Histogram renders in container with fixed height

**Screenshots**
Demo we're working on....

Chrome & Firefox | Safari
:----------------: | :--------:
<img width="255" alt="Screen Shot 2019-09-23 at 8 26 37 PM" src="https://user-images.githubusercontent.com/5892789/65478973-8f012180-de40-11e9-9afa-add64e553b5e.png"> | <img width="255" alt="Screen Shot 2019-09-23 at 8 26 13 PM" src="https://user-images.githubusercontent.com/5892789/65478979-93c5d580-de40-11e9-9380-97a35aa18fe9.png">

**Browser (check https://whatismybrowser.com/)** 
 - Browser: Safari 12.1 on macOS (Mojave)
 
**What's your OS? (check https://whatsmyos.com):**
 - OS X 10.14.5

**API version (check your console)**
 - Using ArcGIS API for JavaScript 4.13-next.20190923 [Revision: 3f682984]

**Additional context**
Not a regression, same behavior in 4.12

**Comment by mpayson** [comment]
Looks like dragging the slider will also occasionally highlight the map view:
<img width="1679" alt="Screen Shot 2019-09-23 at 8 09 02 PM" src="https://user-images.githubusercontent.com/5892789/65478305-1dc06f00-de3e-11e9-8741-1706ebbedacd.png">

**Comment by JonUihlein** [comment]
Thanks for reporting! The highlight issue was reported internally and we're verifying the fix locally.

I don't think there have been any reports about the height issue so we'll take a look. 👍

**Comment by JonUihlein** [comment]
Wanted to follow up: we identified the issue with histogram height in Safari and have committed a fix.

**Comment by ekenes** [comment]
I was able to verify this. @mpayson Can you verify in your app as well?

**Comment by mpayson** [comment]
@ekenes doesn't look fixed in the sample?
> https://codepen.io/mpayson/pen/yLBZzpg

**Comment by ekenes** [comment]
whoops. Sorry. It looks like the fixes didn't make it in this weeks deployment of `next`. It will be there next Monday afternoon though. Sorry for the preliminary 🎉.

**Comment by ekenes** [comment]
This should be fixed now on `next`.

**Comment by mpayson** [comment]
Confirmed, thanks!
