### ISSUE TITLE
Bug: Warnings in console

### ISSUE THREAD

**Issue by RyannGalea** [Esri/feedback-js-api-next#52]
Not sure how to resolve these issues,

```
    "@arcgis/webpack-plugin": "^4.16.0-next.20200427",
    "arcgis-js-api": "^4.16.0-next.20200602",
```

```
[watch:angular] ‼ ｢copy-webpack-plugin｣: unable to locate 'arcgis-js-api\workers\' at 'E:\prosperty\client\node_modules\arcgis-js-api\workers'
[watch:angular] ‼ ｢copy-webpack-plugin｣: unable to locate 'arcgis-js-api\geometry\geometryenginewebworker.js' at 'E:\prosperty\client\node_modules\arcgis-js-api\geometry\geometryenginewebworker.js'
[watch:angular] WARNING in ./node_modules/arcgis-js-api/core/workers/workers.js 25:1129-1139
[watch:angular] Critical dependency: the request of a dependency is an expression
[watch:angular]
[watch:angular] WARNING in ./node_modules/arcgis-js-api/core/workers/WorkerFallback.js 25:2827-2837
[watch:angular] Critical dependency: the request of a dependency is an expression
[watch:angular]
[watch:angular] WARNING in unable to locate 'arcgis-js-api\workers\' at 'E:\prosperty\client\node_modules\arcgis-js-api\workers'
[watch:angular]
[watch:angular] WARNING in unable to locate 'arcgis-js-api\geometry\geometryenginewebworker.js' at 'E:\prosperty\client\node_modules\arcgis-js-api\geometry\geometryenginewebworker.js'
```

**Comment by RyannGalea** [comment]
So it seems to import,

```
"arcgis-js-api": "^4.16.0-next.20200602",

import geometryEngine from 'esri/geometry/geometryEngine'
```

returns undefined now, this was not the case in version 

```
"arcgis-js-api": "^4.16.0-next.20200519"
```

**Comment by odoe** [comment]
The `copy-webpack-plugin` warnings can be ignored. This just requires an update for the `next` of the webpack-plugin. Can you try `import * as geometryEngine from 'esri/geometry/geometryEngine'`? There was some updates here that might need that.

**Comment by RyannGalea** [comment]
@odoe,

This worked, for the time being. 

It also seems like the 'geometryEngine.union()' functionality changed & I had to update my code a little bit.

**Comment by ycabon** [comment]
Hi @RyannGalea.

> It also seems like the 'geometryEngine.union()' functionality changed & I had to update my code a little bit.

can you provide some detail on the change you observed?

**Comment by sandromartis** [comment]
I am seeing the same error message in a Webpack application:

> WARNING in ./node_modules/@arcgis/core/core/workers/workers.js 5:863-872
Critical dependency: the request of a dependency is an expression

> WARNING in ./node_modules/@arcgis/core/core/workers/WorkerFallback.js 5:2264-2273
Critical dependency: the request of a dependency is an expression

I'm trying the following:

```
import PortalItem from '@arcgis/core/portal/PortalItem';

const portalItem = PortalItem.fromJSON(<somePortalItem>);
```

My package.json:
```
"dependencies": {
    "@arcgis/core": "^4.18.0-next.20201108",
    "@arcgis/webpack-plugin": "^4.18.0-next.20201029",
}
```

It doesn't matter if I add `new ArcGISPlugin({ locales: ['en'] })` to my Webpack Plugins or not.

**Comment by odoe** [comment]
Those `Critical dependency: the request of a dependency is an expression` are expected warnings, not errors. There is nothing to be done.
