### ISSUE TITLE
Targeting ES6 In tsconfig.json

### ISSUE THREAD

**Issue by RyannGalea** [Esri/feedback-js-api-next#54]
Description
Not sure if this is the right repository for this or not, but I'm trying to get an idea on when we will be able to compile Arcgis using es6.

Context
I'm currently building an Angular Application and I am starting to have conflicts where it would be much better to set my compiler to es6 instead of es5. Currently, it won't compile properly with Arcgis using es6.

Any info appreciated.

**Comment by andygup** [comment]
@RyannGalea thanks for reaching out. I noticed this question is a duplicate post of https://github.com/Esri/arcgis-webpack-plugin/issues/87. I recommend we close this issue out since it's not directly related to `/next` and continue the conversation over on the webpack-plugin repo.
