### ISSUE TITLE
Bug: Disabled PopupTemplate action fires when clicked

### ISSUE THREAD

**Issue by markoskifle** [Esri/feedback-js-api-next#58]
**Describe the bug**
PopupTemplate action fires when clicked when it is disabled

**To Reproduce**
1. Go to https://codepen.io/markoskifle/pen/PoPxmwQ
2. Click on a feature
3. In the popup click on 'Test Action1'
4. alert widow opens.

**Expected behavior**
The disabled task should not be clicked

**Screenshots**
![2020-07-14_13-53-46](https://user-images.githubusercontent.com/16328524/87459711-c1e7f200-c5d9-11ea-869d-ac55f36453d9.png)

**Browser (check https://whatismybrowser.com/)** 
 - Browser: Edge 83
 
**What's your OS? (check https://whatsmyos.com):**
 - OS: Windows 10* 64-bit"
 - Device: Windows desktop PC

**API version (check your console)** 
- Version: ArcGIS API for JavaScript 4.16.0-next20206629 

**Additional context**
None

**Comment by bsvensson** [comment]
Initially reported as #46 (since closed).

Thank you for adding the repro case.  

It seems like this is not specific to the latest version.  I was able to repro back to at least 4.8.

**Comment by markoskifle** [comment]
That is right.

**Comment by markoskifle** [comment]
Resolved
