### ISSUE TITLE
Enhancement: GraphicsLayer - Static graphics

### ISSUE THREAD

**Issue by anonanonttl** [Esri/feedback-js-api-next#59]
Hello,

Possibility to deactivate graphics re-positioning in graphicsLayer, specially when scale changed.

Thanks

**Comment by mmgeorge** [comment]
@anonanonttl can you elaborate? To zoom or pan graphics have to move (in terms of screen space)

**Comment by anonanonttl** [comment]
@mmgeorge suppose we have a poligon, when zoom in/out, coordinates are recalculated yes, but if we want it to remain fixed, we can recalculate to have previous state but with a large data for a graphicslayer, the performance deteriorates.

**Comment by mmgeorge** [comment]
Ah ok so the polygon screen coordinates need to be recomputed when panning/zooming or there will be issues when interacting with the map. Suppose you are looking at a county directly in the center of the screen, and then you pan left. The vertices of the county need to be translated to the right as you pan or it will stay in the center of the screen. 

The performance issue for graphics is not so much about computing the coordinates, but instead the world space spatial index which is used for hit-testing.
