### ISSUE TITLE
Bug: featureLayer query : 302 redirect to login page  : Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by anonanonttl** [Esri/feedback-js-api-next#60]
Hello

We have all argis services protected behind an apache server, which when the user has invalid session, return a 302  status with 
 login page redirection url, however, requests at the end of this redirection return the error : Unexpected token < in JSON at position 0.

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="initial-scale=1,maximum-scale=1,user-scalable=no"
    />
    <title>
      Request data from a remote server | Sample | ArcGIS API for JavaScript
      4.16
    </title>

    <style>
      html,
      body,
      #container {
        padding: 0;
        margin: 0;
        height: 100%;
        width: 100%;
      }

      .container {
        padding: 1em;
      }

      #btnQuery {
        overflow: auto;
        text-align: center;
        cursor: pointer;
        font-size: 1em;
      }

      input {
        width: 75%;
      }
    </style>

    <link
      rel="stylesheet"
      href="https://js.arcgis.com/4.16/esri/themes/light/main.css"
    />
    <script src="https://js.arcgis.com/4.16/"></script>
  </head>

  <body>
    <div class="container esri-widget">
      <div>
        <h2>Using esri/request</h2>
        <button id="btnQuery">Make Request</button>
        <input
          id="inputUrl"
          type="text"
          value="https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer"
        />
      </div>
      <pre id="resultsDiv"></pre>
    </div>

    <script>
      require(["esri/request"], function (esriRequest) {
        var resultsDiv = document.getElementById("resultsDiv");
        var input = document.getElementById("inputUrl");

        // Define the 'options' for the request
        var options = {
          query: {
            f: "json",
            outFields: "*",
            spatialRel: "esriSpatialRelIntersects",
            where: "1=1"
          },
          responseType: "json"
        };

        // Make the request on a button click using the
        // value of the 'input' text
        btnQuery.addEventListener("click", function () {
          var url = input.value;
          esriRequest(url, options).then(function (response) {
            console.log("response", response);
            var responseJSON = JSON.stringify(response, null, 2);
            resultsDiv.innerHTML = responseJSON;
          }, function(error) {
            console.log(error);
          });
        }); 
      });
    </script>
  </body>
</html>
```

I don't have a test url, but with simple request https://google.com reproduces the error.

**Another problem also is when featureLayer is loaded from map view.**

**Esri requests should follow the redirection to the page in the case of an html content type**

Thanks

**Comment by bsvensson** [comment]
It seems to me like the API is following the redirect correctly.  The problem is that it's redirection to something that is not JSON.

**Comment by anonanonttl** [comment]
Ya, redirect works, but the problem is when server respond with a page location, like login page.

**Comment by pspraveenkr** [comment]
> however, requests at the end of this redirection return the error : Unexpected token < in JSON at position 0.

@anonanonttl - Are you expecting the app itself be redirected to your login page so that the user can login again? 

> Esri requests should follow the redirection to the page in the case of an html content type

What is the final response the browser would receive at the end of the redirection? Is it json or html? If it is html, is the html for the login page?

**Comment by anonanonttl** [comment]
>  Are you expecting the app itself be redirected to your login page so that the user can login again?

@pspraveenkr Yes

> What is the final response the browser would receive at the end of the redirection? Is it json or html? If it is html, is it the html for login page?

It's a html, login page html

**Comment by pspraveenkr** [comment]
Ok. Requests made through XMLHttpRequest or Fetch API don't work that way afaict. Such requests will follow the 302 redirection but they wouldn't trigger a complete page navigation to take the user to the redirected location.

Instead, would it be possible to configure the apache server to return a JSON response (with a suitable error code) instead of redirecting to a HTML page? Then, you can catch that error in the app and trigger page navigation yourself by setting `window.location`.

**Comment by pspraveenkr** [comment]
> configure the apache server to return a JSON response (with a suitable error code)

Note that it may be sufficient to just return an error with 401 as error code. There is probably no need to return JSON response.

**Comment by bsvensson** [comment]
Or keeping the server part as is, just add some error handling for that request.  If it's for a specific application connecting to a specific server, the app would know enough about the infrastructure to do specific handling of this.

```
          if (error && error.message.includes("Unexpected token < in JSON at position 0")) {
            // check if error.details.url seem to be the log in page
            alert("Probably not JSON:\n" + error.details.url);  
            // send people to log in screen 
          } else {
            alert("Unknown problem URL (for esriRequest):\n" + error.details.url);
          }
```

**Comment by anonanonttl** [comment]
> Or keeping the server part as is, add some more error handling for that request. If it's for a specific application connecting to a specific server, the app would know enough about the infrastructure to do specific handling of this.
> 
> ```
>           if (error && error.message.includes("Unexpected token < in JSON at position 0")) {
>             // check if error.details.url seem to be a service url that might trigger the log in page
>             alert("Probably not JSON:\n" + error.details.url);  
>             // send people to log in screen 
>           } else {
>             alert("Unknown problem URL (for esriRequest):\n" + error.details.url);
>           }
> ```

I had done this in the interceptor, but it's not very pretty. In addition, the message is different depending browser type and version

**Comment by anonanonttl** [comment]
> Ok. Requests made through XMLHttpRequest or Fetch API don't work that way afaict. Such requests will follow the 302 redirection but they wouldn't trigger a complete page navigation to take the user to the redirected location.
> 
> Instead, would it be possible to configure the apache server to return a JSON response (with a suitable error code) instead of redirecting to a HTML page? Then, you can catch that error in the app and trigger page navigation yourself by setting `window.location`.

@pspraveenkr 
it's an SSO, on several applications we don't have an access to intercept a 401

**Comment by dasa** [comment]
You could test if the request is redirected and then redirect the page with code like this early in the app:

Option 1 - slightly less efficient since it loads the redirect location, but doesn't hard-code the redirect location:

```js
      const testUrl = "https://js.arcgis.com/4.16";
      fetch(testUrl).then((resp) => {
        if (resp.redirected) {
          window.location.href = resp.url;
        }
      });
```

Option 2 - treats a redirect as an error and manually redirects the page:

```js
      const testUrl = "https://js.arcgis.com/4.16";
      fetch(testUrl, {
        redirect: "error"
      }).catch((err) => {
        if (err instanceof TypeError) {
          window.location.href = "http://www.esri.com/";
        }
      });
```

**Comment by anonanonttl** [comment]
it's more a server side design issue with us, I'm not going to bother with a standard spec, redirect manual is the best solution to handle redirect case for those who will encounter this kind of .., after you've the opaqueredirect response type to handle redirect case then and do what you want with it.

However  the API should provide more sophisticated http interceptors or make error codes more logical than a status code zero.

I close this
