### ISSUE TITLE
Bug: hard coded `esri` asset path causes 404

### ISSUE THREAD

**Issue by COV-GIS** [Esri/feedback-js-api-next#62]
In 4.15 `GeolocationPositioning.js` used relative path `../../images/support/sdk_gps_location.png`. 4.16 switched to `esri/images/support/sdk_gps_location.png`. No good for webpack.

**Comment by odoe** [comment]
This was an issue with the webpack-plugin, the latest [`@arcgis/webpack-plugin@4.16.3`](https://github.com/Esri/arcgis-webpack-plugin/releases/tag/4.16.3) should fix this.

**Comment by COV-GIS** [comment]
It does. Thanks.
