### ISSUE TITLE
@arcgis/core: t9n files missing

### ISSUE THREAD

**Issue by Biboba** [Esri/feedback-js-api-next#67]
**Describe the bug**
Map's widgets are broken because t9n files cannot be found with @arcgis/core built with webpack 

**Framework and build tools** 
 - webpack

**To Reproduce**
Clone the following repository:
https://github.com/Biboba/esrijs-es-modules-webpack-starter
And follow the readme

**Expected behavior**
A map with default widgets should be displayed (zoom), just like on this sample:
https://developers.arcgis.com/javascript/latest/sample-code/webmap-basic/live/index.html
and no error should be logged in the console

**Screenshots**
![Capture d’écran 2020-09-22 à 13 10 39](https://user-images.githubusercontent.com/11556423/93875369-23f95d80-fcd5-11ea-9b85-48c34c042c54.png)

**Browser (check https://whatismybrowser.com/)** 
 - Browser: Chrome 85.0 sur MacOS
 
**What's your OS? (check https://whatsmyos.com):**
 - OS: MacOS 10.15.6
 - Device: Laptop

**API version (check your console)**
 - Version: 4.17.0-next.20200921

**Additional context**
I wanted to update the webpack.config.js to manually copy the t9n files just like it is done in arcgis-webpack-plugin:
https://github.com/Esri/arcgis-webpack-plugin/blob/d949c4c512e8a2b4306d05ca1e268c6e9b065f28/lib/requiredPlugins.js#L213-L224
But having a look in @arcgis/core folder, I could not find the files so I believe they are missing ?

Thanks for your help !

**Comment by odoe** [comment]
Depending on your setup, you can use an npm script to copy the assets folder or do with with the copy-webpack-plugin.

// assuming you copy a public folder during your build
```json
{
	"script": {
        "copy": "ncp ./node_modules/@arcgis/core/assets ./public/assets",
    }
}
```

Or you can use the copy plugin
```js
// webpack.config.js
  plugins: [
    new CopyPlugin({
      patterns: [
        {
          from: "node_modules/@arcgis/core/assets",
          to: "assets"
        }
      ]
    })
  ],
```

**Comment by Biboba** [comment]
Thanks for your quick reply @odoe.
Indeed, that what I tried to do but I could not find them. 
I must have done something wrong in the search...
Sorry for the noise
