### ISSUE TITLE
Bug: Widget editor - Attributes missing after create object -> fill attributes -> move it and submit

### ISSUE THREAD

**Issue by kawamikasa** [Esri/feedback-js-api-next#68]
Graphic attributes are not saved after applyadit, 'see step to reproduce'

**To Reproduce**
1. create an object
2. fill in his attributes
3. move the same object
4. submit form

**Browser (check https://whatismybrowser.com/)** 
 - Firefox 80
 
**What's your OS? (check https://whatsmyos.com):**
 -Windows 10* 64-bit

**API version (check your console)**
 - 4.XX

https://developers.arcgis.com/javascript/latest/sample-code/sandbox/index.html?sample=widgets-editor-basic

**Comment by bsvensson** [comment]
Thanks for reporting this. It does seem to still be a problem in the `next` version as well.

Just a friendly reminder that this repo is intended for bugs that are specific to `next` only, and does not exist in released versions.

See https://github.com/Esri/feedback-js-api-next#issues: _Bugs: Bug reports should be specific to js.arcgis.com/next and not present in the current release._

For bugs that are present in released versions, please contact Esri Support. We've recently added an easy link for that from the "New issue" creation link:
![image](https://user-images.githubusercontent.com/808357/94623688-a059e680-0269-11eb-870a-8b7aab8ce93f.png)
