### ISSUE TITLE
Bug: symbolUtils renderPreviewHTML and CIMSymbol

### ISSUE THREAD

**Issue by valnewville** [Esri/feedback-js-api-next#76]
center horizontal alignement not respected.

Cordially

![Capture](https://user-images.githubusercontent.com/72911603/96096980-b950d180-0ed0-11eb-9850-67fab1aebba2.PNG)

**Comment by annelfitz** [comment]
Hi @valnewville - thanks for reporting this issue. We will work on it and keep you updated on the progress.

**Comment by annelfitz** [comment]
@valnewville This has been fixed. Please test using `https://js.arcgis.com/next` and let us know if you are still seeing any issues.
