### ISSUE TITLE
@arcgis/core: running jest tests with create react app

### ISSUE THREAD

**Issue by steveoh** [Esri/feedback-js-api-next#78]
**Describe the bug**
the app works fine but jest has issues running tests

> Cannot use import statement outside a module

this is on all `@arcgis/core/...` imports

Then I dive into configuring jest to transform the `@arcgis` esm files in `node_modules`

Then jest fails trying to import css files from a commonjs module. So I configure jest to not transform css files.

> ReferenceError: regeneratorRuntime is not defined

Is now thrown from the commonjs module. If I remove the import of the commonjs module,  `@arcgis/.../mapview` throws the following

> TypeError: FilterCSS is not a constructor

Then I give up.

**Framework and build tools** 
 ```
 "react": "^17.0.1",
 "react-dom": "^17.0.1",
 "react-fast-compare": "^2.0.4",
 "react-scripts": "^4.0.0"
```

**To Reproduce**

use the sample in https://github.com/Esri/feedback-js-api-next/pull/74 and run `npm test`

**Expected behavior**

I should be able to run tests that import esri modules without too much cruft.

**API version (check your console)**

4.17.0-next.20201008

**Additional context**

adding 

```json
"jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!(@arcgis)/)"
    ]
  }
```

to the `package.json` allows the test to complete with lots of console errors

**Comment by odoe** [comment]
This requires that you create `__mocks__` for the `@arcgis/core` modules you are importing with files being tested. Most of them can be simple like this.
```js
// src/__mocks__/@arcgis/core/layers/FeatureLayer.js
export default class FeatureLayer {};
```

I'll get an updated CRA sample updated in the existing PR.

**Comment by odoe** [comment]
The sample has been updated for the PR here.
https://github.com/odoe/feedback-js-api-next/tree/add-esm-samples/esm-samples/jsapi-create-react-app

**Comment by steveoh** [comment]
Is that a temporary solution?

**Comment by odoe** [comment]
No, that is the recommended solution for testing purposes.

**Comment by andygup** [comment]
Closing, I think we answered @steveoh's question.

**Comment by steveoh** [comment]
It was answered but I hope this can improve in the future. It is not ideal to mock every arcgis import as I'm sure you can understand.

**Comment by safarviktor** [comment]
> This requires that you create `__mocks__` for the `@arcgis/core` modules you are importing with files being tested. Most of them can be simple like this.
> 
> ```js
> // src/__mocks__/@arcgis/core/layers/FeatureLayer.js
> export default class FeatureLayer {};
> ```
> 
> I'll get an updated CRA sample updated in the existing PR.

This works for some components, but not others. I have a bunch of tests that use this approach and work fine. Now I have come to a component in our project that uses `@arcgis/core/rest/support/IdentifyParameters` and `@arcgis/core/rest/support/IdentifyResult` and this approach does not work. Running the test results in the above mentioned error: `SyntaxError: Cannot use import statement outside a module`
