### ISSUE TITLE
@arcgis/core: assets are loaded from relative paths

### ISSUE THREAD

**Issue by bgmort** [Esri/feedback-js-api-next#79]
I'm working on building a map with @arcgis/core, and I've managed to get it working, but only on pages at the root level, not in subdirectories.  It's trying to load assets using a relative path, so if my page is at `/events/event/edit`, it will try to load the asset from `/events/event/assets/esri/...`.  I suggest when fixing this to also make it configurable, so the developer can specify the root path to load assets from, just in case `/assets` is not an option.

**Framework and build tools** 
 React with Typescript, create-react-app and netlify dev for local development

**To Reproduce**
Create a MapView component on a page at a nested path such as /test-path/page

**Expected behavior**
The assets load and the widget works

**Screenshots**
![image](https://user-images.githubusercontent.com/808854/98193255-f7db1a00-1ed9-11eb-8d37-d3000e721b40.png)

Ignore the fact that the responses are 200s, that's because webpack dev server falls back to serving / for any unmatched path.

**Browser** 
n/a, but it's Chrome 87 on macos
 
**What's your OS?**
macos 10.14.6

**API version**
ArcGIS API for JavaScript 4.18.0-next.20201104

**Comment by andygup** [comment]
> I suggest when fixing this to also make it configurable, so the developer can specify the root path to load assets from, just in case /assets is not an option.

Hi Brian, you're in luck, there is a setting for that. Try setting `config.baseUrl`. Here's an Angular example: https://github.com/Esri/feedback-js-api-next/blob/master/esm-samples/jsapi-angular-cli/src/app/app.component.ts#L78

**Comment by steveoh** [comment]
for create react app you use the package.json homepage property. https://create-react-app.dev/docs/deployment/#building-for-relative-paths

**Comment by bgmort** [comment]
@andygup  Excellent, I will do that if/when I switch back eventually.  I switched over to `esri-loader` because my production build times ballooned from under 30 seconds to nearly 6 minutes.

**Comment by RyannGalea** [comment]
Is there a way to do this now using the latest @arcgis/core package? As I'm having this issue pop up again.

**Comment by andygup** [comment]
@RyannGalea yessir: https://developers.arcgis.com/javascript/latest/api-reference/esri-config.html#assetsPath

**Comment by steveoh** [comment]
> @RyannGalea yessir: [developers.arcgis.com/javascript/latest/api-reference/esri-config.html#assetsPath](https://developers.arcgis.com/javascript/latest/api-reference/esri-config.html#assetsPath)

Can this be set to a CDN so we could skip the whole asset copying build step?

**Comment by dasa** [comment]
It can be an absolute path, like shown here: https://github.com/Esri/feedback-js-api-next/issues/90#issuecomment-746132641
Please make sure there isn't a version mismatch though if this approach is used.

**Comment by RyannGalea** [comment]
> @RyannGalea yessir: https://developers.arcgis.com/javascript/latest/api-reference/esri-config.html#assetsPath

Thanks Andy, finding documentation for this has been difficult for some reason.
