### ISSUE TITLE
@arcgis/core: webpack example has loader issues with fonts, images and svg

### ISSUE THREAD

**Issue by COV-GIS** [Esri/feedback-js-api-next#82]
Out of the box, the webpack example fails to compile and throws loader errors for the 79 font, image and svg URLs encountered in the the API's css. I see it's using webpack 5. I've never had to use loaders for those resources with webpack 4 and the built API, although I'm using the API's sass and not css. I'm curious whether anyone else is having this issue, or it's webpack 5 and loaders are required, or something else.

**Comment by odoe** [comment]
I just tried this out and I'm not getting any errors.

When you run your build, do you see the following message in the console?

```sh
Using @arcgis/core version: 4.18.0-next.20201102
```

That message is from the the `@arcgis/webpack-plugin@next`. If you don't see it, it's not loading. The plugin adds the loaders for all the assets, so that could cause that issue. I just don't know why it wouldn't load.

Are you on Windows/Linux/Mac?
What version of Node/npm?

You can bypass the webpack-plugin if you want. You can see how it does everything in [this branch](https://github.com/Esri/arcgis-webpack-plugin/tree/update-for-esm). It's not required, just provided as a helper plugin.

**Comment by COV-GIS** [comment]
Simply running the example as is with:
```json
{
  "private": true,
  "dependencies": {
    "@arcgis/core": "^4.18.0-next.20201102"
  },
  "devDependencies": {
    "@arcgis/webpack-plugin": "4.18.0-next.20201029",
    "clean-webpack-plugin": "^3.0.0",
    "css-loader": "^5.0.0",
    "html-webpack-plugin": "^5.0.0-alpha.7",
    "mini-css-extract-plugin": "^1.2.1",
    "moment-locales-webpack-plugin": "^1.2.0",
    "npm-run-all": "^4.1.5",
    "serve": "^11.3.2",
    "webpack": "^5.4.0",
    "webpack-cli": "^4.1.0",
    "webpack-dev-server": "^3.11.0"
  },
  "scripts": {
    "build": "webpack --mode production",
    "watch": "webpack -w",
    "start": "webpack serve --mode development"
  }
}
```
Win 10-64, Node 12.19.0 and npm 6.13.4.

I dug into the logs and it's `mini-css-extract-plugin` that's throwing the missing loader error.

**Comment by COV-GIS** [comment]
I tried to work this out @odoe, including omitting the plugin and setting up all loaders in project config. Always the same errors for all the css resources.

```
ERROR in ./src/index.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character ' ' (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

The interwebs were not particularly helpful. All the issues were lack of proper loaders or path issues in the css and/or webpack. Neither of which are the issue here.

I'll revisit down the road when 4.18 is released.

**Comment by COV-GIS** [comment]
Hey @odoe .

This is a windows issue.

Beyond my windows machine. Works fine on two macs and fails on 4 windows machines.

I'm closing on account of bleeding edge webpack or a dep being the most likely culprit.
