### ISSUE TITLE
@arcgis/core: projection.load() uses relative url

### ISSUE THREAD

**Issue by jag-eagle-technology** [Esri/feedback-js-api-next#86]
**Environment**
4.18.0-next.20201119 NPM ES Modules
Create React App - (React v17.0.1)
browsers list configured as per docs (last 1...)
homepage set to the root url of the application (not hosted in a directory) in package.json
tested through local and vercel/netlify deploys

**Issue**

Calling projection.load() in our react application with client side routing when not at the root url results in the following errors, caused by a relative load. We are at the path /edit/_[id]_. The library looks for wasm files at /edit/ rather than at /.

Network Request (due to client side routing homepage html is returned from this url)
![image](https://user-images.githubusercontent.com/68313738/99787834-21a46a00-2b85-11eb-9137-2e62071d1648.png)

Requests to other web assembly files are sucessfull

**Console Errors**

pe-wasm.js:5 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
(anonymous) @ pe-wasm.js:5

pe-wasm.js:5 falling back to ArrayBuffer instantiation
(anonymous) @ pe-wasm.js:5

pe-wasm.js:5 failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
(anonymous) @ pe-wasm.js:5

pe-wasm.js:5 CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0

pe-wasm.js:5 CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0

pt @ pe-wasm.js:5
main.chunk.js:8481 Error: CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
    at Object.onAbort (pe.js:5)
    at pt (pe-wasm.js:5)
    at pe-wasm.js:5

pe-wasm.js:5 Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info.
    at pt (https://localhost:3000/static/js/143.chunk.js:274:133)
    at https://localhost:3000/static/js/143.chunk.js:337:61

**Comment by bsvensson** [comment]
@jag-eagle-technology - the error `Incorrect response MIME type. Expected 'application/wasm'` makes me think that maybe your web server isn't configured with the correct MIME type(s) as per:
https://developers.arcgis.com/javascript/latest/guide/get-api/#hosting-a-local-build

**Comment by jag-eagle-technology** [comment]
The geometry engine works fine when client side routing (react router) isn't used both locally and on my netlify deploy. This screenshot shows the relative loading when at the edit/id url:
![image](https://user-images.githubusercontent.com/68313738/99757414-28ff4f80-2b54-11eb-9182-76e258a33f9b.png)

**Comment by andygup** [comment]
Try setting this:

```javascript
import config from "@arcgis/core/config.js";

config.assetsPath = "/assets"; //assuming assets are in /assets

```

**Comment by jag-eagle-technology** [comment]
That worked, thanks!
