### ISSUE TITLE
Enhancement: Set opacity for symbols like PictureMarkerSymbol

### ISSUE THREAD

**Issue by catcherholms007** [Esri/feedback-js-api-next#87]
In my workflow I need control opacity for markers. In ArcGIS js api I can change layer (GraphicsLayer) opacity only.
How can I change opacity for one graphic?

**Comment by LukashenkoEvgeniy** [comment]
It will be awesome if this functionality will be supporting

**Comment by annelfitz** [comment]
Hi @LukashenkoEvgeniy - you can do this already using a [CIMSymbol](https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-CIMSymbol.html). CIMSymbols are multilayer vector symbols that allow you to create complex symbology.

Using a CIMPictureMarkerSymbol layer, you can add a picture symbol and set the opacity using the `tintColor` property. Here's an example: https://codepen.io/annefitz/pen/LYReodg On line 66, enter the URL for your image. On line 64, you can update the opacity value in the `tintColor` property to change the opacity of your picture marker. Hopefully this helps!

**Comment by pspraveenkr** [comment]
> On line 64, you can update the opacity value in the `tintColor` property to change the opacity of your picture marker.

fyi - opacity is a value between 0 and 255 where 0 is completely transparent and 255 is completely opaque.
