### ISSUE TITLE
Enhancement: Including the @arcgis/core library in my SPFX SharePoint webpart

### ISSUE THREAD

**Issue by jscudder** [Esri/feedback-js-api-next#90]
When I include the @arcgis/core/assets contents in my SharePoint online SPFX webpart, SharePoint complains there are too many files (over 1000) included with my webpart. I know this is happening due to the number of files in @arcgis/core/assets. Is there any way I can bundle @arcgis/core/assets contents in my project to avoid this?  Right now I am able to get a basic map showing 
 (but without zoom, navigation, compass, popup and attribution controls) by including a line in the webpart: SPComponentLoader.loadCss('https://js.arcgis.com/4.18/esri/themes/dark/main.css'); 
<img width="847" alt="SpfxWebpartErrorEsriArcGisAssets" src="https://user-images.githubusercontent.com/6181613/101819755-f67abe00-3b25-11eb-9989-3118109e4ab8.PNG">

**Comment by andygup** [comment]
@jscudder you can experiment with manually removing some of the subdirectories under `/assets`. Once you remove a subdirectory you'll need to exercise all part of your app to make sure you haven't removed something that is required. 

For example:
* If you don't need 3D you could start by removing `/webscene` and then testing your app functionality.
* You could try removing `/smartMapping` if you don't require smart mapping functionality. 
* You can also remove CSS themes that you aren't using from `/themes`. You could keep this one `@arcgis/core/assets/esri/themes/dark/main.css` and experiment with removing the other unused themes. e.g. `SPComponentLoader.loadCss('@arcgis/core/assets/esri/themes/dark/main.css')`

Just some ideas that could reduce the number of files quite a bit.

**Comment by jscudder** [comment]
Here is what I did instead, and this workaround is working perfectly so far. I am no longer hosting the assets inside a SharePoint site. When my SharePoint map webpart is loading I make these two calls:

SPComponentLoader.loadCss("https://cdn.jsdelivr.net/npm/arcgis-js-api@4.18.0-next.20201213/assets/esri/themes/dark/main.css");
config.assetsPath = 'https://cdn.jsdelivr.net/npm/arcgis-js-api@4.18.0-next.20201213/assets';

Everything is working perfectly now with no more errors or UI issues.
