### ISSUE TITLE
@arcgis/core: Mesh geometry not rendering in global scene view after build

### ISSUE THREAD

**Issue by tbock** [Esri/feedback-js-api-next#95]
**Describe the bug**
When using a feature layer to render client side mesh geometry the renderer appears to fail and I am getting these errors in the console: 
WebGL: INVALID_OPERATION: getUniformLocation: program not linked
WebGL: INVALID_OPERATION: useProgram: program not valid

Issue is only occurring on ng build and deployed NOT when using ng server. 

**Framework and build tools** 
 - Angular 10.1.6
 - Node 14.15.4

**To Reproduce**
Create mesh3d  feature layer using client side json only with simple renderer.

**Expected behavior**
In dev environment using ng serve this occurs:
![image](https://user-images.githubusercontent.com/4040295/104659095-e734e600-5678-11eb-8e25-20593ce039b4.png)

Once built with ng build --prod this occurs. I can still click where I know the geometry is supposed to be and it will be highlighted but nothing is rendered.
![image](https://user-images.githubusercontent.com/4040295/104658999-be145580-5678-11eb-8cd1-44177ec661ca.png)

**Browser (check https://whatismybrowser.com/)** 
 - Chrome 87 on Windows 10
 
**What's your OS? (check https://whatsmyos.com):**
 - OS: Windows 10* 64-bit
 - Device: Windows desktop PC

**API version (check your console)**
 - Version: 4.19.0-next.20210114

**Comment by andygup** [comment]
Thanks @tbock. 
* Can you reproduce this with 4.18.1?
* Can you provide a codepen, stackblitz or github repo to see if we can reproduce this?

**Comment by tbock** [comment]
Sorry... should of mentioned ... this occurred with 4.18.1 first then I bumped to next version to see if I got the same issue.   I will boil it down to something I can share and get back to you.  Thanks

**Comment by andygup** [comment]
>> Issue is only occurring on ng build and deployed NOT when using ng server.

Travis, do you see the same issue on your local machine when you create a `dist` build? Or is this only showing up on your production machine?

**Comment by tbock** [comment]
Yes I just confirmed this is happening in the dist build on my local machine as well.

**Comment by andygup** [comment]
Can you run `npm ls terser` and tell us what version you are using. There's a possibility that a bug in terser could be messing things up when the app is minimized for production.

**Comment by tbock** [comment]
![image](https://user-images.githubusercontent.com/4040295/104669643-53badf80-568f-11eb-97aa-61c348a52e99.png)

https://github.com/tbock/arcgis-core-issue

**Comment by andygup** [comment]
Hi Travis, sorry for the delay, I was running a bunch of tests. I'm writing up the bug reports and we'll tentatively schedule a fix for 4.19 release in April. One potential temporary workaround is to use `esri-loader`. I'll go ahead and close this issue, thanks for bringing it to our attention.
