### ISSUE TITLE
@arcgis/core: errors cause ci failure

### ISSUE THREAD

**Issue by steveoh** [Esri/feedback-js-api-next#97]
These esri errors are causing ci to fail. We do not want to set CI to false. Will you suppress these errors as they aren't helpful to developers. 

> react-scripts build
>
> Creating an optimized production build...
>
> Treating warnings as errors because process.env.CI = true.
> Most CI servers set it automatically.
>
> Failed to compile.
>
> ./node_modules/@arcgis/core/core/workers/workers.js
> Critical dependency: the request of a dependency is an expression
> 
> ./node_modules/@arcgis/core/core/workers/WorkerFallback.js
> Critical dependency: the request of a dependency is an expression

**Comment by odoe** [comment]
Is this travis? Have you tried setting `warnings_are_errors: false` in `.travis.yml`. Other CI's should have similar. These are expected webpack warnings, not errors, related to dynamic loading of worker files.

**Comment by steveoh** [comment]
> Have you tried setting `warnings_are_errors: false` in `.travis.yml`. 

> We do not want to set CI to false.

We would like to keep warnings as errors to catch other issues.

**Comment by odoe** [comment]
I don't know if there is a way to suppress warnings, they're not from the API, they're from webpack. You can config webpack to suppress them I think, but you'd need to eject CRA.

**Comment by odoe** [comment]
Found something, this should remove it.

https://medium.com/tomincode/hiding-critical-dependency-warnings-from-webpack-c76ccdb1f6c1

```js
module.exports = {
  // ... your webpack configuration ...
  plugins: [
    new webpack.ContextReplacementPlugin(
      /\/@arcgis\/core\//, // I think this is right regex
      (data) => {
        delete data.dependencies[0].critical;
        return data;
      },
    ),
  ]
}
```

**Comment by steveoh** [comment]
hmm interesting. thanks for looking into it.

**Comment by steveoh** [comment]
closed by https://github.com/Esri/feedback-js-api-next/pull/101?

**Comment by andygup** [comment]
@steveoh  should be fixed. Can you also verify on your end?
