### ISSUE TITLE
@arcgis/core: Is ESModule type version for building with vite on the way?

### ISSUE THREAD

**Issue by Aiooioo** [Esri/feedback-js-api-next#98]
**Describe the bug**
Are u considering the building support with new vite cli tool, as this is a totally new tool, and can be used in many framework. But it's very different with webpack, as it uses rollup for bundle build.
The @arcgis/core package is now not running very well with vite latest version.

**Framework and build tools** 
 - Vite

**To Reproduce**
Build app with vite.

**Expected behavior**
app bundle run into error...

**Screenshots**
noop

**Browser (check https://whatismybrowser.com/)** 
 - Browser: [e.g. "Chrome 87 on Windows 10"]
 
**What's your OS? (check https://whatsmyos.com):**
 - OS: Win 10 x64
 - Device: Desktop PC

**API version (check your console)**
 - Version: 4.18.0

**Additional context**
Add any other context about the problem here. Please note if this issue has been reported elsewhere.

**Comment by andygup** [comment]
@Aiooioo we might take a look at some point. Did you review our rollup sample for possible configuration hints? https://github.com/Esri/jsapi-resources/tree/master/esm-samples/rollup

What errors are you getting?

**Comment by odoe** [comment]
Is this with the react/preact/lit vite app?
I tried with vanilla and works
https://github.com/odoe/vite-jsapi

I can try with react

**Comment by Aiooioo** [comment]
woo, thanks. I use react with vite, and i will recheck the conf from your samples.

**Comment by andygup** [comment]
Hi @Aiooioo I'll go ahead and close this, if you have questions feel free to reopen or open a new issue.
